code/modules/atmospherics/machinery/datum_pipeline.dm

Fixes the GAME by being literally just a port of https://github.com/tgstation/tgstation/pull/55918
idk it really fucking isn't
oh yeah I guess the tests won't fail anymore or something

Fixes the reason the Integration tests broke

---

code/datums/helper_datums/getrev.dm
code/modules/tgs/v3210/api.dm
html/changelog.html

fixes some busted variables
not broken = good

Fix compile errors

---

_maps/map_files/Heliostation/Heliostation.dmm

Adding in all the stupid nonsense I forgot with the latest update.
It's good to have all the features in the map
:cl:
add: Cytology and fusion room added to heliostation
add: more space heaters to Heliostation
fix: Fixed some broken areas on heliostation
fix: Fixed aux base door on Helio
fix: Fixed teleporter on Helio
/:cl:

Heliostation Update Fix

---

fulp_modules/nightmare_edit/nightmare.dm
tgstation.dme

Remake of #76 
:cl:
qol: Nightmares are no longer smart in-game, rather than it being a rule.
/:cl:

Nightmares arent smart

---

fulp_modules/fulp_clothing/wintercoats/code/wintercoats.dm

fixes a typo @Homingpenguins made
typo = bad
:cl:
spellcheck: fixed typo

fixes dumb misspelling

---

code/controllers/subsystem/job.dm

Not sure if there's a way to make this modular, I made this at 3 AM
Our chain of command is different, code should reflect this.
Not necessary.

Chain of Command edit

---

fulp_modules/jobs/deputy/code/deputy.dm
fulp_modules/jobs/deputy/code/deputy_block.dm

Fixes broken stuff

---

fulp_modules/jobs/antag_protection_overwrites.dm

Fuck your config, now they're never antag.

Fixes command antag because SOMEONE (totally not me) didnt do it properly

---

fulp_modules/bloodsuckers/code/antagonists/bloodsucker_datum.dm
fulp_modules/bloodsuckers/code/bloodsucker/bloodsucker_life.dm

this took me over 5 hours to figure out how to fix, thanks TG.
:cl:
fix: Bloodsuckers are no longer colorblind after Torpor/Sol.
/:cl:

Fixes bloodsucker's colorblindness

---

code/game/gamemodes/objective.dm
fulp_modules/bloodsuckers/code/bloodsucker/bloodsucker_objectives.dm
fulp_modules/bloodsuckers/code/gamemodes/traitorsucker_gamemode.dm
fulp_modules/bloodsuckers/code/readme.MD

Might possibly be able to be given to players somehow? Idk im not a mod
Also stealthily adding a change to traitorsucker gamemode, because copypaste went wrong.
Not needed

Improves Bloodsucker objective code slightly

---

fulp_modules/toys/code/toys.dm

it took me three days to figure out that I did this
I shouldn't be allowed near a computer
:cl:
spellcheck: deleted a stray period in the supermatter toy description 
/:cl:

when the grammar mistake

---

_maps/map_files/Heliostation/Heliostation.dmm

fixes the shitty layer manifold

fuckin smartpipes (hotfix)

---

fulp_modules/ZFulpcode/modules/jobs/inventories.dm
tgstation.dme

they actually have the rest of their gear now
see above
:cl:
fix: makes it so spawning the crowbar doesn't delete everything else
/:cl:

Security crowbars but with less shitcode

---

_maps/map_files/SeleneStation/SeleneStation.dmm

Wouldn't it be nice if my map actually worked?
:cl:
fix: Fixes dark spots, some minor bugs, and the holodeck on selenestation
/:cl:

Selene fixes

---

_maps/map_files/SeleneStation/SeleneStation.dmm

Adds a fuel tank to the Engineering Lobby 
Makes the engineers happy
:cl:
add: Fuel tank to Engineering Lobby
/:cl:

SeleneStation : Adding Fuel tank to Engineering

---

_maps/map_files/SeleneStation/SeleneStation.dmm

Changed the morgue doors
Mapping standards I guess
:cl:
fix: Changed the morgue doors
/:cl:

SeleneStation : Changed the morgue doors

---

fulp_modules/ZFulpcode/modules/jobs/huds.dm
fulp_modules/main_features/jobs/brigdoc/code/brigdoc.dm
fulp_modules/main_features/jobs/deputy/code/deputy.dm
fulp_modules/main_features/jobs/job_integration.dm

Thanks to the author of https://github.com/fulpstation/fulpstation/issues/153 for letting me know of this issue! Fixed it and cleaned unused variables which were leftovers from the old repo's HUD implementation (which we don't use and it was me being dumb)
:cl:
fix: Fixed having no SecHUD icon in the case that you had no ID.
/:cl:

We've got you surrounded sir come fix hud icons

---

fulp_modules/readme.md

Adds Fulp flowchart to the readme

---

_maps/map_files/Heliostation/Heliostation.dmm

The buttons were as tedious as the requests consoles
m

Finishes Heliostation directionals

---

fulp_modules/main_features/jobs/deputy/code/deputy_clothing.dm

deputy hotfix

---

_maps/map_files/Heliostation/Heliostation.dmm

Removed the request control from cargo
idk tg removed it
:cl:
del:Removed the request control from cargo
/:cl:

Heliostation: Removed the request control from cargo

---

_maps/map_files/SeleneStation/SeleneStation.dmm

Construction room in engineering now has 3 tool 2 electrical and 1 welding closets
More fun for the engineers of the station
:cl:
add: Construction room in engineering now has 3 tool 2 electrical and 1 welding closets
/:cl:

SeleneStation: Adding electrical and welding closet to construction room in engineering

---

fulp_modules/main_features/mentorhelp/mentor.dm
fulp_modules/main_features/mentorhelp/mentor_clientprocs.dm
fulp_modules/main_features/mentorhelp/mentorhelp.dm
fulp_modules/main_features/mentorhelp/mentorpm.dm
fulp_modules/main_features/mentorhelp/mentorsay.dm

Imagine thining Mentorhelp runs perfectly fine because no one has told you anything, then you see
[2021-05-29 20:44:35.923] MENTOR: MENTORHELP: John Willard (<a href='?src=mentor;mentor_follow=[mob_336];mentor_token=2118888674049100129743910054746515'>F</a>): test
Image for reference because Github actually makes it a fuckin link
Also changes comments and stuff whatever doesnt matter

(Hopefully) Fixes Mentorhelp logging

---

_maps/map_files/Heliostation/Heliostation.dmm

I forgot copy+pasting maps didn't bring over areas if you didn't make them visible with ctrl+1 beforehand
I expect my GBP: No update between 3 to 4 business days
:cl:
fix: fixed maint room in Helios being spaced
/:cl:

Fixes this part of maint being in space in Helios

---

fulp_modules/readme.md

Dont want our contributors to get flooded with emails about failing checks.

Adds workflows to the readme

---

_maps/map_files/SeleneStation/SeleneStation.dmm

Adding an air alarm to HFR
Its a nice addition also standards
:cl:
add: HFR room now has an air alarm
/:cl:

SeleneStation: Adding air alarm to HFR

---

_maps/map_files/SeleneStation/SeleneStation.dmm

Whoops, missed this and I don't wanna revert just to fix it. Quickly pushing this through.

Fixes the atmos engine APC

---

_maps/map_files/Heliostation/Heliostation.dmm

Fixes the stupid pipes on Heliostation

---

fulp_modules/main_features/bloodsuckers/code/gamemodes/monsterhunter_gamemode.dm
fulp_modules/main_features/bloodsuckers/code/powers/fortitude.dm
fulp_modules/main_features/bloodsuckers/code/powers/monstertrack.dm

dies
:cl:
fix: Monster hunters now spawn!
balance: Flow now gives damage resistance
balance: Monster Hunters no longer use Blood to track Monsters
/:cl:

Monster hunters spawn, get buffed Fortitude, and no longer take blood to track monsters

---

_maps/map_files/SeleneStation/SeleneStation.dmm

Removes double grille in the abandoned bar
I need work so it is being done
:cl:
del: Double grille in abandoned bar
/:cl:

SeleneStation: Double grilles in abandoned bar

---

_maps/map_files/SeleneStation/SeleneStation.dmm

Fixes mismatched walls in engineering 
consistency
:cl:
fix: Mismatched walls in engineering 
/:cl:

SeleneStation: Mismatched walls in engineering 

---

fulp_modules/main_features/bloodsuckers/code/gamemodes/monsterhunter_gamemode.dm

Monster hunter hotfix

---

fulp_modules/main_features/jobs/brigdoc/code/brigdoc.dm

I didnt test this lol
:cl:
fix: Brig Doctor's PDAs now start connected to their ID
/:cl:

fixes brig doc's PDA

---

_maps/map_files/SeleneStation/SeleneStation.dmm

Replaced the cabinet with a normal one in the sec checkpoint
apparently there should only be one filing cabinet of that kind
:cl:
fix: Replaces cabinet in sec checkpoint to be a normal one
/:cl:

SeleneStation: Changed the filing cabinet

---

_maps/map_files/SeleneStation/SeleneStation.dmm

Moved some of the machines in botany around so it is less clustered
complaint was made about botany getting clustered with the current layout although this one is fairly simple I hope it fixes the issue without having to change it completely 
:cl:
balance: Moved machines in botany around a bit to help with cluttering 
/:cl:

SeleneStation: Small botany renovation 

---

fulp_modules/main_features/bloodsuckers/code/bloodsucker/bloodsucker_crypt.dm

Quick fix, Tremere Bloodsuckers can now properly revive the dead, and cancelling out of a TGUI menu will no longer force you to wait the timer anyways.

Fixes Tremere revival & cancelling timers

---

.vscode/settings.json
fulp_modules/Z_edits/container_init/machine_init.dm
fulp_modules/features/body_cameras/body_camera.dm
fulp_modules/features/body_cameras/readme.md
tgstation.dme

Security can now purchase 6 body camera upgrades at the SecTech vendor, allowing you to connect bodycameras to a jumpsuit using your ID. This gets deactivated if you re-use your ID on the jumpsuit, get EMP'ed, or get the suit stripped off your person.
Holy shit pleasep lease please ple s
:cl:
add: Body camera upgrades at your local SecTech vendor
/:cl:

Body cameras 2.0

---

fulp_modules/fulp_configs/code/fulp_config.dm
fulp_modules/main_features/mentorhelp/mentorsay.dm

two people can play this game
how is hardcoding me into HOP not good for the game
:cl:
admin: Adds the Head of Pseudostaff role to MSay
/:cl:

Adds the Head of Pseudostaff

---

fulp_modules/main_features/mentorhelp/mentor.dm
fulp_modules/main_features/mentorhelp/mentor_clientprocs.dm

For some reason /datum/mentors/New(ckey) only works for admins???? Whatever. At least it works now. I don't like mentorhelp code.

Contributor hotfix

---

fulp_modules/fulp_configs/code/fulp_config.dm

fulp_config hardcoding

---

fulp_modules/main_features/mentorhelp/mentorsay.dm

I was told people are confusing it with Medical comms.

changes contributor's msay color

---

fulp_modules/main_features/mentorhelp/mentor.dm
fulp_modules/main_features/mentorhelp/mentor_clientprocs.dm
fulp_modules/main_features/mentorhelp/mentorwho.dm

We already have checks elsewhere to prevent admins from showing up where we don't want them.

[Please TM first] Fixes Admins not seeing Msay when deadminned

---

fulp_modules/features/body_cameras/body_camera.dm

unregister body camera proc is called when unequipping the jumpsuit... and it checks for the non existent ID you use to unregister it.

Fixes body camera unregister runtime

---

_maps/map_files/SeleneStation/SeleneStation.dmm

Replaced the colors in incinerator so waste isnt sent to space there, too.

fucks with selene a bit idk

---

code/___fulp_defines/fulp_defines.dm
fulp_modules/main_features/bloodsuckers/code/powers/masquerade.dm

Masquerade status effect
Also because people can't fucking notice the glowing action button telling them that Masquerade is on, so they ahelp saying bloodsucker is shit and broken because they arent healing in Torpor.
:cl:
add: Masquerade status effect
/:cl:

Masquerade status effect

---

_maps/map_files/SeleneStation/SeleneStation.dmm

[Selene] Adds boxing gloves locker

---

fulp_modules/Z_edits/tg_edits.md
tools/build/build.js

This is why our checks are failing

Re-adds removed undocumented TG edit and documents it

---

_maps/map_files/Heliostation/Heliostation.dmm
fulp_modules/features/prison_kitchen/_restaurant.dm

I completely forgot that cables dont shock grilles unless there's plating under it

Replaces floor with plating

---

fulp_modules/main_features/mentorhelp/mentorhelp.dm

feature was removed due to being unused and not worth the TG edit. This way it doesnt edit TG files and can be used, since there's recently had times it should actually be put in place.

Muting someone from adminhelps now mute you from mentorhelps

---

fulp_modules/main_features/bloodsuckers/code/powers/lunge.dm

Fixes lunge permanently slowing you down / Fixes lunge permanently immobilizing you

---

_maps/map_files/SeleneStation/SeleneStation.dmm
fulp_modules/features/body_cameras/body_camera.dm
fulp_modules/main_features/beefmen/code/modules/mob/beefman.dm
fulp_modules/main_features/beefmen/code/modules/mob/beefman_clothing.dm
fulp_modules/main_features/jobs/deputy/code/deputy_clothing.dm

Security sashes now use a little less copypasta code, the security ones are slightly armored, and body cameras now fit on sashes and plasmamen security suits now, too. (Used to be ONLY regular sec jumpsuits)
yes its tested, cry about it
Sashes are already shit, let's at least make sec keeping theirs, not be 100% a mistake.
Also security bodycams working on security suits is cool ig.

Fixes body cameras, buffs Sashes

---

_maps/map_files/Heliostation/Heliostation.dmm
_maps/map_files/PubbyStation/PubbyStation.dmm
_maps/map_files/SeleneStation/SeleneStation.dmm

No more station-wide AI-esque camera bug!

Fixes aux base on all fulp maps

---

_maps/map_files/Heliostation/Heliostation.dmm

I don't know why they were purple, I set them to the color the rest of their pipes have, and made them visible.
Engineers won't accidentally sabotage the SM anymore.

[Helio] fixes SM chamber

---

_maps/map_files/PubbyStation/PubbyStation.dmm

Turns out I'm not done with pubby yet. Not the fulp update.

Pubby update

---

fulp_modules/main_features/beefmen/code/modules/mob/beefman.dm

I've played beefman for about 2 days and every single round, at least 1 person has walked up to me and told me 'stranger' just to inconvenience me. I've even had someone follow me around for ~15 minutes just repeatedly saying it to me, and when I left they continued over the radio.
We're the only server with Beefman, and we still have usually 0-1 beefmen per round. Whenever there IS one, they constantly get people intentionally or accidentally triggering their phobia throughout the entire round, it just isn't fun to play as Beefman.
:cl:
del: Beefman's stranger phobia.
/:cl:

Removes Beefmen's phobia

---

_maps/map_files/Heliostation/Heliostation.dmm

I know Heliostation v2 is a WIP, but I thought it's time we take it a step further.
Heliostation v3 is Heliostation, improved in every single way.
Tons of new things, with neat little hidden easter eggs for everyone.
Also has the possibility of maintenance pills being found in maintenance!
Includes a plasmaman Medbay, as is common for Helian's maps.
Heliostation improved
:cl:
add: Welcome the new redesign of Heliostation - Heliostation 3!
/:cl:

Heliostation v3

---

_maps/map_files/Heliostation/Heliostation.dmm

Reverts fulpstation/fulpstation#293

Revert "Heliostation v3"

---

fulp_modules/Z_edits/tg_edits.md
fulp_modules/main_features/bloodsuckers/readme.MD

#282 modularized bans
I wont cry when its time for TGU

Updates list of TG edits

---

code/game/machinery/computer/crew.dm
code/modules/jobs/jobs.dm
fulp_modules/features/fulp_clothing/digitigrade/code/digi_lizard.dm
fulp_modules/main_features/beefmen/code/modules/mob/beefman.dm
fulp_modules/main_features/jobs/brigdoc/code/landmark.dm
fulp_modules/main_features/jobs/deputy/code/deputy.dm
fulp_modules/main_features/jobs/deputy/code/deputy_clothing.dm

Deputies keep telling me that they are part of security, hopefully this shuts them up finally.
Gives them a security belt with all their gear so they don't have to steal one from a security officer's locker (no more excuses for opening one now).
This is how I intended deputies to be in the first place.

Deputy Update 4: Full-departmental Deputies & Secbelt

---

code/controllers/subsystem/job.dm
fulp_modules/Z_edits/tg_edits.md

We lost it during a TGU thanks to no documentations 
@SgtHunk your mother

re-adds Fulp Chain of Command

---

fulp_modules/readme.md

Improved readme

---

_maps/map_files/SeleneStation/SeleneStation.dmm

- Moved the crayons in dorms to a more efficient location one table north.
Making it so I can get the crayons from the north table in dorms, not south, for better feng shui.
Antags can get crayons faster and win.
:cl:
add: crayons from southern dorms table to northern.
/:cl:

Making Selene better

---

fulp_modules/main_features/bloodsuckers/code/rulesets/bloodsucker_rulesets.dm

The rest is all config
we split deputies into several jobs.

Deputy bloodsucker hotfix

---

fulp_modules/main_features/bloodsuckers/code/bloodsucker/bloodsucker_life.dm
fulp_modules/main_features/bloodsuckers/code/powers/distress.dm
fulp_modules/main_features/bloodsuckers/code/powers/mesmerize.dm
fulp_modules/main_features/bloodsuckers/code/powers/recuperate.dm

I got reports that Recuperate doesn't stop costing blood when deactivated?
If two bloodsuckers try to mesmerize, shit gets fucked up, so I won't allow 2 mesmerizes to go through.
Distress was screeching to all bloodsuckers rather than just their master

Bloodsucker fixes

---

fulp_modules/features/prison_kitchen/hos_prefix.txt

I was forced to do this

---

fulp_modules/tg_edits.md

Documents mapping TG edit and moves tg_edits to fulp_modules

---

fulp_modules/features/ert/code/advanced_equipment.dm
fulp_modules/features/ert/code/antag_datum.dm
fulp_modules/features/ert/code/ert_datum.dm
fulp_modules/features/ert/code/ert_outfit.dm
fulp_modules/features/ert/code/hardsuits.dm
fulp_modules/features/ert/code/procs.dm
fulp_modules/features/ert/code/safety_moth.dm
tgstation.dme

#299 because for some reason that kept failing checks but it showed no errors on my end, apparently a missing file?
Trying again on master.
Also fixes an ERT hardsuit not being space proof.

Safety moth again

---

_maps/heliostation.json
_maps/selenestation.json
code/modules/jobs/job_types/prisoner.dm

'xcept on fulp maps that have prison restaurant :)
Prisoners are worse greytiders than assistants as they have literally nothing to do, how are 4 prisoners meant to share one console of Orion Trail? And they cant escape either, not without reason to, anyway.

Literally just disables Perma prisoners

---

_maps/map_files/PubbyStation/PubbyStation.dmm
_maps/map_files/SeleneStation/SeleneStation.dmm
_maps/pubbystation.json
_maps/selenestation.json

Pubbystation: Enlarges Permabrig, Adds Prisoners, Adds Restaurant bots, Adds more Shaft miner lockers
Selenestation: Adds a skill station in Perma, makes CQC actually work in Selene's kitchen

Pubbystation and Selenestation updates

---

fulp_modules/Z_edits/nightmare_edit/nightmare.dm
fulp_modules/Z_edits/race_bans/bans.dm

Race code now should work roundstart

---

_maps/map_files/SeleneStation/SeleneStation.dmm

Adds an Autodrobe to Selene dorms.
More clothing variety for people to wear during shifts.
:cl:
add: Adds an Autodrobe to Selene dorms
del: Removes a potted plant from Selene dorms
/:cl:

Adds an Autodrobe to Selene dorms (attempt #2)

---

_maps/map_files/SeleneStation/SeleneStation.dmm

Just a few random things I found around Selene:
Added pipes that connect a vent and scrubber in holodeck control that were previously unconnected.
Removed one of the showers in the locker room because there was 2 on one tile.
Fixed fluid pipes in the kitchen, botany and janitorial because they never properly connected to the water supply.
Removed misplaced holodeck tiles that were under the doors leading into the holodeck
Fixed the botany stationary water tank not actually connecting to the fluid pipes beside it
General map fixes
:cl:
fix: Added atmos pipes to Selene holodeck control
fix: Fixed plumbing network around Selene service 
/:cl:

Minor map fixes around Selene

---

_maps/map_files/SeleneStation/SeleneStation.dmm

so I have this problem, I like service departments working together, and I like both chaplains and curators.
But here's my problem;
Curators and Chaplains don't work together, like you would expect from other paired up service departments.
My solution:
Merge library and chapel together.
yea

[Selene] adds a door between Chapel and Library

---

_maps/map_files/PubbyStation/PubbyStation.dmm

updates pubby to latest map depot version

[MDB IGNORE] Pubby update

---

fulp_modules/main_features/bloodsuckers/code/bloodsucker/bloodsucker_objectives.dm
fulp_modules/main_features/bloodsuckers/code/bloodsucker/bloodsucker_objects.dm

masquerade update got merged before i can test it all

bloodsucker objective quickfix

---

_maps/_basemap.dm
code/__DEFINES/atom_hud.dm
code/__DEFINES/role_preferences.dm
code/__HELPERS/global_lists.dm
code/__HELPERS/roundend.dm
code/controllers/subsystem/job.dm
code/controllers/subsystem/ticker.dm
code/datums/hud.dm
code/game/area/areas/shuttles.dm
code/game/gamemodes/objective.dm
code/game/machinery/computer/crew.dm
code/game/objects/items/devices/scanners.dm
code/modules/admin/verbs/adminhelp.dm
code/modules/client/client_procs.dm
code/modules/mob/living/carbon/human/examine.dm
code/modules/mob/living/carbon/human/species.dm
code/modules/surgery/bodyparts/_bodyparts.dm
fulp_modules/Z_edits/preferences/_fulp_preferences.dm
fulp_modules/fulp_configs/code/sound.dm
fulp_modules/main_features/beefmen/code/modules/language/russian.dm
fulp_modules/main_features/bloodsuckers/code/antagonists/bloodsucker_datum.dm
fulp_modules/main_features/mentorhelp/ahelp_reject.dm
fulp_modules/main_features/mentorhelp/readme.MD
fulp_modules/mapping/plaques/commission_plaques.dm
fulp_modules/tg_edits.md
tools/build/build.js

Standardizes Fulp edit notes found in TG code so its easier to find our edits whenever needed.

Standardizes fulp edits (+removes a TG edit from mentorhelp)

---

fulp_modules/Z_edits/fulp_jobs/unlock_times.dm

Shaft miner should actually be behind a wall now, also added the QM there because I realized we can have a first round Acting Captain QM and this is just bad...
I hate when the "Captain" declares Cargonia

Fix an oversight on miner unlock and add QM to the list

---

fulp_modules/Z_edits/preferences/beefman_preferences.dm
tgui/packages/tgui/interfaces/PreferencesMenu/preferences/species/beefman.ts

beefmen tgui preference stuff

---

_maps/map_files/SeleneStation/SeleneStation.dmm

a
Removes three static spawn maint pills in Selene and replaces them with random maint loot spawners.
No more tricking people with fake maint pills that won't add you to the leaderboard.
:cl:
add: three maint loot spawners
del: Removed three static spawn maint pills from Selene
/:cl:

Removes static spawn maint pills from Selene and replaces them with random maint loot spawners

---

fulp_modules/main_features/mentorhelp/ahelp_reject.dm

I dont like how easy it is to confuse with "IC Issue" and "Denied"

Updates ahelp mhelp rejection message

---

tgui/packages/tgui/interfaces/PreferencesMenu/jobs/jobs/engineering_deputy.ts
tgui/packages/tgui/interfaces/PreferencesMenu/jobs/jobs/science_deputy.ts
tgui/packages/tgui/interfaces/PreferencesMenu/jobs/jobs/service_deputy.ts
tgui/packages/tgui/interfaces/PreferencesMenu/jobs/jobs/supply_deputy.ts

copy pasted the descriptions and forgot to swap out the second 'Medbay'.

deputy tgui preference fix

---

code/game/gamemodes/objective.dm
fulp_modules/main_features/bloodsuckers/code/antagonists/bloodsucker_datum.dm
fulp_modules/main_features/bloodsuckers/code/bloodsucker/bloodsucker_objectives.dm

Admins can now force a Bloodsucker to break/fix Masquerade and can give/take away levels.

Adds more things to Bloodsuckers in Traitor Panel to make debugging them easier

---

fulp_modules/main_features/bloodsuckers/code/bloodsucker/bloodsucker_life.dm

this is the most complained about thing about Bloodsuckers, I'm tired of it.
I dont know
:cl:
del: You, the Player.
/:cl:

Bloodsuckers in Masquerade will heal in Torpor

---

fulp_modules/main_features/mentorhelp/mentorpm.dm

Currently they cant start new mhelps, but they can reply to already existing ones.

Admin muted people cant reply to started mhelps anymore

---

fulp_modules/main_features/bloodsuckers/code/antagonists/bloodsucker_datum.dm
fulp_modules/main_features/bloodsuckers/code/bloodsucker/bloodsucker_coffin.dm
fulp_modules/main_features/bloodsuckers/code/bloodsucker/bloodsucker_crypt.dm
fulp_modules/main_features/bloodsuckers/code/bloodsucker/bloodsucker_frenzy.dm
fulp_modules/main_features/bloodsuckers/code/bloodsucker/bloodsucker_integration.dm
fulp_modules/main_features/bloodsuckers/code/bloodsucker/bloodsucker_life.dm
fulp_modules/main_features/bloodsuckers/code/bloodsucker/bloodsucker_objectives.dm
fulp_modules/main_features/bloodsuckers/code/powers/_powers.dm

Bloodsuckers is a large portion of our entire codebase so there's a lot of code to constantly be going through, so one of my pastimes is reading over it and updating old code.
I moved more of Swain's comments to https://hackmd.io/@fulpstation/HyntHUigF since that's where they should all be.

Bloodsucker minor code improvements

---

_maps/map_files/SeleneStation/SeleneStation.dmm

Replaces the skeleton corpse in Selene maints with remains and a random fly organ spawner.
Powergamers beware, you're in for a scare!
No more powergamers rushing skeleton species shift start.
:cl:
del: Removed skeleton corpse in Selene maints
/:cl:

Removes skeleton corpse from selene maints

---

_maps/map_files/SeleneStation/SeleneStation.dmm

Swaps the art gallery and chapel creating a larger, connected curator area and a less plain (still rectangular chapel area).
Also deletes the giant guillotine maintenance room, and moves the bloody toolbox into the clown maint's room.
More interesting design of chapel and library

Selenestation library and chapel changes

---

_maps/map_files/SeleneStation/SeleneStation.dmm

removes soul from selene library

---

fulp_modules/features/antag_tips/code/antag_tip_integration.dm

Kills enrico

---

_maps/map_files/SeleneStation/SeleneStation.dmm

CHANGE LOG 
fixes other peoples' mistakes 
changelog END

Reina contributing and its consequences have been a disaster for the human race

---

_maps/map_files/Heliostation/Heliostation.dmm
_maps/map_files/SeleneStation/SeleneStation.dmm
fulp_modules/Z_edits/christmas.dm
tgstation.dme

Christmas trees now give normal gifts rather than admin gifts
Also adds a subtype of christmas trees that DO give admin gifts in case any admin needs it
Because the trees are now harmless, Helios now has one and Selene has one in bar now
Removes fun for Christmas before it happens

You're a Mean One, Helianthus

---

fulp_modules/features/jobs/deputy/deputy.dm

Ye that
Fix good
Nothing to see here
fix: You can thank me for fixing your broken Selene station Joyce!
/:cl:

Fix broken pipe at Helio station uno.

---

fulp_modules/features/bloodsuckers/code/bloodsucker/bloodsucker_life.dm

please stop breaking my antag

---

fulp_modules/features/jobs/brigdoc/beacon.dm

Changed outdated description of potassium iodide left over from the old rad system so it describes what it actually does
:cl:
del: Outdated potassium iodide description
add: accurate description
/:cl:

Fixed outdated radiation flavortext

---

fulp_modules/features/jobs/deputy/deputy.dm
fulp_modules/features/jobs/deputy/deputy_clothing.dm

Deputy berets cant be knocked off
Service beret counts as a beekeeper hat
Deputies get tablets instead of PDAs

Deputy update

---

fulp_modules/Z_edits/fulp_bans.dm
tgstation.dme

Re-adds fulp bans

---

fulp_modules/Z_edits/inititalize_edits/closet_init.dm
fulp_modules/features/clothing/digitigrade/code/digi_shoes.dm

read the tin
less locker bloat = good, probably
shitcode may be present
:cl:
qol: Digitigrade shoes are now in locker Garment Bags.
/:cl:

Puts digitigrade shoes in Garment Bags

---

_maps/map_files/Heliostation/Heliostation.dmm

Fucking Blaberface abused this and spaced the entire station as Swarmer.
Also replaces the turbine space injector that isn't even fucking maxed roundstart with a cooler passive vent.

Fixes broken ass area on Helios tation

---

fulp_modules/features/species/beefmen/beefman_preferences.dm
fulp_modules/features/species/beefmen/mob/beefman.dm
fulp_modules/global_vars.dm
fulp_modules/tg_edits.md
tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/beefman_features.tsx
tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/species_features.tsx

Beefmen trauma is now a preference that you can choose
Also removes the deadchat one, since it was too good to keep now that it isn't just random.
some beefmen dont want hypnotism every round. some might, idk.

Beefmen brain trauma is now a preference

---

fulp_modules/mapping/ruins/space/beef_station.dmm

removes merge conflict marker

---

fulp_modules/features/species/beefmen/phobetor_trauma.dm

[2022-01-05 01:44:54.433] ## TESTING: GC: -- [0x201c55d] | /obj/effect/hallucination/simple/phobetor was unable to be GC'd --

fixes beefmen tear qdel'ing

---

fulp_modules/features/jobs/brigdoc/brigdoc.dm

I was gonna add a playtime lock for ERTs but they aren't a job and there isn't a system for antagonist playtime lock and ERTs aren't called enough for me to waste my time doing that. When looking into that I found this:
Brig Phys now grants medical xp instead of security.
Brig Phys was recently changed to require medical playtime instead of security, but with this change they neglected to change what exp was granted. Brig Phys isn't a security job, so playing it to unlock HOS is stupid.
:cl:
help
/:cl:

Brig Physician playtime now grants mecical exp instead of security

---

_maps/map_files/Heliostation/Heliostation.dmm

The button didn't close the blast doors, now it does.
Lawyers winning

Fixes the Heliostation blue law office privacy button

---

fulp_modules/features/bloodsuckers/code/powers/_powers.dm
fulp_modules/features/bloodsuckers/code/powers/targeted/mesmerize.dm
fulp_modules/features/bloodsuckers/code/powers/tremere/auspex.dm
fulp_modules/features/bloodsuckers/code/powers/tremere/dominate.dm
fulp_modules/features/bloodsuckers/code/powers/tremere/thaumaturgy.dm

Fixes Bloodsucker power cooldowns, especially for Tremere.

Bloodsucker cooldown fixes

---

_maps/map_files/SolitaireStation/Solitairestation.dmm

-Fixes random engine tile in fore maint
-Fixes sec checkpoint tile outside of the checkpoint
-Makes the emitter zone part of the SM Room area
-Makes the storage zones of the AI chamber storage rather than AI
-Changes the zone with all the canisters to atmos rather than storage
-Changes secure storage to engineering area
-Changes the turbine to be the incinerator area rather than the HFR engine area
-Changes the mislabelled "tool storage" to primary storage
-Changes the mislabelled  "fore starboard maints" to tool storage
-Expands eva maints to include more than just two wall tiles
-Removes security records console from experimentation lab
-Wires the circuit lab APC
-Fixes 4 instances of broken or accidental disposal piping in sci hallway
-Engineering south maint entrance can no longer be …

Solitaire fixes

---

fulp_modules/features/spells/fulp_spellbook.dm
fulp_modules/features/spells/fulp_spells.dm
tgstation.dme

Exactly what it says on the tin. Brings back Summon Dance Floor from the deleted devil game mode. It may need to have a longer cooldown because of the smoke, but that hopefully won't be an issue. Here's a pic for people who weren't around before it was removed: 
Since we changed our policy for wizards, I thought it would be fun to give them more gimmick-y type spells that don't necessarily do anything other than maybe be annoying. 
:cl:
add: Adds Summon Dance Floor to the wizard spellbook
/:cl:

Brings back Summon Dance Floor

---

fulp_modules/features/species/beefmen/mob/beefman.dm

Beefmen can insert and take their  tongues out at will
FUN addition no advantages on a metalevel (NOT buffing my main race)
:cl:
expansion: Expands content of an existing feature
/:cl:

Beefman tongue INSERTION REMOVAL

---

_maps/map_files/SolitaireStation/Solitairestation.dmm

Fixes a bunch of runtimes and issues with Solitaire.
Such as:
- stacked pipes
- ACTIVE TURFS ROUNDSTART (WHAT TH EFUCK)
- ALL OF THESE AREAS HAD MISSING APC'S (and were even reported in the forum thread but never fixed)
- REMOVED THE STUPID FUCKING CS SOURCE DECALS OUTSIDE BAR
- ALL THESE FUCKING RUNTIMES
AND THERE ARE STILL 35 ROOMS WITHOUT AIR ALARMS BUT FUCK THAT IM NOT DOING IT ITS TOO TEDIOUS
fuck you
This map was rushed and the more attempts to rework it are made the more issues seem to come to light
This map still has issues unresolved in the forum thread
i'm on my breaking point just look at all the missing stuff from this map and all the weird design choices like lavaland-elite only skulls on AI sat

Fixes Solitaire runtimes + missing APCs

---

fulp_modules/features/bloodsuckers/code/powers/_powers.dm
fulp_modules/features/bloodsuckers/code/powers/brujah.dm
fulp_modules/features/bloodsuckers/code/powers/cloak.dm
fulp_modules/features/bloodsuckers/code/powers/distress.dm
fulp_modules/features/bloodsuckers/code/powers/feed.dm
fulp_modules/features/bloodsuckers/code/powers/fortitude.dm
fulp_modules/features/bloodsuckers/code/powers/gohome.dm
fulp_modules/features/bloodsuckers/code/powers/masquerade.dm
fulp_modules/features/bloodsuckers/code/powers/monstertrack.dm
fulp_modules/features/bloodsuckers/code/powers/recuperate.dm

I refuse to describe this PR.
I refuse to state why this is good for the game.
I refuse to modify aspects of the game.

Fixes feed (standardizes BS power code so it doesn't happen again in the future)

---

_maps/map_files/SeleneStation/SeleneStation.dmm
_maps/map_files/SolitaireStation/Solitairestation.dmm

Selene spawns stupid useless stuff in, Solitaire has Engineering deputy lockers instead of science/med
Fixes both those problems for deputy lockers 😎

[Solitaire/Selene] Fixes Deputy lockers

---

_maps/map_files/Heliostation/Heliostation.dmm

Did U Know Lia Is A cArp That Attacks Other Mobs? ? this Includes CArps .. If Lia Cannot  Readh The Carp The Will Start Breaking Windows 2 Get To Them . !

[Helio] Stops the HoS office from getting depressurized most rounds.

---

_maps/map_files/SolitaireStation/Solitairestation.dmm

Overhauls disposals completely, addresses feedback from forums/discord/things I noticed, and things from PR's that had either been overwritten or somehow missed as were not present in the master. Additionally tweaks some things like pipes/wires/wall objects, and any issues I noticed while doing the above.
- Completely re-did disposals from ground up - testing a subloop option for medbay that isolates the main loop incase of sabotage in medbay and engineering. Looks horrible on the map but should function more efficiently and prevent the entirety of disposals being rendered useless if one pipe at any point on station is broken.
- rewired and piped sci main entrance to link with rest of station post-update
- deleted duplicate maints access outside genetics/next to vault
- rewired circuits …

Solitaires' Solitaire Station disposals overhaul, fixes, and tweaks.

---

fulp_modules/mapping/ruins/space/beef_station.dmm

fixes the 3 roundstart AT in beefstation
fixes the 3 roundstart AT in beefstation
:cl:
fix: fixes the 3 roundstart AT in beefstation
/:cl:

fixes the 3 roundstart AT in beefstation

---

fulp_modules/features/antagonists/bloodsuckers/code/antagonists/bloodsucker_datum.dm
fulp_modules/features/antagonists/bloodsuckers/code/antagonists/vassal_datum.dm

makes bs powers logged like traitor/ling/heretic

logs bloodsucker power purchasing

---

_maps/map_files/SolitaireStation/Solitairestation.dmm

[Solitaire] Command/Virology/AI overhaul

---

fulp_modules/features/mentors/mentorpm.dm

Removes removed mentorpm feature from the code

---

fulp_modules/features/prison_kitchen/prison_bots.dm

The prisoner bot used to order an unobtainable spaghetti, which showed up as an error, now it orders plain boiled spaghetti.
https://www.youtube.com/watch?v=XfG0-iW5o0Y

Fixes prison bot ordering unexistant spaghetti

---

_maps/map_files/Heliostation/Heliostation.dmm

Why?
Unless this is somehow intentional which I highly doubt, or helio2 is coming tomorrow, I don't want another atmo tech fucking up distro.
:cl:
fix: fixes Heliostation using distro as exhaust for thermomachine
/:cl:

Fixes Heliostation using distro for thermomachine's exhaust

---

fulp_modules/features/antagonists/bloodsuckers/code/bloodsucker/bloodsucker_life.dm
fulp_modules/features/antagonists/bloodsuckers/code/bloodsucker/shaded_bloodsucker.dm
tgstation.dme

Suggestion from the forums - https://forum.fulp.gg/t/bloodsuckers-brujah-malkavian-frenzy-suggestions/4498
I find it a pretty cool idea

Malkavians get shaded instead of gibbed/dusted

---

_maps/map_files/SolitaireStation/Solitairestation.dmm

Merges both https://github.com/fulpstation/fulpstation/pull/512 and https://github.com/fulpstation/fulpstation/pull/518 into one PR, because both others got merge conflicts that I didn't want to deal with.
Playable map

both my solitaire PRs at once without conflicts

---

_maps/map_files/PubbyStation/PubbyStation.dmm

fixe s lighting glitch in pubystation ai sat

---

fulp_modules/features/antagonists/bloodsuckers/code/antagonists/bloodsucker_datum.dm
fulp_modules/features/antagonists/bloodsuckers/code/antagonists/vassal_datum.dm
fulp_modules/features/antagonists/bloodsuckers/code/bloodsucker/bloodsucker_coffin.dm
fulp_modules/features/antagonists/bloodsuckers/code/bloodsucker/bloodsucker_crypt.dm
fulp_modules/features/antagonists/bloodsuckers/code/bloodsucker/bloodsucker_daylight.dm
fulp_modules/features/antagonists/bloodsuckers/code/bloodsucker/bloodsucker_flaws.dm
fulp_modules/features/antagonists/bloodsuckers/code/bloodsucker/bloodsucker_life.dm
fulp_modules/features/antagonists/bloodsuckers/code/bloodsucker/bloodsucker_objects.dm

Grammar fixes for bloodsuckers
Grammar fixes
:cl:
spellcheck: fixes bloodsuckers grammar
/:cl:

Bloodsucker Grammar

---

fulp_modules/features/halloween/2019/costumes.dm
fulp_modules/features/halloween/2020/costumes.dm

Fixes minor mistakes in item names/ descriptions in some of the old Halloween costumes. By no means is this exhaustive of all the issues with these items, but it's something.
Mistakes are bad, fixing them is good.
:cl:
fix: minor, non-exhaustive fixes for Halloween costumes
/:cl:

minor fixes for old halloween costumes

---

_maps/map_files/SolitaireStation/Solitairestation.dmm

Fixes some problems with Solitaire's new arrivals, and cuts back on some maint look in arrival/brig maintenance, since I found it too much.

solitaire arrivals fixes + maint loot removal

---

code/___fulp_defines/bloodsucker_defines.dm
fulp_modules/features/antagonists/bloodsuckers/code/bloodsucker/bloodsucker_objects.dm
tgui/packages/tgui/interfaces/KindredArchives.js

Stakes don't runtime when hitting something that isn't a mob anymore.

Fixes stakes + Archives code improvement

---

_maps/map_files/PubbyStation/PubbyStation.dmm

This is just some of them, I am not going to post all of them. 
I don't know. 
:cl:
fulp doesn't have changelog, no?
/:cl:

Fixes pubby's yellow stripes decal corner being weird and stuff

---

fulp_modules/features/jobs/deputy/_deputy.dm

guess what came in the mail today
an empty pizza box
😦

Fixes deputies getting empty pizza in the mail today

---

fulp_modules/features/jobs/deputy/deputy_gear.dm

I don't even know what this fixes, but it fixes something.

fixes deputy beret objectives

---

fulp_modules/features/antagonists/traitor/uplink_items/race_restricted.dm

Changes living beefplushie cost to 2 tc instead of 3 and fixes some bad grammer i did.
2 tc cost makes more sense when looking at the rest of the items, like healing smokes and will incentivize it to get used more.
:cl:
balance: The living beefplushie now costs 2 tc instead of 3.
spellcheck: Fixes living beefplushie grammer.
/:cl:

Cheaper living beefplushie and grammer fixes

---

fulp_modules/features/species/beefmen/mob/beefman.dm
fulp_modules/features/species/beefmen/mob/beefman_limbs.dm

meatmen can no longer infinitely generate meat when sawing off their limbs
i found another unrelated  bug where beefmen can stand on 0 legs after they saw off their legs. 
HAPPENS at random IDK whats causing it
:cl:
/:cl:

FIXES meatman limb duplication glitch

---

_maps/map_files/SeleneStation/SeleneStation.dmm

Giving science the right order console is good.
:cl:
fix: fixes Selene Station science supply order console 
/:cl:

Fixes Selene Station science supply order console 

---

fulp_modules/features/antagonists/bloodsuckers/code/rulesets/monsterhunter_event.dm

Fixes monster hunters not spawning and also removes single letter variable, I don't know how it was missed but it was, and now it's gone.
bug fix.

Fixes MH's not spawning

---

fulp_modules/features/antagonists/bloodsuckers/code/powers/targeted/lunge.dm

do_after's extra checks are supposed to be callbacks. Mine wasn't, so it was runtiming when you lunge'd, and wouldn't actually wait the cooldown.

fixes lunge

---

fulp_modules/features/antagonists/bloodsuckers/code/rulesets/monsterhunter_event.dm

Traitors with a martial art that makes them immune to stamina damage is a REALLY not good idea.

monsterhunters now take all antags into account

---

_maps/map_files/Heliostation/Heliostation.dmm

**Adds fire alarm to helio sec hallway and windows to F/S maint**  
People without crowbars can now exit the area with fire alarm, instead of breaking the firedoor with brute force.
I add window there because you cannot see if anyone somehow gets spaced there, meaning no one can't find you. @Ebb-Real 
:cl:
add: Adds fire alarm to helio sec hallway and windows to F/S maint  
/:cl:

Adds fire alarm to helio sec hallway and windows to F/S maint  

---

_maps/map_files/PubbyStation/PubbyStation.dmm

Howdy there, the issues were the following:
- Curators weren't able to upload books without moving the library computer, because the book scanner was out of range of the library computer.
I moved the scanner and the book binder to the same area, so curators won't have to move the computer to upload books.
- I saw one space tile that was wrongfully labeled as nearstation, so I fixed that too.
- The sec equipment room was missing a distro pipe. Now fixed.
Curators can upload books and ordnance has the full equipment!
And I guess sec will get air in the equipment room if it's lacking...
:cl:
fix: Moved the library book binder and scanner to the same area as the library computer.
fix: The security equipment room's air pump is now connected to distro.
/:cl:

Fixes some Pubby issues.

---

_maps/map_files/Heliostation/Heliostation.dmm
code/___fulp_defines/fulp_defines.dm
fulp_modules/features/prison/prison_shuttle/prison_mail.dm
fulp_modules/features/prison/prison_shuttle/prison_shuttle_template.dm

Makes mail shuttles a little more lenient, checks for all existing mail rather than all the ones on the shuttle via keeping them on a list, and makes helio's perma arcades use directionals.
eh.

Small fix to Helio Permabrig + Fix to mail shuttles

---

_maps/map_files/Heliostation/Heliostation.dmm

Replaces gas masks with atmos gas masks
Fixes incinerator power to not rely on an incinerator to power it directly
Makes atmos pipes not connected to mix if you try to edit them in any way
Makes atmos pipes easier to add layer manifolds to without plasmaflooding yourself
how isn't it

[Heliostation] fixes problems with atmos

---

_maps/map_files/SeleneStation/SeleneStation.dmm

map bug fix lol
map bug fix lol

Fixes broken glitter grenade on Selene

---

fulp_modules/features/species/beefmen/mob/beefman_limbs.dm

fixes runtime i ngibbing beefmen
u can now kil them without making runtimes
:cl:
/:cl:

fixes runtime in gibbing beefmen

---

_maps/map_files/SeleneStation/SeleneStation.dmm

Lol
fixed it lmafo.. what idiot broke it in the first place
:cl:
expansion: Expands content of an existing feature
/:cl:

fixes mis-area'd on selene

---

_maps/map_files/SeleneStation/SeleneStation.dmm

**Adds DNA disk box to selene genetics lab**
hey where's my admin role
I mean... uh... gene needs the disk I guess?
:cl:
fix: gives selene genetics lab the missing disk box, I guess.
/:cl:

Adds DNA disk box to selene genetics lab

---

fulp_modules/features/antagonists/bloodsuckers/code/powers/monstertrack.dm

fixes monsterhunter tracker

---

fulp_modules/features/halloween/2021/costumes.dm

Adds a worn icon so the tournament medal actually appears in-game when worn.
bug fix.

Fixes tournament medal

---

fulp_modules/features/clothing/body_cameras/body_camera.dm

little helpful thing for security 😃

body cameras fit on security wintercoats

---

fulp_modules/features/prison/prison_kitchen/prison_bots/rat_bot.dm

/tg/ changed the path of the cheese wedge, so the bot now orders this:
Now it orders a cheese wedge, which is obtainable.
:cl:
fix: Fixed prison rat bot ordering unobtainable food.
/:cl:

Fixes prison kitchen bot ordering unobtainable food

---

_maps/map_files/Heliostation/Heliostation.dmm

Some asshole removed the plating but kept the decals on the tile...
Because.......
:cl:
fix: fixed missing plating on Helio's ordnance.
/:cl:

Fixes missing tile on Helio's ordnance.

---

_maps/map_files/SeleneStation/SeleneStation.dmm

What copypasting map parts does to a mf...
:fearful: 
:cl:
del: Removed the chunk of Helio in Selene's space.
/:cl:

Fixes Selene map error

---

_maps/map_files/Heliostation/Heliostation.dmm
_maps/map_files/SeleneStation/SeleneStation.dmm

There was no metal or glass for sci besides in robo on selene, there were no roundstart circuits on helio. There was missing access to crew monitors for people that weren't CMO when the crew monitor tablet thing gets grabbed.
less missing stuff good.
:cl:
add: added missing metal + glass on sele.
add: added missing integrated circuits on helio.
add: added missing crew monitor computer to med on helio.
/:cl:

Missing stuff in sci and med

---

fulp_modules/features/antagonists/bloodsuckers/code/powers/feed.dm

Feed should now hopefully cause you to break the Masquerade again.
It sucks.

Hopefully fixes feed not breaking masquerade

---

_maps/map_files/Heliostation/Heliostation.dmm
_maps/map_files/SeleneStation/SeleneStation.dmm

Yeah apparently using the box labour camp template fucked up the docking point at the gulag itself. So I changed it to be the generic template, and that seems to work.
No more broken shit hopefully. 🥺 
:cl:
fix: fixed Helio and Selene's labour camp shuttles for real this time.
/:cl:

Fixes Helio and Selene's labour camp shuttles FOR REAL.

---

fulp_modules/features/antagonists/bloodsuckers/code/antagonists/monsterhunter_datum.dm
fulp_modules/features/antagonists/bloodsuckers/code/bloodsucker/bloodsucker_objectives.dm

fixes mnoster hunter grentexting

---

fulp_modules/features/antagonists/traitor/uplink_items/race_restricted.dm

it used the wrong typepath :/
it actually works
:cl:
fix: Living beefplushie actually appears in the uplink now.
/:cl:

Makes traitor beefplushie actually work because i was a dumbass all along

---

_maps/map_files/PubbyStation/PubbyStation.dmm

AYO YOU KNOW WHAT IM TRYNA SAY I ADDED A SHUTTER CAUSE SOME FAILURE FORGOT TO ADD IT (SMOKEY) AY WHAT CAN I SAY GIMME CONTRIBUTOR STATOS PLEASE Im like gonna be the next PRODIGE KNOW WHAT IM SAYIN' AYE?
cause I FUCKIN made it duh???
HELLO?
:cl:
expansion: Expands content of an existing feature
server: something …

I added a SHUTTER in PHARMACY in PUBBY station.

---

fulp_modules/features/antagonists/infiltrators/infil_objectives.dm
fulp_modules/features/antagonists/infiltrators/infil_ruleset.dm
fulp_modules/features/antagonists/infiltrators/infiltrator.dm

mor optimized way to find traitor targets
:cl:
expansion: Expands content of an existing feature
/:cl:

infils fixes buncha shit

---

fulp_modules/features/antagonists/infiltrators/infil_ruleset.dm
tgui/packages/tgui/interfaces/PreferencesMenu/antagonists/antagonists/ghostinfiltrator.ts

fix infiltrator preview icon on antag enabling panel

---

fulp_modules/features/antagonists/bloodsuckers/code/antagonists/bloodsucker_datum.dm
fulp_modules/tg_edits.md
tgui/packages/fulpui-patches/index.js
tgui/packages/fulpui-patches/interfaces/AntagInfoBloodsucker.tsx
tgui/packages/fulpui-patches/package.json
tgui/packages/tgui/routes.js
tgui/yarn.lock

Adds a Bloodsucker TGUI interface by extending tgui with a new "fulpui" package.
Improved UX for the bloodsucker introduction window. Lays the groundwork for future fulpstation interfaces.
Existing Bloodsucker tips interface:
New Bloodsucker tgui interface:
:cl:
add: Bloodsucker antag tgui interface
/:cl:

blood-sucker-tgui - Adds a new tgui interface for the bloodsucker antag

---

fulp_modules/Z_edits/job_edits.dm

Changes the detective's job slots so there's now only one roundstart, with an additional 1 latejoin slot.
The detective fulfills a specialized role of investigating and solving crime using their brain and their scanner. They lack content, as most of the time this results in being called to one place and walking over to scan it and checking the results. When there's multiple detectives the small amount of work the detective has is now split between 5 people rushing to see who can do it first. This causes what could be a substantial amount of content for a detective in a round divided between 5 people leaving little for all. 
Decreasing the total job slots allows for a better detective experience where it's not a competition as to who will actually have things to do in the round. Two …

Changes the detective's jobslots to 1 roundstart and 2 total

---

fulp_modules/Z_edits/job_edits.dm

Someone messed up so we had 0 roundstart prisoners and two slots for latejoins to pick it, all the jobs had their spawn positions and total positions swapped minus cyborg idk how this wasnt noticed until now
lol
lmfao

Fixes our jobs lol

---

fulp_modules/features/antagonists/bloodsuckers/code/rulesets/monsterhunter_event.dm
fulp_modules/features/antagonists/infiltrators/infil_items.dm
fulp_modules/features/antagonists/infiltrators/infil_objectives.dm

i accidentally deleted all my branches when i was tryna do somth so it closed al my open prs

fixes monstr huntr icon and corporate climber objectives

---

fulp_modules/tg_edits.md
tgui/packages/fulpui-patches/interfaces/KindredArchives.js
tgui/packages/fulpui-patches/interfaces/RequestManagerFulp.js

Moves 2 fulp TGUIs to fulp TGUI folder

---

_maps/map_files/SeleneStation/SeleneStation.dmm

@SmoSmoSmoSmok 🖕 🖕 🖕 🖕 🖕 🖕 🖕 🖕 🖕 🖕 🖕 🖕 🖕 🖕 🖕 🖕 🖕 🖕 🖕 🖕 🖕 🖕 🖕 🖕 🖕 🖕 🖕 🖕 🖕 🖕 
It isn't because it'll make Helian reenable selene

Lets cargo use their supply shuttle on selene

---

fulp_modules/Z_edits/felinid_edit.dm

The dummy mob used for screenshot tests is undefeatable we should just bow to them and stop trying to give them traumas as we have no way of winning against it with the way its assigned its race

Saves our parallel map testing tests?

---

_maps/map_files/Heliostation/Heliostation.dmm
_maps/map_files/SeleneStation/SeleneStation.dmm

Someone didn't know how to spell that word and fucked it up on all our maps
Makes our maps look good?
:cl:
fix: fulpstation is saved
/:cl:

Fixes some misspellings in our codebase

---

_maps/map_files/Heliostation/Heliostation.dmm

Describe The Pull Request. Please be sure every change is documented or this can delay review and even discourage maintainers from merging your PR!
Argue for the merits of your changes and how they benefit the game, especially if they are controversial and/or far reaching. If you can't actually explain WHY what you are doing will improve the game, then it probably isn't good for the game in the first place. 
:cl:
balance: New helio med
/:cl:

Helio Medical Revamp

---

_maps/map_files/Heliostation/Heliostation.dmm

adds sunglasses to helio office

---

fulp_modules/features/species/beefmen/mob/beefman.dm

beefmen wil now BLEED OUT and die
:cl:
/:cl:

fixes beefmen not bleeding 

---

fulp_modules/features/spells/fulp_spellbook.dm

Makes summon dance floor not appear as an offensive spell

---

_maps/heliostation.json
_maps/selenestation.json
config/maps.txt

Fixes a spelling error in the map jsons for helio and selene
Our job changes in the mapping jsons actually work now.
:cl:
fix: map json job changes for heliostation and selenestation now work properly
/:cl:

Fixes our map json's job changes

---

code/game/objects/items/devices/scanners/health_analyzer.dm
code/modules/antagonists/traitor/objectives/eyesnatching.dm
code/modules/mob/living/carbon/human/examine.dm
fulp_modules/Z_edits/felinid_edit.dm
fulp_modules/features/antagonists/bloodsuckers/code/antagonists/bloodsucker_datum.dm
fulp_modules/features/antagonists/bloodsuckers/code/bloodsucker/bloodsucker_crypt.dm
fulp_modules/features/antagonists/bloodsuckers/code/bloodsucker/bloodsucker_integration.dm
fulp_modules/features/antagonists/bloodsuckers/code/bloodsucker/bloodsucker_life.dm
fulp_modules/features/antagonists/bloodsuckers/code/bloodsucker/bloodsucker_objects.dm
fulp_modules/features/antagonists/bloodsuckers/code/powers/_powers.dm
fulp_modules/features/antagonists/bloodsuckers/code/powers/brujah.dm
fulp_modules/features/antagonists/bloodsuckers/code/powers/feed.dm
fulp_modules/features/antagonists/bloodsuckers/code/powers/masquerade.dm
fulp_modules/features/antagonists/bloodsuckers/code/powers/tremere/thaumaturgy.dm
fulp_modules/features/species/species_integration.dm
fulp_modules/tg_edits.md

Reverts fulpstation/fulpstation#655
Saves the fulpstation codebase

Revert "Bloodsuckers can drink any blood (TG edit removal)" 

---

_maps/map_files/Heliostation/Heliostation.dmm
_maps/map_files/SeleneStation/SeleneStation.dmm

Updates our stations with directional shutters

---

_maps/map_files/Heliostation/Heliostation.dmm

I really love having separate rooms for surgeries. The smartfridge is in the center of the room so it can be used by either side. Each room has shutters that can can be closed for privacy. I moved the wall into the security room a bit so I had to slightly redesign it and remove the chairs, but other than that everything is mostly unchanged. Playtested it and everything seemed to work fine, but this is my first map PR so I'm sure there's probably something I missed.

Separates Heliostation's  Aft Surgery into two separate rooms.

---

fulp_modules/mapping/ruins/space/beef_station.dmm

I forgot to update beefstation last time I updated tgu & ausbushes flowers pathing got redone so they wouldnt load anymore.

Updates beefstation

---

_maps/map_files/SeleneStation/SeleneStation.dmm

selene atmos 2

---

fulp_modules/fulp_world/fulp_world.dm

Every server should have this
:cl:
add: Round time now shows in the hub entry
/:cl:

Added Round Time to Hub Entry

---

fulp_modules/features/antagonists/bloodsuckers/code/bloodsucker/bloodsucker_integration.dm

Fixes bloodsuckers getting affected by fluctuating blood levels

---

tgui/packages/tgui/interfaces/PreferencesMenu/antagonists/antagonists/monsterhunter.ts

This improves the antagonist role of the Monster Hunter.

Fixes the Monster Hunter antagonist

---

code/datums/storage/subtypes/extract_inventory.dm

This is pissing me off & I am not ever gonna use chat tabs i dont want to wait for next tgu to not be spammed

Ports the Admin Log spam fix

---

_maps/map_files/SeleneStation/SeleneStation.dmm

Saves Selene's brig

---

fulp_modules/features/antagonists/infiltrators/infil_objectives.dm
fulp_modules/features/antagonists/infiltrators/infiltrator.dm

gibbed pets now theoretically hypothetically count towards the objective
:cl:
/:cl:

fixes PET killing objective

---

_maps/map_files/Heliostation/Heliostation.dmm

What is says on the tin. I think I reset back to the wrong commit when fixing the merge conflicts in the helio PR.

Adds the missing APCs and Air alarms to helio and changes lobby to engi proper

---

fulp_modules/features/antagonists/infiltrators/infil_objectives.dm

u dont need 2 escape to suceed this objective anymor
:cl:
/:cl:

makeks the adanvcaed mulligan objective compatible with the radio

---

_maps/map_files/SeleneStation/SeleneStation.dmm

2 doors went insane
:cl:
/:cl:

fixes everything in the universe in selene station

---

fulp_modules/features/antagonists/bloodsuckers/code/antagonists/vassal_datum.dm

vassals can now see only their own bloodsucker master and only vassals that are on their team. BLOODSUCKERS can now only see their own vassals
:cl:
/:cl:

fixes vassals not seeing any huds and fixes bloodsucker huds

---

_maps/map_files/Heliostation/Heliostation.dmm

- Reworks Supply Department.
- Adds Maintenace Below Cargo Connecting With Xenobiology Maintenace.
- Moves Vault from Evac to Cargo Hallway.
- Why do you move the vault near cargo?
Because that belongs to cargo, duh.
- Why is the originally evac vault place left as space?
Because currently evac shuttle are not proper aligned with evac room placement (security outpost,) and I plan on reworking evac or evac shuttle soon, or maybe in this PR, dunno.
- Why the skybridge?
Because I don't want vault exposed to space and ALSO SKYBRIDGE IS AWESOME.
- WTF is that shipment
Donk supply shuttle did a swag drift but the shipment flew off and hit the station.
:cl:
add: Me
/:cl:

Heliostation Department Rework - Cargo

---

fulp_modules/features/antagonists/infiltrators/infil_objectives.dm
fulp_modules/features/antagonists/infiltrators/infil_ruleset.dm

someone ,who i wont name, planted a runtime in infil code
:cl:
/:cl:

fixes runtime in infils

---

_maps/map_files/SeleneStation/SeleneStation.dmm

some dumbasshole disconnected them
:cl:
/:cl:

reconnects turbine to smes on selenstation

---

_maps/map_files/Heliostation/Heliostation.dmm

Yeah it wasn't connected roundstart, meaning that if cargo got depressurized it wouldn't get air from distro

Connects Helio Cargo to the pipenet

---

fulp_modules/features/antagonists/infiltrators/infil_items.dm

When you got DEADLY WEAPONS and UNAUTHORIZED CONTRABAND its good for us to know where it originated from i think
All in uplink.log

Logs infil radio gifts

---

fulp_modules/features/events/bruhspace_anomaly.dm

I love the old bruhspace anomaly event which is why I want the warning to make more sense. The bruh moment itself is not issued, the warning for it is. Thanks for coming to my ted talk.
My immersion.
:cl:
fix: bruhspace event grammar
/:cl:

Fixes bruhspace grammar

---

_maps/map_files/Heliostation/Heliostation.dmm

Fixes Raystation

---

_maps/map_files/SeleneStation/SeleneStation.dmm

Updates SeleneStation with the new stuff (bz fab. chamber)

---

fulp_modules/features/antagonists/bloodsuckers/code/rulesets/bloodsucker_rulesets.dm

it never executed coz it runtimed
:cl:
/:cl:

fixes midround bloodsuckers

---

fulp_modules/features/antagonists/infiltrators/infiltrator.dm

Pepsilawn coded this with his phone
:cl:
/:cl:

Fixes admin selected factions

---

fulp_modules/features/antagonists/bloodsuckers/code/antagonists/vassal_datum.dm
fulp_modules/features/antagonists/bloodsuckers/code/bloodsucker/clans/_clan.dm
fulp_modules/features/antagonists/bloodsuckers/code/powers/tremere/dominate.dm

prevents temporary vassals from being favoritized 

---

fulp_modules/features/antagonists/bloodsuckers/code/bloodsucker/bloodsucker_life.dm
fulp_modules/features/antagonists/bloodsuckers/code/monster_hunter/hunterfu.dm

this runtime would hapen whenever u staked a clanless VAMPIORE
:cl:
/:cl:

fixes runtime when staking bloodsuckers

---

fulp_modules/features/antagonists/bloodsuckers/code/antagonists/vassal_datum.dm

shitmins can give vassal status to players after selecting which vampire this vassal shuld belong to
:cl:
/:cl:

allows admins to vassalize ppl

---

_maps/map_files/SeleneStation/SeleneStation.dmm

BZ scrubber wasn't connected to anything and the pressure tank didn't have any oxygen in it and nobody told me anything about it in the like 2 weeks its been on the server

Unfucks selene ordnance

---

fulp_modules/features/antagonists/infiltrators/infil_items.dm

a ghost would alwys be chosen to spawn as a gorila regardless wether the player being transformed is afk or not. thsi fsixesd it p ok 
:cl:
/:cl:

fixes ghost selection for gorilla spawning

---

fulp_modules/features/antagonists/bloodsuckers/code/bloodsucker/shaded_bloodsucker.dm

this runtime would happen if no ghost was selected to be a shade
:cl:
/:cl:

fixes runtime for SHADED bloodsuckers

---

fulp_modules/features/mentors/mentor_clientprocs.dm

Ray kept crying to me he appeared as mentor instead of contributor in msay which was because contributors.txt only handled ckeys in canonical form & he was written as OneTortoise instead of onetortoise, this just calls the base dm proc ckey() on whatever raw text the file might contain

Makes Ray a contributor

---

fulp_modules/features/antagonists/bloodsuckers/code/powers/_powers.dm
fulp_modules/features/antagonists/bloodsuckers/code/powers/fortitude.dm
fulp_modules/features/antagonists/bloodsuckers/code/powers/monstertrack.dm

all his abilotos rintume
:cl:
/:cl:

fixes the monsterhunter antagonist

---

fulp_modules/features/mentors/mentor_clientprocs.dm

Promotes Ray to contributor (FR) 

---

_maps/map_files/PubbyStation/PubbyStation.dmm

Removes lightbulb on Pubbystation

---

fulp_modules/features/antagonists/infiltrators/infil_items.dm

WHEN u claim ur final objective, all ur current objectives will be removed b4 gaining it
:cl:
/:cl:

fixes infils not greentexting cause of dagd

---

fulp_modules/features/antagonists/bloodsuckers/code/bloodsucker/shaded_bloodsucker.dm

fixes bloodsucker shards capturing non existing ghosts

---

fulp_modules/features/antagonists/infiltrators/infil_items.dm
tgui/packages/fulpui-patches/interfaces/InfilRadio.js

dehardcodes the INFILRADIO UI

---

fulp_modules/Z_edits/heart.dm
tgstation.dme

What is says on the tin
Doesnt feel right to keep around when players wouldn't be aware of it

Removes an undocument balance change

---

code/_onclick/hud/rendering/plane_master.dm

Port this https://github.com/tgstation/tgstation/pull/69778 so we can TM until next TGU.
Thanks, Potato. 
Hi
:cl:
/:cl:

Port Potato's Fix of Rendering Issue

---

fulp_modules/features/antagonists/infiltrators/infil_items.dm
fulp_modules/features/antagonists/infiltrators/infil_objectives.dm

rewrites it so no other antags get it and u dont need to keep the card in ur bag to greentext
:cl:
/:cl:

rewrites emag objective

---

_maps/heliostation.json
_maps/shuttles/emergency_helio.dmm
fulp_modules/mapping/shuttles/map_templates.dm

It still looks like this, but hopefully, it loads the brig this time. 
:cl:
add: Added new evac shuttle for Helio station
/:cl:

Helio evac second attempt

---

fulp_modules/mapping/ruins/space/beef_station.dmm

Fixes bad paths for the bucket and pAI that were causing holes in beef station.
Requires players to space beef station themselves.
:cl:
fix: holes in beef station
/:cl:

Fixes hole in beef station

---

fulp_modules/features/antagonists/infiltrators/infil_items.dm

the rift can only spawn 1 robot and their laser gun damage is halved
:cl:
/:cl:

nerfs infil secborgs

---

_maps/map_files/Heliostation/Heliostation.dmm
_maps/map_files/SeleneStation/SeleneStation.dmm

Places missing round start action figures on Helio and Selene
Fun C:
:cl:
fix: md and chaplain have action figures now on Helio
fix: added several missing action figures to selene station
fix: Selene chemist action figure now in pharmacy
add: deathsquad, wizard, and ninja action figures hidden throughout Selene maintenance
/:cl:

Action Figures

---

fulp_modules/features/antagonists/infiltrators/infil_items.dm
fulp_modules/features/antagonists/infiltrators/infiltrator.dm

admin logging infil objectives

---

fulp_modules/features/antagonists/infiltrators/infiltrator.dm

seems this was confusing sum ppl so now u no longer need to refresh ur UI to see the new objectives

infil antag ui gets updated automatically with new objectives without having to refresh

---

fulp_modules/features/antagonists/bloodsuckers/code/bloodsucker/bloodsucker_objectives.dm

Apparently QM becoming a head happened like 6 months ago in June which is like half a year ago so this line isn't very true anymore

Promotes the QM to command

---

fulp_modules/features/antagonists/bloodsuckers/code/powers/tremere/auspex.dm

https://github.com/fulpstation/fulpstation/pull/861 was meant to help make https://github.com/fulpstation/fulpstation/pull/860 easier but they both got merged at the same time, this standardizes auspex with the rest of the powers.
I also removed a reference to proc holders while I was here because they no longer exist.
Doesn't affect the game, so I can't really explain why.
No gameplay changes.

Makes auspex use the new power support

---

fulp_modules/mapping/ruins/space/beef_station.dmm

Fixes the walls to be reinforced (instead of titanium) on beef station. Now without fucking up fernando's changes, hopefully
Beef station isn't a shuttle, so it shouldn't have shuttle walls. 
:cl:
fix: beef station walls
/:cl:

fix beef station walls

---

_maps/heliostation.json
_maps/map_files/Heliostation/Heliostation.dmm

Adds Coffee to Heliostation
Adds Coffee to Heliostation
:cl:
add: Adds Coffee to Heliostation
/:cl:

Adds Coffee to Heliostation

---

_maps/map_files/Heliostation/Heliostation.dmm
config/maps.txt

Removes the useless bin from warden office. Closes #894
Doin your mom do do doin your mom
:cl:
/:cl:

Undisposals the warden's office

---

_maps/map_files/SeleneStation/SeleneStation.dmm

Closes #891 
Doing your mom do do doing your mom
:cl:
/:cl:

Makes our grass not ass

---

fulp_modules/mapping/ruins/icemoon/beef_cytology.dmm

Makes the plasma river the correct subtype, adds a DNA infuser, and makes the rec room look less sterile
Makes the spawner more interesting (provided you can recruit a second person to join). Bug fixes are good and stuff.
:cl:
add: gave beefstation a DNA infuser, gave the kitchen and rec room an update, added an oven to the kitchen
fix: fixes the subtype of plasma lava, moldy food is now the bacteria subtype
/:cl:

Updates beef cytology

---

fulp_modules/features/antagonists/bloodsuckers/code/structures/bloodsucker_coffin.dm

makes ventrue better
makes ventrue better and not poop
negrundayo smokey sends his regards
John Willard stamp approved 
🆑
rank 2 is too weak so yea rank 3 now u can break cuffs with brawn atleast
/:cl:

ventrue buff

---

fulp_modules/features/antagonists/monster_hunter/monsterhunter_abilities.dm
fulp_modules/features/antagonists/monster_hunter/monsterhunter_weapons.dm
fulp_modules/features/antagonists/rulesets/monsterhunter_event.dm

changes in the mh ruleset

---

_maps/map_files/Heliostation/Heliostation.dmm

- Changes solar access
- Fixes Distro Naming
- Fixes AI sat access
- Closes #926 #925 #897 #866
- Changes captain display case access

Heliostation Fixes

---

fulp_modules/features/antagonists/monster_hunter/killer_rabbit.dm
fulp_modules/features/antagonists/rulesets/monsterhunter_event.dm

also removes time constraint from the ruleset i didnt mean to leave that in
:cl:
/:cl:

fixes rabbits being non-hostile

---

code/__DEFINES/role_preferences.dm
fulp_modules/_defines/bloodsuckers.dm
fulp_modules/fulp_world/fulp_world.dm
fulp_modules/tg_edits.md

Removes another TG edit
Removing TG edits means TGU's are easier.

Removes the role preferences tg edit

---

fulp_modules/features/species/beefmen/russian.dm

Makes beefmen tongue use TG's system for adding new languages instead of completely overwriting it.
Less likely to break in the future.
Also makes it not register for speech to modify language, because it doesn't.

Changes the beef tongue

---

fulp_modules/features/antagonists/bloodsuckers/code/powers/feed.dm
fulp_modules/features/antagonists/bloodsuckers/code/structures/bloodsucker_crypt.dm

Removes overlapping balloon alerts when feeding/vassalizing people.

Removes some overlapping balloon alerts

---

fulp_modules/Z_edits/felinid_edit.dm

maybe fixes check idk 
Closes https://github.com/fulpstation/fulpstation/issues/968

Fixes checks maybe

---

_maps/map_files/PubbyStation/PubbyStation.dmm

Engineering officer can enter engineering.
Adds the missing AI board.
Adds air alarm in turbine.
Not tested.
It's not because it is pubby
:cl:
del: pubby, I wished.
/:cl:

Pubby Bug Fixes

---

_maps/map_files/Heliostation/Heliostation.dmm

**Finish the rest of engineering maintenance which I did not finish in my past rework, as well as restoring cargo disposal pipe sanity.**
I am extremely **dissatisfied** with the current look of service, but reworking service is currently out of my plan.
:cl:
add: Heliostation Engineering Maintenance Revamp; Cargo Disposal Pipe Sanity
/:cl:

Heliostation Patch 4 - Engineering Maintenance Revamp; Cargo Disposal Pipe Sanity

---

README.md

Fix guides links

---

fulp_modules/features/antagonists/monster_hunter/monsterhunter_datum.dm

instead of the objectives telling you who the monster target is, you will now have to identify them yourself. Hunters now have a monster vision ability. Monster players will appear with a rabbit outline on ur screen when this ability is active
Another option is to hunt down white rabbits, which will give you hints on who your target may be, their abilities, and what sort of monster they are.

reworks how monsters are hunted

---

fulp_modules/features/antagonists/bloodsuckers/code/bloodsucker/bloodsucker_life.dm
fulp_modules/features/antagonists/bloodsuckers/code/powers/masquerade.dm
fulp_modules/features/antagonists/rulesets/bloodsucker_rulesets.dm

Fixes some found Bloodsucker runtimes.
Not sure how much this fixes but it fixes the runtimes idk

Fixes some BS runtimes

---

fulp_modules/features/species/beefmen/beefman_clothing.dm

A few descriptions were outdated and a few armor values were wrong.
Beefman buff...?
fix: Beefman sashes now have the correct armor values when compared with the same job's jumpsuits.
/:cl:

Fixes for beefman sashes

---

fulp_modules/features/clothing/body_cameras/body_camera.dm

Changes the feedback for body cameras, removing text I thought was unnecessary (due to sounds making it obvious that an action worked), and adding/rewording balloon alerts to fit other instances of it.
awesome body cameras & better feedback

Bodycamera better feedback

---

_maps/map_files/SeleneStation/SeleneStation.dmm

incredible
AI is no longer on a death timer
:cl:
fix: SeleneStation's AI Satellite is now connected to power grid.
/:cl:

Connects the AI Satellite on SeleneStation to the grid

---

fulp_modules/features/mentors/mentor.dm

I accidentally made contributor list check mentor.txt instead of contributor.txt sorry bros

Fixes contributor list

---

fulp_modules/features/antagonists/bloodsuckers/code/clans/_clan.dm
fulp_modules/features/antagonists/bloodsuckers/code/clans/clan_vassal.dm
fulp_modules/features/antagonists/bloodsuckers/code/structures/bloodsucker_objects.dm

Fixes archives of the kindred showing the non-clan vassal-only clan that was added to prevent vassals from making favorites n such.

Fixes archives of the kindred

---

_maps/map_files/Heliostation/Heliostation.dmm

Rework EVAC area, including security outpost and customs, especially customs because I made it ugly as fuck years ago
Fixes SMES / Science Transit Tube lacking APC.
@SgtHunk  Finish by end of week else you are fired.

Heliostation Patch 5 - Evacuation

---

_maps/map_files/PubbyStation/PubbyStation.dmm

Fixes the execution room being called security

Adds Pubby 2

---

fulp_modules/features/antagonists/bloodsuckers/code/clans/clan_malkavian.dm

i checked the codebase for incorrect uses of invoke async and this was the only one we got, this fixes it.
malkavians now whisper their revelations as they should.

Fixes malkavians whispering their revelations

---

_maps/map_files/PubbyStation/PubbyStation.dmm

Pubby Prison lacked a lot of stuff other fulp maps had
Also removes the bz canister in science that shouldnt be there
Science nerf is always good

Nerfs pubby science and changes the prision a bit

---

fulp_modules/features/nanites/code/programs/healing.dm

It doesn't use nanites if it isn't adjusting temperature.

Fixes description for temperature adjustment

---

fulp_modules/features/nanites/code/machines/nanite_chamber.dm

Nanite chambers won't allow you to put literally anything in the game besides a nanite chamber into the chamber.
fix

Nanite chambers can only put people in it

---

_maps/map_files/SeleneStation/SeleneStation.dmm

Jumping into security office disposals would send you into HoS' office
Jumping into HoS' office's disposal would loop you back to HoS' office.
:cl:
fix: Selene has working disposal units in brig
/:cl:

Selene security office disposals fix

---

_maps/map_files/PubbyStation/PubbyStation.dmm

now with 11% less issues
:cl:
add: Adds a court room to pubby
/:cl:

Adds a Pubby Courtroom

---

_maps/map_files/PubbyStation/PubbyStation.dmm

fixes some stuff and adds some stuff
stuff is good, everything is in the changelog
:cl:
add: cell charger to engineering 
add: foundry in pubby: 
Before - 
Now - 
balance: AI sat disabler turrets will actually do something 
Before - 
Now - 
/:cl:

Pubby additions and fixes

---

code/modules/deathmatch/deathmatch_loadouts.dm

see https://github.com/tgstation/tgstation/pull/82024 i simply want this change faster

Dmloadout equipfix

---

_maps/map_files/Heliostation/Heliostation.dmm

Fixes missing disposal pipe in evac and near disposal
Also adds a beef plushie in coldroom so i can claim i reworked helios service
Disposal works and no longer has pipes under the walls
also i dont get demoted
:cl:
fix: Fixes helios disposal and unwalls the pipe
/:cl:

Minor Helios disposal Fix

---

fulp_modules/Z_edits/felinid_edit.dm

gives nobraindamage felinids a name
Lets admins identify better

gives nobraindamage felinids a name

---

fulp_modules/_signals/misc.dm

Removes unused stuff. If theirs anything else unused please tell me.
helps maintainability

removes unused signals

---

fulp_modules/_defines/fulp_defines.dm
fulp_modules/features/prison/prison_vendor.dm
fulp_modules/features/prison/prisoner.dm

deletes ACCOUNT_PRISON so prisoners can have money.
Lets prisoners have money.

Fr Fixes Prisoner accounts

---

_maps/map_files/PubbyStation/PubbyStation.dmm

Fixes this
bug fix
:cl:
fix: fixed pubby cryo tubes being under tiles
/:cl:

Pubby cryo tubes fix

---

_maps/map_files/SeleneStation/SeleneStation.dmm
_maps/shuttles/arrival_selene.dmm

fixes some problems with selene.
fixes:
fixes:
https://discord.com/channels/279359975250198528/587000604547874826/1222350787724836926
fixes:
https://discord.com/channels/279359975250198528/587000604547874826/1222347447737782352
fixes:
fixes:
https://discord.com/channels/279359975250198528/587000604547874826/1219522036943163412
fixes:
https://discord.com/channels/279359975250198528/587000604547874826/1222368613667835926

Selene maintance

---

_maps/map_files/Heliostation/Heliostation.dmm

Kills john willard
Fixes one of the smes not having cables under them
Moves the recharger in warden officer 1 tile up because it was under a light fixture, which made it really hard to click
Bug fix and qol

Minor helio fix and qol

---

fulp_modules/features/species/protogen/protogen.dm
fulp_modules/tg_edits.md
tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/fulp_species_features.tsx

tgu removed the .tsx by accident
we cant have this cool awesome species without being able to choose your cool awesome features is all im sayin
:cl:
fix: fixed protogen prefs
/:cl:

Fixes protogen features

---

_maps/map_files/TheiaStation/TheiaStation.dmm

Minor aestetic changes to Theia. Adds sensors to the atmos chambers that are currently missing them.
Makes Theia prettier, hopefully
:cl:
add: Minor changes to Theia
/:cl:

Minor updates to Theia station

---

fulp_modules/features/species/protogen/protogen.dm

Updates the protogen descriptions for readability. If they're going to stick around, their lore should be cleaned up a bit.
it probably isn't
:cl:
spellcheck: Updates description for protogens
/:cl:

updates protogen descriptions

---

fulp_modules/features/antagonists/monster_hunter/hunting_contract.dm
fulp_modules/features/antagonists/monster_hunter/monsterhunter_abilities.dm
fulp_modules/features/antagonists/monster_hunter/monsterhunter_datum.dm
fulp_modules/features/antagonists/monster_hunter/monsterhunter_weapons.dm
fulp_modules/features/antagonists/monster_hunter/rabbit_powers.dm
fulp_modules/features/antagonists/monster_hunter/wonderland.dm
fulp_modules/features/antagonists/monster_hunter/wonderland_apocalypse.dm

This PR alters player-facing monster hunter text for grammar and clarity.
There are a number of minor errors in monster hunter's textual content. This PR tries to fix most of those errors and attempts to better convey monster hunter mechanics through the antagonist's text.
:cl:
spellcheck: fixes some grammatical errors present in monster hunter text and makes a few changes for clarity
/:cl:

Monster hunter grammatical edits

---

fulp_modules/features/nanites/code/nanite_component.dm

This PR fixes the bug where nanites break ID access
bug bad, access good
:cl:
fix: Nanites will no longer break your ID access
/:cl:

Fixes nanites breaking IDs

---

fulp_modules/features/nanites/code/programs/healing.dm

The Bio-Regeneration nanite program will now heal organic bodyparts rather than robotic ones.
Unintended slip-up from #1197.
:cl:
fix: bio-regeneration nanites now heals organic bodyparts rather than mechanical ones
/:cl:

Bio-Regeneration now heals organic bodyparts

---

fulp_modules/features/antagonists/bloodsuckers/code/structures/bloodsucker_crypt.dm
fulp_modules/features/antagonists/bloodsuckers/code/structures/bloodsucker_recipes.dm

Current master doesn't compile, due to conflicts between PRs that were merged simultaneously (#1230 and #1232 ). This fixes the issues causing compile-time errors.
Nothing player-facing

Makes our master compile again.

---

_maps/map_files/TheiaStation/TheiaStation.dmm

I accidentally left a few tile decals on closed wall turfs in #1249, so this PR fixes that and improves a few other minor map details.
_Aesthetic_
:cl:
fix: fixed a few recent Theia Station mapping errors
/:cl:

Additional Theia fixes following recent improvements

---

_maps/shuttles/cargo_fulp.dmm

This PR edits Theia's cargo shuttle a bit for general aesthetic purposes and fixes one particularly annoying nonfunctional conveyor belt.
<details><summary>Expand for image of edited cargo shuttle shown in StrongDMM</summary>
</details>
- Slightly better cargo shuttle appearance.
- One less incredibly annoying broken conveyor belt.
:cl:
add: edited Theia Station's cargo shuttle a bit
fix: fixed a broken conveyor belt on Theia Station's cargo shuttle
/:cl:

Theia cargo shuttle edits/fix

---

_maps/shuttles/emergency_theia.dmm

This PR makes a few minor improvements/fixes to Theia Station's escape shuttle. See the mapbot check associated with this PR for more information.
Theia Station's shuttle has a few minor issues and this PR fixes them.
:cl:
fix: made a few minor improvements to Theia Station's escape shuttle
/:cl:

Minor Theia Station escape shuttle improvements

---

_maps/map_files/PubbyStation/PubbyStation.dmm

In #1260 I attempted to implement proper plumbing systems on Pubby Station. For the most part this worked, but about 20% of the systems were flawed and not actually functional. This PR should fix that (at the expense of a few toilets which had to be removed due to bathroom spatial constraints.)
Nonfunctional plumbing systems are bad, and this PR fixes a couple of them on Pubby Station.
:cl:
fix: fixed a few instances of nonfunctional plumbing on Pubby Station
/:cl:

Pubby Station plumbing fixes

---

_maps/map_files/TheiaStation/TheiaStation.dmm

This PR edits Theia Station's science department and fixes a few minor mapping issues present in said department. See the results of the MapDiffBot check on this PR for images.
These edits (hopefully) improve Theia Station's quality as a map.
:cl:
map: edited Theia Station's science department a fair bit
/:cl:

Theia Station science edits

---

fulp_modules/Z_edits/christmas.dm
tgstation.dme

The Grinch is dead and we killed him

---

_maps/map_files/TheiaStation/TheiaStation.dmm

This PR corrects a few small mapping errors present on the upper-rightish portion of Theia Station. A couple, incredibly minor aesthetic changes were also made along with these fixes. See the results of the MapDiffBot check on this PR for details/images.
There was a bathroom mislabeled as a supply closet ;-; 
:cl:
map: Fixed a few mapping errors on Theia Station
/:cl:

Corrects a few small mapping errors on Theia Station

---

_maps/map_files/PubbyStation/PubbyStation.dmm

This pull request makes a handful of minor improvements to Pubby Station's science department and surrounding maintenance. (See the results of the MapDiffBot check on this PR for images.)
These changes (hopefully) represent slightly better map design.
:cl:
map: made a handful of minor improvements to Pubby Station's science department
/:cl:

Minor Pubby Station science department improvements/fixes

---

_maps/map_files/SeleneStation/SeleneStation.dmm

This PR slightly edits/improves Selene Station's science department. See the results of the MapDiffBot check on this PR for images.
This will hopefully make Selene Station's science department more appealing to those engaging with it.
:cl:
map: Edited Selene Station's science department a bit.
/:cl:

Minor Selene Station science department edits

---

_maps/map_files/TheiaStation/TheiaStation.dmm

Re-does Theiastation's disposals system from scratch.
- The disposals delivery system is now 100%* functional!
- Removes 100% of pipes placed over walls and windows!
- Adds [The Wrungler](https://github.com/user-attachments/assets/5e8b4a62-8b9f-4496-ab76-ea93b898bc1b)!
- Removes 50% of disposal bins from atmospherics!
- Removes 100% of notes from the Supply department's airlocks!
- Closes 100% of Fulpstation issues! (#1245)
And ~~so much~~ absolutely nothing more!
*_It has not been tested that the disposals system is now 100% functional. In fact, this PR hasn't been tested at all yet._
:cl:
map: Re-does the Theiastation disposals system. The disposal delivery system now works properly.
/:cl:

TheiaStation: Repressurised!

---

_maps/fulp_maps/RandomRuins/IceRuins/beef_cytology.dmm

This PR edits a large portion of the Beefman Cytology ruin with the intent of improving it. Please refer to the results of the MapDiffBot check on this PR for images.
These changes add another layer of polish to a ruin that hasn't been updated in at least a year or so.
:cl:
map: edited the Beefman Cytology ruin.
/:cl:

Beefman Cytology Ruin Upkeep

---

tgstation.dme

tick a file that got unticked but shouldn't have been
ideally i'd update the "play credits" funtionality to use a folder contents instead of a hard coded list but thats for another midnight project
resolves #1311 probably
:cl:
fix: round end music plays appropriately at round end 
/:cl:

tick the credits file. lol.

---

_maps/map_files/PubbyStation/PubbyStation.dmm
_maps/shuttles/cargo_pubby.dmm

This PR makes a fair number of changes to Pubby Station's cargo bay for the sake of aesthetic and (to a slightly lesser extent) functionality. Images may be found in the results of the MapDiffBot check on this PR as per always.
This PR aims to improve a somewhat messy portion of Pubby Station.
:cl:
map: Edited Pubby Station's cargo bay.
/:cl:

Pubby Station Cargo Edits

---

_maps/map_files/TheiaStation/TheiaStation.dmm

This PR attempts to fix all (or most) of Theia Station's cameras. 
Currently a lot of cameras on Theia Station have their `c_tag` variable set to null (which is not ideal). A couple of them also share `c_tag` values, and there are a good few blindspots around the station. This PR should mostly fix those issues.
:cl:
map: Fixed a lot of cameras on Theia Station and covered unintentional blind spots.
/:cl:

Theia Station Camera Fixes

---

tgui/packages/tgui/fulpui-patches/FulpChangelog.jsx

This pull request _should_ fix our changelog.
I think the changelog broke during the final merge commit shown in PR #1345. All other Fulp TGUI files seem to have been moved while it was not, and I think that caused it to break. 
:cl:
fix: Fixed the Fulpstation changelog by moving its file.
/:cl:

Fulpstation Changelog Hotfix

---

fulp_modules/Z_edits/fulp_languages.dm
fulp_modules/features/antagonists/bloodsuckers/code/bloodsucker/bloodsucker_datum.dm
fulp_modules/features/antagonists/bloodsuckers/code/vassal/vassal_datum.dm

This pull request edits two lines in order to allow the bloodsucker language to be spoken.
Bloodsuckers (and their vassals) should be able to speak this language.
:cl:
fix: Bloodsuckers (and their vassals) should be able to speak Blah-Sucker again.
/:cl:

Fixes the Bloodsucker Language
