tools/build/build.js

You know what? fuck you. *skips your fulp_modules folder*
Makes fulp_modules part of dependencies so that it doesn't get skipped in case a change is made in ONLY that folder.
I've had multiple breakdowns but it doesn't compare to the ones i've had when I see 'skipping DM' only because I edited a file in there without editing any other file.

build.bat will no longer skip fulp_modules

---

fulp_modules/jobs/antag_protection_overwrites.dm

remake of #94 because I deleted the repository it was on.
:cl:
balance: Brig Doctors, Deputies and Head of Staff can no longer roll most antagonists.
/:cl:

Removes Command/Deputy/Brig Doc Antags

---

fulp_modules/container_init/machine_init.dm
fulp_modules/science_budget/readme.MD
fulp_modules/science_budget/science_budget.dm
tgstation.dme

The RD's tablet can already buy things from Cargo, and Science is more likely to use Bepis over Cargo, and money cannot be taken out of departmental budget cards. There's also a cool sprite that TG had made, even if they dont use it.
Rewards Science for doing their job by letting them do more of their job.
:cl:
add: A Scientific Department Budget card can now be found in the Research Director's locker. Enjoy your Bepis!
/:cl:

Adds a Scientific Department ID to the RD's locker

---

fulp_modules/bloodsuckers/code/antagonists/bloodsucker_datum.dm
fulp_modules/bloodsuckers/code/bloodsucker/bloodsucker_life.dm
fulp_modules/bloodsuckers/code/bloodsucker/bloodsucker_objects.dm
fulp_modules/bloodsuckers/code/gamemodes/monsterhunter_gamemode.dm
fulp_modules/bloodsuckers/code/powers/fortitude.dm
fulp_modules/bloodsuckers/code/powers/haste.dm
fulp_modules/bloodsuckers/code/powers/lunge.dm
fulp_modules/bloodsuckers/code/powers/masquerade.dm

Moths have eye sprites now, and Bloodsuckers, since it replaced with Bloodsucker eyes, would instnatly sell a Mothperson bloodsucker out instantly from just looking at their 1 pixel large eyeballs.
Bloodsuckers also get flooded with messages saying they're entering Torpor, but never actually revive, even if they're in their coffin.
:cl:
fix: Bloodsuckers now properly enter Torpor on death, and revive when under 100 Brute/Burn damage.
fix: Mothpeople bloodsuckers now have regular eyes again.
fix: Predatory lunge can now be used again, and will not permanently stun Bloodsuckers anymore.
fix: Haste can no longer be done while lying down.
balance: A monster hunter will now no longer be guaranteed to spawn during a Traitorsucker round.
/:cl:

Bloodsucker changes

---

fulp_modules/toys/code/toys.dm

It makes it so that the batong can fit on your belt slot, like the real baton. Also some grammar fixes in the supermatter toy description.
The batong is now more likely to fool security, this is good. Also better grammar.
:cl:
add: The ability to wear the batong on your belt slot!
spellcheck: Fixed some grammar errors in the supermatter toy description.
/:cl:

Makes the batong fit on the belt slot & fixes some grammar.

---

fulp_modules/cult_edit/cult_edit.dm
tgstation.dme

Remake of half of #72 
:cl:
balance: Cult's stun spell deals brute and bleed to Mindshielded people, rather than stunning.
/:cl:

Cult stun nerf, but modular, and without the zealot's buff

---

fulp_modules/jobs/deputy/code/deputy.dm
fulp_modules/jobs/deputy/code/deputy_clothing.dm

The mutadone medipen that each Science deputy receives as a part of their roundstart kit now contains 10u of mutadone instead of 60u of mutadone.
Science deputies now start each shift with two mutadone medipens instead of one.
Mutadone medipens now use the sprites for atropine medipens instead of the sprites for epinephrine medipens.
John Willard gave each Science deputy a mutadone medipen as a part of their starting kit. For some ungodly reason, this mutadone medipen contains **60u of mutadone** and injects **30u of mutadone** per jab (so, unlike the epineprhine medipen it shares a sprite with, it actually contains two doses, not one. that definitely won't confuse new players!). For reference, mutadone only needs one tick to purge your mutations, and it'll keep purging your mutations …

science deputy medipens now contain a sane amount of mutadone

---

_maps/map_files/SeleneStation/SeleneStation.dmm
_maps/shuttles/emergency_selene.dmm

idk
:cl:
fix: Fixed Selenestation's holodeck having a misplaced camera, no light, and inconsistent entrance tiles.
fix: Selenestation's kitchen table (the one with the vend-a-tray) now has a proper firelock.
fix: Selenestation - The newscaster in the Vacant commissary is now properly located on a wall.
fix: Selenestation shuttle - The outer cockpit airlock now actually lets security through.
/:cl:

Minor Selene fixes

---

_maps/map_files/SeleneStation/SeleneStation.dmm

Why why why why why why
This is untested I just copied over the access to the Medical airlock its connected to, so I assume it works.
:cl:
fix: People can no longer climb the Medical reception desk to open the Medical doors via the button.
/:cl:

Deletes Selenestation

---

_maps/map_files/SeleneStation/SeleneStation.dmm

There's like, 2 coffee vendors throughout the entire map. Science doesnt even have one, when they do on all other maps do.
Adds several coffee vending machines, including in the Bridge
Adds a cigarette vending machine in the Bridge
Renames the windoor in the bridge to Command Desk (Was Captain's Desk)
Replaces the cigarette refill vendor from the Bar's backroom with a cola refill.
Step 1) Cover your target in frost oil
Step 2) Watch as they die due to no coffee being anywhere on the map, and the bar being on the complete other end of the station
Step 3)
And yes, this is i ded.
:cl:
qol: Coffee vendors has been placed around Selenestation.
/:cl:

[Selenestation] Adds coffee vendors

---

fulp_modules/main_features/bloodsuckers/code/antagonists/bloodsucker_datum.dm
fulp_modules/main_features/bloodsuckers/code/bloodsucker/bloodsucker_life.dm
fulp_modules/main_features/bloodsuckers/code/powers/cloak.dm
fulp_modules/main_features/bloodsuckers/code/powers/fortitude.dm
fulp_modules/main_features/bloodsuckers/code/powers/lunge.dm
fulp_modules/main_features/bloodsuckers/code/powers/masquerade.dm
fulp_modules/main_features/bloodsuckers/code/powers/recuperate.dm
fulp_modules/main_features/bloodsuckers/code/powers/veil.dm

I hate sleep but I also dont know any other alternative I could use here.
Fixes #162 so thank you for opening that issue to bring this to my attention!
When the Antagonist is Playable ! 😳 
:cl:
fix: Bloodsucker passive abilities will no longer cancel if they get shove/stunned, will no longer drain immense amounts of Blood randomly, and will no longer prevent construction
fix: Bloodsuckers will no longer be able to infinitely buff themselves once they reach Rank 7
balance: Bloodsuckers can now remove their wounds by going through Torpor
fix: Recuperate now should work properly again.
/:cl:

Bloodsucker fixes (sleep is too strong)

---

_maps/map_files/SeleneStation/SeleneStation.dmm

I need mapping jobs, I'm going hungry
Moved the wrench outside
Officers can now wrench the canisters inside
:cl:
add: Wrench in execution room now accessible to officers
/:cl:

SeleneStation: Moving the wrench ,in the execution room closet, outside

---

_maps/map_files/SeleneStation/SeleneStation.dmm

Removes a crate from engineering that was stacked on top of another.
Can actually let engineers open the crate without a hassle
:cl:
fix: Fixed the stacked crates in engineering
/:cl:

SeleneStation: Crates stacked in engineering

---

code/___fulp_defines/fulp_defines.dm
code/game/objects/items/implants/implant_mindshield.dm
fulp_modules/main_features/bloodsuckers/code/antagonists/bloodsucker_datum.dm
fulp_modules/main_features/bloodsuckers/code/antagonists/monsterhunter_datum.dm
fulp_modules/main_features/bloodsuckers/code/antagonists/vassal_datum.dm
fulp_modules/main_features/bloodsuckers/code/bloodsucker/bloodsucker_coffin.dm
fulp_modules/main_features/bloodsuckers/code/bloodsucker/bloodsucker_crypt.dm
fulp_modules/main_features/bloodsuckers/code/bloodsucker/bloodsucker_daylight.dm
fulp_modules/main_features/bloodsuckers/code/bloodsucker/bloodsucker_integration.dm
fulp_modules/main_features/bloodsuckers/code/bloodsucker/bloodsucker_life.dm
fulp_modules/main_features/bloodsuckers/code/gamemodes/bloodsucker_gamemode.dm
fulp_modules/main_features/bloodsuckers/code/gamemodes/monsterhunter_gamemode.dm
fulp_modules/main_features/bloodsuckers/code/powers/brawn.dm
fulp_modules/main_features/bloodsuckers/code/powers/cloak.dm
fulp_modules/main_features/bloodsuckers/code/powers/haste.dm
fulp_modules/main_features/bloodsuckers/code/powers/lunge.dm
fulp_modules/main_features/bloodsuckers/code/powers/mesmerize.dm
fulp_modules/main_features/bloodsuckers/code/powers/monstertrack.dm
fulp_modules/main_features/bloodsuckers/code/powers/recuperate.dm
fulp_modules/main_features/bloodsuckers/code/powers/trespass.dm
fulp_modules/main_features/bloodsuckers/readme.MD
tgstation.dme

This PR aims to balance Bloodsucker's powers, there's too strong of a meta to get Brawn/Fortitude first because they're just too good compared to the rest.
:cl:
balance: Latejoining Bloodsuckers now get bonus Rank points to spend by entering their claimed Coffin.
code: The list of antag_allowed_vassals has been replaced with antag_banned_vassals
fix: Brawn now breaks open lockers.
fix: Recuperate should now work again.
balance: Cloak of Darkness now hides you from the AI, and hides you even better.
balance: Lunge will now tear the heart out of dead people.
balance: Immortal Haste will now mess with Monster hunters using Flow.
balance: It is now easier to break out of the persuasion rack, torturing the victim will prevent this.
fix: You no longer stop grabbing someone when dragging them …

Bloodsucker balancing changes

---

fulp_modules/main_features/jobs/deputy/code/deputy.dm

I didnt want to do this, I really hate this entirely. Deltastation's departmental cells require this access to function, Deputies cant use their sechuds, they cant open their department's locker (even if there's nothing in there they need), TG maps have forced my hand. I dont WANT deputies setting timers in the Brig by themselves, but there's no other choice here.
I just wish there was a way to prevent them from opening the security office's lockers without all the other garbage that comes along with it.
:cl:
fix: Deputies now get Security bounties
balance: Deputies can now access Brig holding cells, Sechuds and Security lockers.
/:cl:

Deputy access change & Bounty fix

---

_maps/map_files/SeleneStation/SeleneStation.dmm

Mining wardrobes were stacked in mining room
Stacked items suck 
:cl:
del: Removed one of the mining wardrobes stacked on another one
/:cl:

SeleneStation: Mining wardrobe stack fix

---

fulp_modules/main_features/bloodsuckers/code/bloodsucker/bloodsucker_coffin.dm
fulp_modules/main_features/bloodsuckers/code/bloodsucker/bloodsucker_life.dm

How Torpor works now
---
Torpor is triggered by:
- Being in a Coffin while Sol is on
- Entering a Coffin with more than 10 combined Brute/Burn damage
- Dying
Torpor is ended by:
- Having less than 10 Brute damage while OUTSIDE of your Coffin while it isnt Sol
- Having less than 10 Brute & Burn Combined while INSIDE of your Coffin while it isnt Sol
- Sol being over
Also, makes Torpor give you immunity to low pressure, so while flamethrowers/fire will still be an annoyance, you wont take damage to, for example, space. I've had 3 people complain already about being endlessly stuck in Torpor because they thought it would be a good idea to enter Torpor while in a depressurizing room.

Changes how Torpor is dealt with

---

_maps/map_files/SeleneStation/SeleneStation.dmm
_maps/selenestation.json

In black - old version
In magenta - new version
yes it works in Botany now.
I dont like Bartenders being shot in their own bar, or CQC not working in the bar's atrium because glass panes are meant to show that this is actually the theatre, but I'm also biased against Botanists because I just hate them all for making nothing but deathnettle.
Also there was no bar atrium or kitchen coldroom (despite that being an additional CQC area (why is it an additional area its done automatically)) so those have been added.
:cl:
balance: The chef's CQC in Selene works in the bar's full atrium and botany, but no longer in the bar itself.
balance: The table between the Kitchen and Botany has been replaced with a door.
/:cl:

[Selene] Edits (buffs) Chef's CQC

---

fulp_modules/main_features/beefmen/code/modules/mob/beefman_trauma.dm

Adds another check to the proc that returns the turf that the beefman phobetor tear can choose. Also documents it and makes it a bit more readable.
tl;dr beefmen can't teleport to areas that have the NOTELEPORT flag (CentCom, wizard's den, etc)
Finally got the motivation to do this
Also futureproofing in case that the non-human nuke ops PR at TG gets merged. (ALSO YES THIS FIXES WIZARD BEEFMAN, DONT REMIND ME OF WIZARD BREAKING INTO CENTCOM)
:cl:
fix: Beefmen can no longer teleport to areas that they shouldn't be able to teleport to.
/:cl:

Beefmen can no longer teleport to NOTELEPORT areas

---

fulp_modules/main_features/bloodsuckers/code/bloodsucker/bloodsucker_crypt.dm

Makes vassal rack unbuckle, and candelabrum's alt-click (which is toggle + unbuckle iirc) use RightClick
Willardtodo....
:cl:
qol: Vassal rack and candelabrum now use right-click instead of alt-click.
/:cl:

Makes vassal rack/candelabrum use right-click

---

fulp_modules/features/antag_tips/html/cultist.html

Adds a new line to the cultist antag tips that details the stun nerf present on fulpstation
Better clarity for custom nerfs; provides information that isn't present on the referenced wiki
:cl:
qol: Cult antag tips now mention the stun nerf
/:cl:

Adds Cult Stun Nerf to Antagonist Tips

---

code/modules/client/preferences_savefile.dm

Changes load_preferences() to account for beefmen features. Not currently modular, but neither is the file in general. If asked, I will try my best to modularize it
Preferences good
:cl:
fix: Beefmen preferences now properly load
/:cl:

[Non-Modular] Beefmen Preferences Fix

---

_maps/map_files/SeleneStation/SeleneStation.dmm

Moves camera in SM chamber so users can interact with the air alarm
Help A.I mains do their job
:cl:
fix: Moved AI chamber Camera down; can now be reached
/:cl:

SeleneStation: Moved camera in SM chamber so users can interact with the air alarm

---

_maps/map_files/Heliostation/Heliostation.dmm

These pipes used to be blue, so it would connect to the pipe UNDER the gas pump, rather than to the gas pump.
🚎

[Heliostation] Fixes atmos from being sabotaged roundstart

---

code/game/gamemodes/objective.dm
fulp_modules/main_features/bloodsuckers/code/antagonists/bloodsucker_datum.dm
fulp_modules/main_features/bloodsuckers/code/antagonists/monsterhunter_datum.dm
fulp_modules/main_features/bloodsuckers/code/antagonists/vassal_datum.dm
fulp_modules/main_features/bloodsuckers/code/bloodsucker/bloodsucker_objectives.dm

Admins giving Bloodsucker objectives will now no longer say 'Nothing', and they can now give the Monster hunter's objective to destroy all monsters.

Fixes admins giving Bloodsucker objectives & Adds monster hunters to admin list

---

_maps/map_files/Heliostation/Heliostation.dmm
_maps/map_files/SeleneStation/SeleneStation.dmm

Selene:
Helio:
CO2 is meant to be sent back into the waste pipes so there's always CO2 for the station's freezers to send heat to, every map but the Fulp ones have this.

[Selene & Helio] Makes CO2 get filtered back into waste

---

_maps/map_files/SeleneStation/SeleneStation.dmm

There were TWO Wags-His-Tail spawns in the Selene custodial closet. Now there is only ONE.
Janitors powergaming moodbuffs from petting TWO Wags-His-Tail (they should only get one moodbuff as only one Wags-His-Tail should spawn1!)
:cl:
fix: Removes lizard
/:cl:

Removes game breaking oversight.

---

_maps/map_files/SeleneStation/SeleneStation.dmm

Moves a pump down to help atmospheric techs
I was told that it would possibly stop atmospheric technicians from being racist
:cl:
balance: atmospheric room tweaks
/:cl:

SeleneStation: Atmospheric room pump shift

---

_maps/map_files/SeleneStation/SeleneStation.dmm

Some pipes are runtiming because other pipes are connecting to what they were meant to connect to, leaving them empty.
I'm doing a lot of mapping work and thought it would be nice to fix this really quick since Fulpateers don't like messing with smart pipes.

[Selene] Fixes atmos

---

_maps/map_files/Heliostation/Heliostation.dmm

- Removes the telepad (adds another portable flasher to the armory - one was removed in the previous PR, so this is readding)
- Moves sinks from the cells to the bathroom
- Removes 3 bookcases (no longer enough to make a baseball bat)
- Replaces all windows with reinforced windows (can no longer easily break them to make spears with the glass shards)
- Moves space heater to the perma maint area
- Removes the drink vendor (no more greybull)
Fuck perma mains.

nerfs helio's perma

---

code/___fulp_defines/fulp_defines.dm
code/modules/admin/sql_ban_system.dm
fulp_modules/Z_edits/race_bans/races.dm
fulp_modules/global_vars.dm
fulp_modules/main_features/beefmen/code/modules/mob/beefman.dm

I really wish these problems could have been addressed in the initial PR, but it was already merged. If a PR is gonna be treated like a meme during the review phase (Where problems are replied to with "Dont care") then it should be treated as a meme during the merge phase.
This frustrated me enough to make me want to fix it at midnight
Bans are no longer evaluated every time spec_life is called, fewer lines are modified in tg files, might be able to fully modularize it
:cl:
admin: More races can be banned, and it's easier to add even more (Ban for EVERY race????)
code: Added a global list of Fulp bans in the format of the job ban list in the sql ban code to more efficiently modularize ban code
code: Reduced the number of lines overridden in a TG file from 5 to 1... for now
code: Moved the …

Race Ban Code Improvement [Not Modular... Yet?]

---

fulp_modules/main_features/bloodsuckers/code/bloodsucker/bloodsucker_coffin.dm

Before, secure coffins took 4 (four) welder hits to break open, as fun as it is to shit talk this coffin, I want to see a crazy lava coffin gimmick.
Armour sucked and coffin didn't have resistance flags, I wanna see more people using this sprite and design idea. New coffin should have just under the armour of the metal coffin, with lava acid, explosion and fire resistance 
:cl:
balance: Makes the secure coffin more secure, increasing its armour
/:cl:

Secure coffin armour buff

---

fulp_modules/main_features/bloodsuckers/code/antagonists/bloodsucker_datum.dm

Rolling Bloodsucker as midround or getting it via Ventrue Favorite Vassal doesn't remove your mutations unless you go on and back off of Masquerade.

Fixes midround Bloodsuckers keeping mutations

---

fulp_modules/Z_edits/race_bans/bans.dm

Race ban code is now officially a ship of theseus
:cl:
code: Improves the clarity of sync_mind by adding an ishuman check
code: Re-adds the check_banned call to on_species_gain so banned people cant use mutation toxin or a pride mirror to change to their banned species
code: Modifies check_banned to early return if the mob doesnt have a ckey
code: Adds some comments to the race ban code
/:cl:

Fixing Race Code 2: Electric Boogaloo

---

_maps/map_files/Heliostation/Heliostation.dmm
_maps/map_files/SeleneStation/SeleneStation.dmm

Module duplicators were missing from Selene/Helio, unlike the official TG maps. Now they're not.
Module duplicators are supposed to be in every circuit lab.
:cl:
add: Added module duplicators to Selene/Helio 
/:cl:

Adds module duplicators to Selene/Helio

---

fulp_modules/mapping/ruins/icemoon/beefman_cytology/beef_cytology.dmm

Adds a moat around the cytology spawner. The pickaxes have also been removed. Stabilized pink extracts have been added to the testing room. This should (hopefully) keep the miners out and keep the beefyboys in. I keep hearing that they're abandoning the base and joining the station, which is kinda not the point of a tutorial spawner. The pink extracts should also make accidentally spawning a hostile mob a little more forgiving.  ![cytofix](https://user-images.githubusercontent.com/69338705/129433218-484c4908-f5b8-422d-b35c-10649f0c5dff.png)
:cl:
balance: adds moat and stabilized pink extracts/ removes pickaxes
/:cl:

Minor changes on the cytology spawner

---

fulp_modules/main_features/jobs/deputy/code/deputy_clothing.dm

New Bloodsucker PR is gonna blacklist them from Bloodsuckers, the only antag they can roll now is obsessed and whatever else Security can roll.
Difference this makes:
- Security should hopefully be less trustful of Deputies looting Security gear they shouldnt have
- They cant be rolled as the Cult's target
- They, like the Quartermaster (except the QM isnt prepared with a stunbaton) can be converted to a revolutionary by a headrev (though cant roll headrev themselves)
- They are prone to brainwash/hypno grenade (they bowmans to counter it anyways)
Let's lie to the players and say deputies can be antag, the look on antag roller's faces when they don't roll antagonist and have to protect their departments will be awesome!

Removes deputy's mindshield

---

fulp_modules/features/clothing/body_cameras/body_camera.dm

Allows the bodycams purchased from the sec vendor to be equipped on any jumpsuit, as opposed to the only Security jumpsuits from before.
Fashion police. 
Adds the ability for Security to wear jumpsuits other than the standard few, for the Officers who want more variety in their looks or to go undercover without forfeiting the benefits of the bodycam. Halloween is coming up, and as of now Officers will have to decide between body cam or costume. Additional, functionality to spy on crewmembers by placing it on their jumpsuit.
:cl:
del: Removed the check for a security jumpsuit on bodycams
/:cl:

Allows bodycams to be worn on any jumpsuit

---

config/maps.txt

Adds runtimestation to the map rotation, being votable
Give me one (1) good reason why not.
:cl:
add: Added RuntimeStation brand stations to the station rotation.
/:cl:

Adds runtimestation to map rotation

---

fulp_modules/main_features/bloodsuckers/code/powers/tremere/dominate.dm
fulp_modules/main_features/bloodsuckers/code/rulesets/bloodsucker_rulesets.dm

People didn't know Dominate's vassalization only works while next to the target.
Fixes that, and also;
1) adds more player feedback to know why something wouldn't work
2) makes vassalizing work in hardcrit
3) makes it only start the cooldown upon being activated, so cancelling out won't force you to wait the very long cooldown.

Dominate: Better player feedback and fixes

---

fulp_modules/main_features/bloodsuckers/code/bloodsucker/bloodsucker_life.dm

Fixes Malkavian revelations not showing as being Forced when viewed thru ingame logs and game.log so I can't tell if I should bwoink or if John coded these slurs in, also makes it annoying to filter out game.log with Notepad++ when I should be able to hide lines containing "FORCED". Only works with Malkavian revelations that aren't whispered until my fix PR is merged on tg and we tgu but it wouldnt require any extra changes to this code once thats done so i might aswell PR this now.
Ugly and cannot be filtered out with Notepad++ easily, I will not read your game logs. 😢 
:cl:
admin: Malkavian revelations are now logged correctly.
/:cl:

Fixes Malkavian admin loggings

---

fulp_modules/features/clothing/body_cameras/body_camera.dm

Bodycameras get installed in the armor vest instead of the jumpsuit
Antags dont have to disable sec's suit sensors to disable their body camera.

Moves bodycamera to armor vests

---

_maps/map_files/SeleneStation/SeleneStation.dmm

renames the airlock to the art gallery one so it stops showing up as this

Fixes selene library airlock name

---

_maps/map_files/Heliostation/Heliostation.dmm
_maps/map_files/SeleneStation/SeleneStation.dmm

every map ever besides deltastation and fulp maps until now has an announcement console in tcomms and when I pointed it out to helian yesterday he told me and i quote "when you map it"
also changes the selene tcomms smes not being connected idk why it wasnt and i dont think anybody knew about that
tcomms smes originally mapped by insane individual (tom f hardy)
tcomms smes mapped by contributor with knowledge of how the game works (me)

makes fulp maps more like every other map that isn't deltastation

---

_maps/map_files/Heliostation/Heliostation.dmm
_maps/map_files/SeleneStation/SeleneStation.dmm

Selene: Repaths 2 cameras to update them to directionals
Helio: Fixes the SM waste pipe, makes incinerator SMES not connected to the grid, adds a thermomachine to its distro.

[Selene & Helio] Small map fixes

---

_maps/map_files/Heliostation/Heliostation.dmm
_maps/map_files/SeleneStation/SeleneStation.dmm

Renames most (hopefully all) cameras, airlocks and APCs from Selene and Helios that are still named after toxins to instead be named after ordnance.
Toxins is old and bad.
Ordnance is new and good.
The prosecution rests. 
:cl:
spellcheck: Removes mentions of toxins in airlocks and cameras of Selene and Helios in favour of Ordnance
/:cl:

Syriniver shot for Helios and Selene (Removing mentions of toxins)

---

fulp_modules/features/lisa/joelgun.dm

This PR fixes the fact Joel's Gun's Misdirection ability could ~~put people inside objects, including but not limited to: 
scrubbers, vents, rolling chair and the nuke, from which they could not exit without admin intervention.
As far as I can tell, the actual intended part remains functionally the same as it used to be.~~
merge people together now, apparently?
This should fix that. 
Fixes a ~~pretty big~~ problem with the thing, hopefully without creating any larger ones. 
:cl:
fix: Joel's Gun's misdirection now uses ~~.throw_at~~ step_towards rather than .Move to avoid previous glitches.
/:cl:

Misdirection can no longer break the laws of physics

---

_maps/map_files/SolitaireStation/Solitairestation.dmm

Adds a security buzz-in, right next to the entrance of brig. 
Removes a rare material spawn, which has the chance to spawn runed metal.
Security buzz-in is a nice quality of life that all stations would benefit from. 
Having 30 runed metal spawn in a fixed position, is a huge boon for cultists, which already thrive due to Solitare's large maintenance.
:cl:
add: Added security buzz-in
del: Removed rare material spawn
/:cl:

Solitare: Sec buzz-in and runed metal removal

---

fulp_modules/features/mentors/mentorhelp.dm
fulp_modules/features/mentors/mentorpm.dm
fulp_modules/features/mentors/mentorsay.dm

Allows for mentors and staff to be pinged in Msay and allows for hyperlink conversions from urls in mentorhelp and msay.

Msay and mhelp QOL (Pinging, hyperlinks)

---

fulp_modules/Z_edits/inititalize_edits/closet_init.dm

Removes the roundstart digitigrade shoes that spawn on every sec and medical locker.
They are almost never used, if a lizard loses their shoes they can be bought on the vendor, simply locker bloat.
qol: After some deep research on the subject, our economists realized that supplying digi shoes for sec and medical lockers is a waste of money for NT. This will increase the quality of life of workers that don't have to deal with spare shoes throw around on the floor every shift. This will decrease the quality of life of lizards that want a free shoe, or moths that are hungry so nothing of value was lost.
/:cl:

Remove digitigrade shoes from some lockers.

---

fulp_modules/mapping/ruins/icemoon/beef_cytology.dmm

Just swap a few tiles to the icemoon version.
Cut 3 tiles that are processing atmos at roundstart.
fix: Buff Atmos techs by giving them a little bit of more CPU processing or something.
/:cl:

Fix small atmos issue on Beeftology station.

---

_maps/map_files/Heliostation/Heliostation.dmm

Science never actually had an APC which was why lights never went down and why the cell charger in science never actually worked and you had to move it to xenobio/techfab room.

makes science actually have an APC

---

_maps/map_files/SeleneStation/SeleneStation.dmm

Sometimes when I played on Fulpstation server when they were running their famous map "Selene Station" I would see this:
And think to myself: "Wow! This is certainly a 'Selene Station' moment!" but it has now come time for me to fix these issues that make us look bad on the lobby screen
Below are examples of things I fixed there were some more that i didnt screenshot but I think some of these are funny or what do you think
(solars not using the airless subtypes were like 80% of them)

Fixes all of the 375 roundstart active turfs on Selene Station

---

fulp_modules/features/bloodsuckers/code/bloodsucker/bloodsucker_life.dm

i was trying to figure out why beefstation people spawned with human names instead of beefman ones and so I checked runtimes and this is when i spotted this
Its been an issue since like #407 and its caused malkavians to lose their cooler gimmick idk how this wasnt reported before also i still dont know whats up with beefmen spawners if someone knows that would be cool i think

Fixes the best clan

---

code/___fulp_defines/fulp_defines.dm
fulp_modules/mapping/ruins/icemoon/beefman_cytology/beefcyto_spawner.dm

pepsi couldn't figure out why it was broken so I said I'd do it.
- Beefman Cytology and Beefman space spawner now have proper job titles (as they end up on the round-end screen with hypnotism trauma)
- Beefmen spawners now spawn with unique Beefmen, rather than human ones.

Fixes beefman spawner names (name + role name)

---

fulp_modules/features/halloween/2021/costumes.dm

Deadcells' hat now has an icon again, it was a subtype of something that didn't exist.
WOW. AMAZING. INCREDIBLE. TRULY.

Fixes non-existant icon for the deadcell hardhat

---

_maps/map_files/SolitaireStation/Solitairestation.dmm

-Changes Maints Tech Storage airlock from Maintenance/Atmospherics to Maintenance/Tech Storage
-Adds Nitrite Gloves to the pile of roundstart equipment for MDs in Medical Storage
-Fixes issue from the Solitaire feedback thread 
-Minor facelift to Science EXPERIMENTER Testing Room
Roundstart MDs having to rush their gloves or get stuck with the loser's latex isn't a good situation, considering other stations either have a pile or are designed for a smaller pop, while this is the maxpop map. 
Having the maints airlock for Tech Storage as an "atmosian backdoor" is an L. Ask your boss. 
Fixing issues as they come up in the thread is good.

[Solitaire] Minor fixes

---

_maps/map_files/SolitaireStation/Solitairestation.dmm

Removes a flying camera that was in atmospherics on solitairestation.
The ai's visibility in the room was not affected by this change as the room already had enough cameras in it
cameras are supposed to be attached to walls, not flying
:cl:
fix: Fixed flying camera on solitaire atmospherics
/:cl:

Fixes flying camera on solitaire atmospherics

---

_maps/map_files/SeleneStation/SeleneStation.dmm

Adds a fire alarm that was missing in selene station cryogenics, moved the intercom over a tile as i felt the fire alarm fit better in it's spot.
I also slightly adjusted the areas to prevent a firelock in the medbay halls from coming down when it shouldn't.
Rooms are supposed to have fire alarms in them.
Prevents doctors getting stuck unable to turn the fire alarm off when they turn on environment as reservoir on their cooler and allows engineers to actually turn the alarm off when they fix it.
:cl:
fix: Fixes missing fire alarm in selene cryo
fix: Changes area placement to prevent firelocks coming down in medbay halls coming down when the cryo alarm is pulled
/:cl:

Fixes missing fire alarm in selene cryo

---

_maps/map_files/SolitaireStation/Solitairestation.dmm

- Addresses some problems brought up in https://github.com/fulpstation/fulpstation/pull/488
- Remakes most of arrivals, including holodeck/dorms/maints around it
- Moves science down
- Fixes random problems I found while working on this
- Cuts back on more maints
Solitaire needs a complete disposal overhaul, but first we need to overhaul all the individual departments.
Service, Medical, Engineering and Supply, and Departures is what's left to be done after this PR, as well as maints but I'd worry about that last.
We can make Solitaire an actual unique map since it does have a lot of promise to it. I've also sunk to much time into this map to just let it die.

solitiare arrivals re-make

---

fulp_modules/mapping/ruins/space/beef_station.dmm

replaces some of the titanium walls with the nodiagonal variants because they're somewhat ugly in some places see below
some other fixes like the space injector turned into a passive vent, air alarms & the bar tables having the wrong dirs & some qol stuff like being able to upload books into the archive
:cl:
/:cl:

beef statio nimprovement

---

fulp_modules/mapping/ruins/icemoon/beefman_cytology/beefcyto_spawner.dm

Fixes names on both beefmen spawners (Scientist Cytologist and the space one thing)
They actually get names now.
They were BOTH broken, not JUST the space ones. @SmoSmoSmoSmok F you

fixes a runtime with beefmen spawners (fixes names)

---

fulp_modules/features/antagonists/bloodsuckers/code/powers/cloak.dm

Cloak of darkness now only takes into account people who can visibly see you, rather than people near you.
People can't see through walls, unless they can, in which case they can, but generally can't.

Makes cloak not care for people who can't see you

---

fulp_modules/features/clothing/body_cameras/body_camera.dm

It's still currently only limited to vests, but in the future we can allow the element to maybe be admin-added onto anything, it sounds pretty cool on paper but I am just not motivated enough to go all the way, after being awake over 24 hours.
This change also makes it so bodycameras don't just fucking qdel itself when being inserted into a vest, and make a BRAND new one whenever you "take it out", and removes the dumb "upgraded" var.
Either way, this is still a major improvement, and allows us to add body cameras to different types of suits more easily (code-wise only atm)
I also don't like the copypaste in it but it is fine for now.

Refactors bodycameras into an Element

---

_maps/map_files/Heliostation/Heliostation.dmm
_maps/map_files/SeleneStation/SeleneStation.dmm

Hard to explain without going in details of how tcomms in mapping works but the bs receiver's presets were meant for the servers opposite side of the room
More consistency, hard to notice unless you're familiar enough already with how Tcomms work
:cl:
fix: more consistency in how Tcomms operate on helio & selene
/:cl:

Rearranges Helio & Selene Tcomms to make more sense for the 3 people that know how tcomms work

---

fulp_modules/features/antagonists/bloodsuckers/code/powers/targeted/lunge.dm
fulp_modules/features/antagonists/bloodsuckers/code/powers/targeted/trespass.dm
fulp_modules/features/antagonists/bloodsuckers/code/powers/veil.dm

- Brings back immediate aggro grabs because just passive grabbing sucked
- Makes riot gear and monster hunters be protected from lunges the same way, as to cut down on needless copypaste.
- Removes instead, the Stun, from using the ability itself, which was detached from the grabbing itself. This still being in the game meant there was no different if lunge aggro grabbed since you can just aggro grab manually anyways.
- Adds a new limit, you can't lunge while you have someone grabbed already.
- Makes predatory lunging at low levels make you spin around and cause smoke, before you lunge at your target. this means that during low levels, predatory lunge is pretty weak. I'm considering bumping this bypass to level 6 or so, and make the timer needed to lunge lower as you level up.
- Because …

Predatory lunge rework

---

fulp_modules/features/prison/prison_shuttle/prison_shuttle_template.dm

fixes trash spawns spawning in weird places that it shouldn't (i.e. in TURBINES)
:cl:
fix: Trash will no longer spawn in odd places on the prison shuttles.
/:cl:

Fixes trash spawning in structures on prison shuttle

---

fulp_modules/features/clothing/body_cameras/body_camera.dm

Body cameras try to do things elements aren't supposed to do, so I swapped them out for Component instead.
If 2 officers got a body camera, what the first officer did with it would affect all others, because all elements were DUPLICATES AND AFFECTS EACHOTHER because THAT'S how elements work YEA

makes body cams a component

---

fulp_modules/features/antagonists/bloodsuckers/code/bloodsucker/shaded_bloodsucker.dm

Because being shaded expects you to have been shaded by someone else, it runtimes if the body has no ghost, as it tries to 'capture' their soul via the user with the shard, which doesn't exist in this case.

Fixes shaded bloodsuckers

---

_maps/map_files/Heliostation/Heliostation.dmm
_maps/map_files/PubbyStation/PubbyStation.dmm
_maps/map_files/SeleneStation/SeleneStation.dmm

This PR made some toxins changes: https://github.com/tgstation/tgstation/pull/65289.
This updates fulp maps to do it exept the removing co2 canisters part bc i like those and feel like it might get used in toxins later on. I also expanded helio launch chamber a bit since the connector would block machines if you put a canister on it. Puppy has a bit extra canisters since sci has to share with atmos (L)
Bit more lattice on Selene since i thought it looked weird.
qol and updates fulp maps to TG canister ammounts.
:cl:
qol: Standardizes canister ammounts.
qol: Helio launch chamber is a bit bigger so that you don't block machines with your canisters on the tank compressor.
add: More lattice on Selene so it looks less weird hopefully.
/:cl:

Standardize toxins + helio qol

---

fulp_modules/_defines/signals.dm
fulp_modules/features/antagonists/bloodsuckers/code/antagonists/bloodsucker_datum.dm
fulp_modules/features/antagonists/bloodsuckers/code/antagonists/monsterhunter_datum.dm
fulp_modules/features/antagonists/bloodsuckers/code/antagonists/vassal_datum.dm
fulp_modules/features/antagonists/bloodsuckers/code/bloodsucker/bloodsucker_integration.dm
fulp_modules/features/antagonists/bloodsuckers/code/bloodsucker/bloodsucker_life.dm
fulp_modules/features/antagonists/bloodsuckers/code/powers/_powers.dm
fulp_modules/features/antagonists/bloodsuckers/code/powers/monstertrack.dm
fulp_modules/features/antagonists/bloodsuckers/code/powers/targeted/_powers_targeted.dm

Bloodsuckers, Monster Hunters, and Vassals, keep their stuff through debraining, such as their powers, martial arts, ect ect.
Bloodsuckers can also now be debrained, it won't final death them. They won't be able to do much, but in the case they are somehow revived, they will continue to be a Bloodsucker. I'm thinking maybe they would be able to rebuild their body by vanishing act like how they regrow limbs. Very stupid idea but sounds funny and forces security to properly final death a bloodsucker.
Also opens us later to maybe being more lax on Bloodsucker dismemberment? Lots of possibilities in the future so I think this is a neat step forward.

Bloodsucker expansion - Debraining

---

_maps/map_files/SeleneStation/SeleneStation.dmm

Morgue's access from hallways needed medical, morgue, maints AND chapel access to enter so nobody on the station but the captain could actually go through, it now only requires morgue access.
Also changed the service hallway airlocks to use the new service access instead of what we had before
this shit is confusing so both surgery rooms are now part of a single surgery area
that chunk of med maints is now part of F/S maints for consistency, also adds maints to the walls where there should be maints
fixes some decal issues that were missed when the library was remade
fixes perma windows not actually being shocked
shocks sec posts' windows
replaces these cycle links with multi ones
Changes all grass tiles on the station from /turf/open/floor/grass to /turf/open/misc/grass
fixes this stool …

More Selene issues

---

_maps/pubbystation.json

Pubby is a smaller map with a smaller permabrig, so they should have half the prisoners to make up for it. They don't even HAVE 4 cells. kinda fucked up.

Lowers pubby's prisoners to 2

---

fulp_modules/Z_edits/job_edits.dm

Halves the Paramedic job slots (4 roundstart -> 2 roundstart, 8 total (roundstart+latejoin) -> 4 total)
Paramedics currently have very little to do, gathering bodies is hard to do when you have 7 other players doing so. This causes paramedics to completely lose interest in trying to be the first ones to find a body, and instead just loiters Medbay or starts doing the MD's jobs.
They also abuse their access to greytide and such, but all these cases relate to one thing:
Having less paramedics makes the lack of/greytiding by, Paramedics, more impactful (and noticable) on the round, and makes the individual paramedics be more invested in their own job as they have more to do, seeing it isn't split between so many people anymore.
Our current job position list (iirc) was made when we were …

halves the amount of paramedics

---

fulp_modules/Z_edits/job_edits.dm

Brings Cyborg positions down to 1 (latejoin is still disabled).
Cyborgs spawning roundstart is something I've never been a fan of. Cyborg isn't a job, it's a role. You transition into one through borging.
I'd rather people who want to play Cyborg would go Assistant instead, and turn into one through Robotics. This gives Robotics a thing to do early in the shift, gives Miners a reason to get materials early on in the shift, and makes Cyborgs feel closer to the Robotics department as a whole, as they created your shell and did the surgery needed to get you in there.
I find Cyborgs with this, would be more likely to actually respect the Robotics department, and even return later for upgrades or model resets, something basically never see nowadays.
I also kept a single cyborg slot, because …

removes nearly all borg positions

---

_maps/map_files/Heliostation/Heliostation.dmm
_maps/map_files/PubbyStation/PubbyStation.dmm
_maps/map_files/SeleneStation/SeleneStation.dmm

List of change:
**HelioStation**
- Service Maint | ("12;22;25;26;28;35;37;38;46;70") to ("12;73") 
- Service Techfab | ("22;25;26;28;35;37;38;46;70") to ("73")
- "Engineering Maintenance" to "Tech Storage Maintenance"  | ("10; 24") to ("12;23) | 
_why would you give atmo tech access to tech storage, and medic even used to be able to enter before the medic access  nerf_
- Solar External Airlocks - Port Bow, Starboard Bow, Starboard Quarter | ("10; 13") to ("10")
- External Airlocks - Med Maint | ("24") to (0)
- External Airlocks - Evac| ("13") to (0)
- Morgue Hallway - ("6;5;28") to ("6")  
_Medical access(5) is supposed to use on medical morgue airlock to block off people from entering med with only morgue access, not using it on morgue hallway airlock. Also, cook comes with morgue access …

Fulp Maps Access Overhaul (Mainly Solar/External Airlocks)

---

_maps/map_files/Heliostation/Heliostation.dmm
_maps/map_files/PubbyStation/PubbyStation.dmm
_maps/map_files/SeleneStation/SeleneStation.dmm

Cryo has been changed since TGU, so it is currently broken on Fulp maps. This replaces the oxygen canisters on those maps with anesthetic mix.

Fixes cryo on fulp maps

---

_maps/map_files/Heliostation/Heliostation.dmm
_maps/map_files/PubbyStation/PubbyStation.dmm
_maps/map_files/SeleneStation/SeleneStation.dmm

Updates the Helio and Selene labour shuttle docking ports so they don't spawn facing the wrong way and changes Pubby's to use the new generic labour shuttle.
Now you can enter the labour shuttle!
:cl:
fix: Fixed the labour camp shuttles in Heliostation, Selenestation and Pubbystation.
/:cl:

Makes Fulp maps' labour camp shuttles work again!

---

fulp_modules/features/cargo/cargo.dm

Adds a Mutadone Medipen cargo crate, under Security. This allows Security to easily de-hulk people assuming cargo delivers, and allows Science to replace used medipens.
Also fixes the price for the other crates, since they currently cost less than the price of the crate itself. You can buy these over and over, then resell the empty crate and turn a profit.
I added this item but we rarely see it used because it is limited to a single job that not many people play as. Hoping this would make dealing with hulks easier and less lethal.

adds a mutadone medipen cargo crate + fixes exploits

---

fulp_modules/_defines/bloodsuckers.dm
fulp_modules/features/antagonists/bloodsuckers/code/antagonists/bloodsucker_datum.dm
fulp_modules/features/antagonists/bloodsuckers/code/antagonists/monsterhunter_datum.dm
fulp_modules/features/antagonists/bloodsuckers/code/bloodsucker/bloodsucker_daylight.dm
fulp_modules/features/antagonists/bloodsuckers/code/bloodsucker/bloodsucker_flaws.dm

cool code improvement !
Removes a bunch of useless stuff, replaces it with persistent bloodsucker HUDs
I mean these ones
not the antag huds.
Also vampire rank display is supposed to update when you have a rank to spend, but it didn't work at all. Now it does, which is pretty cool. It adds a + to know you have unspent ranks.
Also removes 3 vars off of /datum/hud, which is good for lag, especially since we tend to have higher pop than TG, it's best if we don't make it worse for ourselves.

bloodsucker huds persist through bodies

---

fulp_modules/features/antagonists/bloodsuckers/code/powers/_powers.dm
fulp_modules/features/antagonists/bloodsuckers/code/powers/cloak.dm
fulp_modules/features/antagonists/bloodsuckers/code/powers/feed.dm
fulp_modules/features/antagonists/bloodsuckers/code/powers/fortitude.dm
fulp_modules/features/antagonists/bloodsuckers/code/powers/gohome.dm
fulp_modules/features/antagonists/bloodsuckers/code/powers/recuperate.dm
fulp_modules/features/antagonists/bloodsuckers/code/powers/targeted/_powers_targeted.dm

Moves Bloodsucker stuff from the on_life signal to Process.
It's more consistent this way while not sacrificing lag or errors. This signal shouldnt be overused, and Bloodsuckers already use it lots for their own on_life.
It also isn't something that lasts a whole round, like Bloodsucker life, so its fine to process instead.

moves bloodsucker powers to Process

---

fulp_modules/features/species/beefmen/mob/beefman.dm

fixes this 
fixes this
:cl:
fix: es this 
/:cl:

fixe s meatman icon bgu=

---

fulp_modules/features/antagonists/bloodsuckers/code/bloodsucker/bloodsucker_coffin.dm

When setting a lair as bloodsucker you used to get two tips informing you of your new crafting recipes, one of them pointing you to the wrong menu. Now there's only one and it correctly tells you the recipes are under the Tribal crafting menu.
Spellcheck and stuff.
:cl:
spellcheck: the crafting recipe bloodsucker tip now points you to the right category
/:cl:

Fixes typo in bloodsucker tip and removes redundant info message

---

_maps/map_files/Heliostation/Heliostation.dmm
fulp_modules/mapping/ruins/space/beef_station.dmm

this makes aspects of heliostation swagger
fixes these
updates arcades to use their dirs
this APC sucked & controlled an area that isnt even adjacent to it and it confused the shit out of me when i played AI today so I moved it inside of the area
fixes that
this was never connected to wastes so i connected it even if it wont be relevant next tgu
y does linters allow this
these are the subtypes meant for inside the gas 3x3 places in atmos not to dispose into space
lots of c_tags had bad tags that didnt represent the current states of the places they were @ so i gave them better names
this shit
this
the arrow is meant to face east
updates the areas in solars to use /area/solars instead of /area/maintenance/solars
:cl: …

Swags Heliostation

---

fulp_modules/features/clothing/body_cameras/body_camera.dm

Lets sec vests hold body cameras.
security doesn't have to sacrifice better clothes for lack of a body camera (and it has lower armor already so :/ )

Adds body camera to sec vests

---

_maps/map_files/Heliostation/Heliostation.dmm
_maps/map_files/SeleneStation/SeleneStation.dmm
fulp_modules/mapping/ruins/icemoon/beef_cytology.dmm
fulp_modules/mapping/ruins/space/beef_station.dmm
fulp_modules/mapping/shuttles/cargo/cargo_selene.dmm

Missing wire and duplicate pipe (look at the blue pipe's tint on the right of the ghost)
Duplicate pipe (smart pipe stacked on top of regular scrubber pipe on the same layer)
These errors caused by the multilayer cable hub that connect SM output to SMES
Changed a few xeno spawns
these catwalks looked off because there isn't any turf or lattice under some of these grilles
Replaced pharmacy's smart fridges with the preloaded kind (courtesy of Cook77 (zed oppenheimer (my friend) ) )
Replaced chem lab's chem heater with the kind thats preloaded with buffers
Adresses the missing signs that I found when figuring out [#67209](https://github.com/tgstation/tgstation/pull/67209)
Fixed the APCs for 
/area/station/hallway/secondary/exit/departure_lounge
/area/station/solars/aux/port …

A few map fixes

---

fulp_modules/Z_edits/felinid_edit.dm
tgstation.dme

Felinids now start with 199 brain damage and are given a roundstart severe and mild trauma, apart from the ones they'll get from the brain damage.
Furthermore, wearing cat ears will now make you clumsy, dumb and make you slur your speech occassionally - this, on top of getting 75 brain damage every time you wear it (with a cap of 199). If you have any ideas of what to add (reasonable within traits) to this as to discourage it more, feel free.
This was requested by the admins in [our feature request forum](https://forum.fulp.gg/t/felinids-start-with-brain-damage/1910/84).
This should heavily discourage anyone from trying to seek becoming a felinid.
i've added several failsafes that should stop the abuse of the cat ears (such as only you being the one able to equip them, not being able to …

Felinids, or anyone trying to become a felinid, now start with brain damage

---

fulp_modules/features/antagonists/bloodsuckers/code/powers/fortitude.dm

Accident, Monster hunter's ability isn't supposed to cost blood.

Flow doesn't cost blood anymore

---

fulp_modules/Z_edits/felinid_edit.dm

CI error was caused by felinids spawning with the aphasia brain trauma which when qdeleted runtimes lol
Also the kitty ears give you 100 instead of 75 brain damage now i think it improves the game a bit
:cl:
sounddel: Ci doesn't fail anymore
/:cl:

Fixes our CI, Putting on cat ears gives just a bit more brain damage

---

fulp_modules/features/antagonists/infiltrators/infil_items.dm

The description of the advanced mulligan now tells you that its one use and when you stab people with it you don't hit them with it visually like probably intended since its stealthy.
Mulligan is now actually stealthy and less confusing.
:cl:
add: The advanced mulligan now tells you its one use.
fix: When you stab people with the advanced mulligan you won't hit them on the head with it.
/:cl:

Advanced mulligan no bludgeon and it says its one use in its description

---

_maps/map_files/Heliostation/Heliostation.dmm
_maps/map_files/PubbyStation/PubbyStation.dmm
_maps/map_files/SeleneStation/SeleneStation.dmm

HoP no longer oversees cargo and doesn't need half the consoles in his office now that QM is a proper head, replaces them with account lookup consoles. Also fixes some oversights at Helio's bridge & ordnance
Supply hates the HoP now
:cl:
fix: Fixes our HoP offices
/:cl:

Removes cargo-related stuff from our HoP offices

---

_maps/shuttles/prison_kitchen.dmm

It didn't even need the warden's permission to be used.
Fixes #674
Fixes #675
Having the skillchip only available through the shuttle instead of having it mapped onto the station is pointless as it's unusable without the station's json allowing for its use in the prison so no extra benefits is brought by using the proposed alternative.

Removes the free Close Quarter Cooking skillchip from the prison shuttle

---

_maps/map_files/Heliostation/Heliostation.dmm
_maps/map_files/SeleneStation/SeleneStation.dmm
fulp_modules/features/prison/prison_cargo.dm

Fixes #679 
Replaces the request console with a modular console that has its own version of NT IRN and budget card inside. It having its own subtype only matters when its first initialized, if the CPU is ever deleted, the same functionality is obtained from simply asking HoS or QM for NT IRN to be installed on any tablet/laptop, the subtype is only needed to have it run on a console & create the ID. If the ID is destroyed no functionality other than being able to input money directly into the budget is lost, a regular prisoner ID running in a console under NT IRN will still use the prison budget.
Switch from request console to NT IRN modular computer has two side effects:
- Prisoners are unable to order themselves guns or any dangerous items a prisoner ID does not have access to.
- …

Allows prisoners to use the prison budget

---

_maps/map_files/Heliostation/Heliostation.dmm

the wires under the shocked windows were actually never connected to the powernet which i thought they were when i moved the smes

Makes Helio tcomms charge

---

fulp_modules/features/antagonists/bloodsuckers/code/antagonists/bloodsucker_datum.dm
fulp_modules/features/antagonists/bloodsuckers/code/bloodsucker/bloodsucker_crypt.dm

Ventrue Bloodsuckers now only lose the blood spent to upgrade, when they actually spend it. If they cancel out they will no longer be charged.

Fixes Ventrue bloodsuckers using blood when not levelling up

---

_maps/map_files/SeleneStation/SeleneStation.dmm

Since the change to firelocks they'll now check both their sides for bad atmos as opposed to before where it was the fire alarm thatd determine that. This meant the Selene's R&D server room's firelock triggered everytime at roundstart.

Removes the Selene RD office firelock

---

_maps/map_files/SeleneStation/SeleneStation.dmm

Some joker put a x8 maintenance loot spawner over a crate spawner which can spawn as a mini fridge that has a low storage capacity & that makes it all shit itself

Nerfs SeleneStation's medbay maints' crate

---

_maps/map_files/SeleneStation/SeleneStation.dmm
_maps/selenestation.json

Includes and should be limited to:
- Added a body spawner in the morgue
- Added an outlet pump for the n2o tank in atmospherics
- Added an air alarm to the incinerator/turbine room
- Slightly changed atmospherics, extending it one tile down in size to better accommodate the previously missing piping
- Fixed the atmoshpheric space access airlocks to let atmos technicians pass
- Several area changes (mostly the same as the helio PR, additionally the plating floor rooms in xenobio are now considered xeno maints, bar atrium relabelled to cafeterial. Json changes to go along with this.)
- Button fixes (same as the helio PR)

Miscelaneous Selenestation fixes and changes

---

fulp_modules/features/species/beefmen/mob/beefman.dm

Because spawners use randomize_human, which is a hardcoded base proc not attached to anything and cannot be modularized, we are instead setting it to randomize on the species' gain.
Sucks, but works.

Fixes beefman spawners

---

fulp_modules/features/antagonists/bloodsuckers/code/bloodsucker/bloodsucker_integration.dm

Bloodsuckers can no longer use a syringe/IV drip to remove their own blood at no cost, then re-inject themselves with it for infinite blood.

Bloodsuckers lose blood when willingly removed

---

fulp_modules/features/events/bruhspace_anomaly.dm

After moko said in discord that bruhspace anomaly was a funnier name, I decided to make this. Restores bruhspace event text to Mith's version at https://github.com/TheSwain/Fulpstation/pull/81 (thank you John for bringing this event back)
It's more familiar for the people who remember the original event.
:cl:
balance: bruhspace anomaly event text is restored to Mith's version
/:cl:

Bruhspace event text is restored to mith's version

---

_maps/map_files/Heliostation/Heliostation.dmm

Did some oopsies while fixing the merge conflicts on the heliostation shuffle PR. Also fixed/qol'd some other stuff while I was at it.
- Fixes air alarm over a door on the aft hallway
- Fixes the missing wire connecting the engineering foyer (and by extension the station) to the rest of engi
- Fixes the missing piping and wiring connecting to vault and grav gen
- Removes the wiring in grav gen that bypassed the SMES unit
- Removed under-wall wiring from all solars
- Added AI upload access requirements to the doors leading into the AI's chamber
- Adds a wire under the engineering console in the SMES room for AmpCheck to work properly.
- Makes the turbine igniter button be inside the room with a pixel offset rather than being on the wall itself, since it allowed people to interact with it …

Post-shuffle heliostation fixes

---

_maps/map_files/Heliostation/Heliostation.dmm

Removed a door to space because there were three doors in a row. Fixed access where you only needed teleporter access to get into captains office and also fixed the HoP flash so it works.

Removed a door, fixed Captains offices access and HoP flash 

---

_maps/map_files/Heliostation/Heliostation.dmm
_maps/map_files/PubbyStation/PubbyStation.dmm
_maps/map_files/SeleneStation/SeleneStation.dmm

- Adds the unrestricted access helpers that lead out of maints present on tg maps and pubby to Selene and Helio
- Adds PACMAN units to maints in Selene, Helio and Pubby for the same reason as above
- Fixes the broken access on the disposal windoors of Selene and Helio and the ones in Pubby's cargo
- Fixes missing pipes from engi to the rest of the station and a misplaced light on Helio.
- Moves the firelock on pubby's cargo shuttle one tile back so that it's not constantly being triggered by exposure to space
- Makes the locker in CMO office accessible on Pubby
- Some helio piping issues

Updates Fulp maps to some new TG standards and fixes some stuff

---

fulp_modules/features/halloween/2021/costumes.dm

Fixes two typos that referred to the jumpsuit as a "thirsy flower jumpsuit" and a "thirty flower jumpsuit" respectively
Typos bad spelling good
:cl:
spellcheck: fixes two typos
/:cl:

Fixes two typos in the description and name of a jumpsuit

---

_maps/map_files/Heliostation/Heliostation.dmm

Adds layer adapters to Heliostation atmos outputs.
QOL change that is standard on tgstation based maps. Removes the need for atmos techs to do this at shift start so a single output can be used for multiple purposes.
:cl:zhepyrlion
qol: heliostation atmospherics gas chamber outputs now have layer adapters
/:cl:

Adds layer adapters to heliostation atmos gas chamber outlets

---

_maps/map_files/Heliostation/Heliostation.dmm

This is a handful of quality of life changes I have made to Heliostation, mostly to medbay. For real this time because I had unneccessary commits in the other one.
- A button has been added to control the radiation shutters for the SM chamber.
- Desk bells have been added to Robotics and Research desks.
- A window and shutter has been added between Surgery rooms A and B. The shutters are also now proper shutters rather than blast doors.
- Directional access was added leading out of the chemisty/virology access hallway. Those coming out of maintenance will no longer have to travel all the way around to enter central medbay.
- Glass tables in surgery rooms have been reinforced so that squirmy patients won't destroy them as easily.
- The Surgical theater has been fitted with a defibrillator …

Heliostation QOL Changes, Mostly Medbay

---

_maps/map_files/Heliostation/Heliostation.dmm
_maps/map_files/SeleneStation/SeleneStation.dmm

I noticed Helio and Selene did not have plasma stabilizer and thermal regulator modules in engineering like most other stations do. Both stations will now have one of each available at round start. I also did the same for Selene's medbay as it was also missing these modules. Very minor changes were made to make things look tidy. Selene engineering won't start with a spare solars crate. Selene medical storage won't start with boxes of beakers and body bags.
Now lizards and plasmamen don't have to go begging to robotics to be able to use their department provided modsuits.
🆑 
add: plasma stabilizer and thermal regulator added to Selene Engineering and Medbay and Helio Engineering
remove: removed roundstart solar crate in Selene engineering
remove: removed round start beaker and body bag …

Modsuit Utility Modules

---

_maps/map_files/Heliostation/Heliostation.dmm

Fixes Heliostation's Law office fax machine being public, and fixes CMO's PDA painter from being inaccessible due to the fax machine's placement.
Addresses issues #847 and #845 on Helio by moving the placements of their fax machines, and adding an extra fax machine to the law office.
Goes from this:
To this:
And here's the law office:
If the CMO doesn't have access to their PDA painter how else will they demote all the Walter White's that blow up chemistry for the 80th time? On a serious note, without access to the PDA painter, CMO can't do PDA changes within their own department, so I'd argue its fairly important. Also lawyers can no longer be impersonated using their fax, since their fax is no longer open to the public.
:cl:
fix: fixed CMO's PDA painter being inaccessible
fix: fixed the …

Fixes Helio Fax Machine Placement Problems

---

fulp_modules/features/antagonists/bloodsuckers/code/powers/tremere/auspex.dm

Changes auspex teleport range at levels 3-5. Changes range from 6 tiles to 9 tiles. This brings it closer to the wiki's description of the power (https://wiki.fulp.gg/en/Bloodsucker).
This is a followup to a bug report I made about a month ago: https://discord.com/channels/279359975250198528/587000604547874826/1040732505449439283
As previously stated, it makes the power perform closer to the wiki's description, preventing confusion among players. Also, there isn't really any reason to arbitrarily cap the teleportation at 6 tiles range, when normal player view is 9 tiles.
ShadowAKT:cl:
fix: Fix Bloodsucker "auspex" range
/:cl:

Fixes Tremere auspex range

---

_maps/map_files/PubbyStation/PubbyStation.dmm

Instead of 1 airlock and no atmos, adds a second airlock and sets both airlocks to cycle + atmos vents are now in the cargo dock at pubbystation.
Fixing atmos issues is good, not much more to say. You could previously depressurize the area with ease if you weren't careful, makes it not do that anymore.
:cl:
qol: PubbyStation's cargo dock now has two airlocks which cycle, and atmos, this makes it so it won't lose oxygen so easy.
/:cl:

adds atmos and airlock cycle to pubby cargo dock

---

fulp_modules/features/antagonists/bloodsuckers/code/powers/tremere/auspex.dm

Imagine this scenario:
Bloodsucker walks up to you
Goes invisible for 2 seconds
Puts you to sleep
You never wake up
That's fun, right?
Getting put to sleep in literal seconds by an antagonist who can essentially instakill anyone sleeping is very, very strong, and with no counters whatsoever, it makes it a pain to deal with for everyone else.
Inspired by a round I played through recently.
:cl:
balance: Bloodsucker's Auspex ability no longer puts people to sleep, but they now have the level 4 affects of causing you to bleed.
/:cl:

Auspex no longer puts you to sleep

---

_maps/map_files/SeleneStation/SeleneStation.dmm

The original PR was cut short because I wanted it out to be out by the 2023 deadline this makes it better
Fixes #898 
Adds a secure storage area for engineering (that one place with shield generators and stuff)
Redoes the entirety of the turbine instead of it being a 1:1 of the old one.
Makes accessing the outside of the HFR room in space easier since you don't need to circle around the turbine. Neat qol is that the mix chamber is visible from it and is overall far more aesthetically pleasing, atmos is slightly bigger by like 3 tiles down as a result check the MDB render for a better idea I guess.

Selene Engineering Definitive Edition

---

_maps/map_files/PubbyStation/PubbyStation.dmm

Removes the firelock in AI chamber / Adds space shutter in brig equipment room
There's no reason to have some random firelock there in AI chamber.
Also giving shutter for brig equipment room so some random space dust won't space the room
:cl:
balance: removes the firelock in AI chamber and adds space shutter in brig equipment room
/:cl:

[Pubbystation] Removes the firelock in AI chamber / Adds space shutter in brig equipment room

---

fulp_modules/features/antagonists/bloodsuckers/code/bloodsucker/bloodsucker_conversion.dm

RequireDisloyalty runs then checks AmValidAntag, which itself alone doesn't have a mind check, could use conditionals

fixes a runtime

---

fulp_modules/features/species/beefmen/phobetor_trauma.dm

Beefmen tears now don't have two periods and properly show up above mobs
Fixes 👍 
:cl:
fix: Beefmen tears now show up above the mob
spellcheck: Beefmen tears no longer end in 2 periods.
/:cl:

Fixes problems with beefmen tears

---

_maps/map_files/Heliostation/Heliostation.dmm

My brain short-circuited when I was reworking heliostation engineering and decided it was good idea to put 2 electrified grille/waste spawner, thinking it would be funny to troll players.
Turn out I am the only one who is trolled because I mange to walk onto it at least 3 times every single round.
You shouldn't be running into shocked grille when going into straight line in maint such as this:
:cl:
balance: removes the electrified grille/waste spawner in Heliostation engineering maintenace 
/:cl:

Removes the electrified grille/waste spawner in Heliostation engineering maintenace 

---

_maps/map_files/SeleneStation/SeleneStation.dmm

Selene's morgue did not have a computer to do any advanced surgeries or surgeries that required a computer. This should now allow doctors to do surgeries such as dissections roundstart in the morgue.
Out of all the maps Fulpstation offers, the morgue routinely offers a surgical table and operating computer for doctors to perform surgeries with. However, Selene was the only map to only feature a table, and no computer, resulting in doctors having to assemble their own or drag corpses out of the morgue for surgeries that required a computer, such as dissections. 
Before:
After:
Allows doctors to actually operate in the morgue and perform surgeries that require the operating computer to perform. Mostly good for round-start dissection surgeries. Also removes the unnecessary table with a …

Adds an operating computer to Selene's morgue

---

fulp_modules/features/antagonists/bloodsuckers/code/bloodsucker/bloodsucker_conversion.dm
fulp_modules/features/antagonists/bloodsuckers/code/bloodsucker/bloodsucker_procs.dm
fulp_modules/features/antagonists/bloodsuckers/code/bloodsucker/bloodsucker_sol.dm
fulp_modules/features/antagonists/bloodsuckers/code/clans/clan_ventrue.dm
fulp_modules/features/antagonists/bloodsuckers/code/powers/gohome.dm
fulp_modules/features/antagonists/bloodsuckers/code/structures/bloodsucker_crypt.dm
fulp_modules/features/antagonists/bloodsuckers/code/vassal/types/revenge_vassal.dm
fulp_modules/features/antagonists/bloodsuckers/code/vassal/vassal_datum.dm

Bloodsucker's Vanishing Act should now let them re-exit Sol after
Antags should be vassalizable again
Bloodsuckers can no longer have two of the exact same power (Ventrue Favorite Vassals)
Sunlight properly starts and ends now
Ventrue Favorite Vassals now automatically start with their new powers at a power level of 1, meaning they can use Feed from the start.

Fixes some Bloodsucker issues

---

_maps/map_files/PubbyStation/PubbyStation.dmm
config/maps.txt

**Adds a HoochMaster Deluxe** (Bar variant of CondiMaster/ChemMaster) **to the Pubbystation Bar**, adds a 2nd Bar Requests Console in Bar Storage (Next to the double-barreled shotgun), moves around most of the wall-mounted stuff in the Bar (Newscaster, Request Console, Intercom, Fire Alarm), and adjusts the Light switch's X/Y position a little. No changes to the Lounge.
This tweaks the layout of the wall-mounted objects in a mildly more appealing manner, as well as adding a HoochMaster Deluxe, which Pubby's bar **doesn't have**. This forces the Bartender(s) to take or build a ChemMaster or equivalent machine if they want to make cocktails of any complexity. I also believe the storage room could use an additional request console. If nothing else, it's a little extra clutter.
:cl:
add: Adds …

Adds HoochMaster Pubbystation's Bar

---

fulp_modules/mapping/ruins/icemoon/beef_cytology.dmm

Bro its been like half a year since carps arent simple animals whats up with that
I replaced the carp in the cell with a slime because carps are bitch to deal with nowadays and will just teleport outside the moated ruin + their cells can be gotten from moisture traps anyway
I also added a guaranteed fern plant because everything fun is locked behind them which says a lot because cyto isnt actually fun

Allows beefcyto to actually spawn

---

fulp_modules/features/antagonists/infiltrators/infiltrator.dm

Gives infiltrator their own survival box instead of re-using the one given to nuclear operatives.
Nukie survival boxes come with a note explaining explosive implants. Infiltrator doesn't get an implant, so this paper can be quite misleading for people playing. Personally I've been duped by this several times (I'm smoothbrained). This PR gives infiltrator their own survival box. I chose to keep the atropine medipen as it's good at healing, but can be swapped out for a regular epi if coders want it.
:cl:
add: Infiltrators now have their own survival box.
/:cl:

Infiltrators now have their own survival box

---

fulp_modules/features/mentors/mentorwho.dm

What it says on the tin.
Avoids situations where Mentors might have the game on the background waiting for the sound cue and thus appear AFK, discouraging people from Mhelping if they see no mentors online.
:cl:
qol: AFK mentors are no longer hidden from MentorWho
/:cl:

AFK mentors are no longer hidden from MentorWho

---

fulp_modules/features/prison/prison_kitchen/_restaurant.dm

What it says on the tin.
Closes the correctly diagnosed issue #1034
:cl:
fix: Prison seating projectors and Prison restaurant portal boards are now printable from proto/autolathes.
fix: The prison restaurant portal boards are now printable from the security protolathe rather than the service one.
/:cl:

The prison seating projector and portal board now appear on protolathes. Moves the latter to the sec protolathe.

---

_maps/map_files/Heliostation/Heliostation.dmm

The doors for medical storage were named "Coroner office", which is wrong. This fixes that
Self-explanatory
:cl:
spellcheck: Fixed the names of the medical storage doors on Heliostation
/:cl:

Fixes medical storage door names on helio

---

_maps/map_files/PubbyStation/PubbyStation.dmm
_maps/map_files/SeleneStation/SeleneStation.dmm

The freezer chamber HE pipes don't actually connect because there isn't a HE junction there, just a normal pipe. This PR fixes that on both Selen and Pubby
Fixes #937, and the same issue on Pubby
:cl:
fix: Fixes the freezer chamber in Selene's ordnance lab
fix: Fixes the freezer chamber in Pubby's ordnance lab
/:cl:

Fixes Selene and Pubby ordnance freezer chamber

---

fulp_modules/mapping/station_objects/trees.dm

Pixel offset cherry tree. Any maps that use it might want to check that the positioning still makes sense!
Fixes #893
:cl:
image: cherry tree now has appropriate collision
/:cl:

add pixel offsets so the collision makes sense

---

fulp_modules/features/antagonists/bloodsuckers/code/bloodsucker/bloodsucker_life.dm
fulp_modules/features/antagonists/bloodsuckers/code/bloodsucker/bloodsucker_sol.dm

Change torpor mechanic to be blocked if user is frenzied (or is dead and has 0 blood). Am open to input
Prevents torpor loop whilst technically unable to recover.
:cl:
fix: torpor healing and dying loop closed
/:cl:

Frenzied torpor

---

_maps/map_files/Heliostation/Heliostation.dmm

Redoes the entire wiring of heliostation. The stated goal is to replace the current design with a circular design. 
The station's wiring runs from engineering clock-wise arounds the station, with branches inside each department to reach every APC in them but with hardly any redundancies or cross-department bridges, with the exception of cargo and engi which link back up at the end of the powernet's journey.
This simplifies the powernet, making it easier to follow the trail of wires through maints, while retaining some robustness for the powernet, since you must cut a wire on both sides of a section of wiring to cut power to it.
`As of the latest commit`: Adds electrical danger signs accompanied by maintenance tunnel signs to locations where a wire runs through a maints entrance. This will …

Rewiring Heliostation for a circular design

---

fulp_modules/features/species/beefmen/phobetor_trauma.dm

Some QoL to Beefman
You can now teleport when you are 1 tile away from the tear, instead of being forced to be on top of it.
You will click the tear if you click the floor turf it is on, just like how airlocks work, no more pixel hunting.
Screentips.
And reworked some balloon alerts that were too long.
Random QoLs while I was making sure my Fulp branch was setup correctly again.
qol: Clicking on the floor turf under a tear will move your click into the tear, easier teleports with no pixel hunting.
balance: Beefman can teleport using tears when they are 1 tile away from it instead of needing to be on top.
/:cl:

Turf click redirection for beefman tears, 1 extra range to interact with them, screentips and shoter balloon alerts

---

fulp_modules/features/halloween/2020/costumes.dm

The halloween costume box had the wrong gnome hat.
I used to gnome people with the box and couldn't because it was bugged, now I can gnome people again!
fix: The gnomed halloween box spawns the correct gnome hat now.
/:cl:

Fix gnomed

---

_maps/map_files/Heliostation/Heliostation.dmm
_maps/map_files/PubbyStation/PubbyStation.dmm
_maps/map_files/SeleneStation/SeleneStation.dmm

What it says on the tin. They were either normal surgery duffels or normal trays, which don't have the cruel tools coroners should have access to.
Thanks to Nintyuk for pointing this out in the forums.
Gives coroners the tools they should have roundstart.
:cl:
fix: morgues on fulp maps now have coroner surgery trays, with their cruel surgery tools
/:cl:

Gives Heliostation, Selene and Pubby's morgues coroner surgery trays

---

_maps/map_files/Heliostation/Heliostation.dmm
_maps/map_files/PubbyStation/PubbyStation.dmm

When I ported the helio rewire over to the tgu i forgot to add the bitrunner vendor.
Also removes a maints item spawner from inside the rocks in pubby's bomb test site that caused tests to fail beause of RNG.
Bitrunners like to be able to order stuff ig
:cl:
fix: Fixes Heliostation not having a bitrunning order console
/:cl:

Added bitrunner order console to helio

---

fulp_modules/Z_edits/fulp_verbs.dm
fulp_modules/features/mentors/mentor.dm
fulp_modules/features/mentors/mentor_clientprocs.dm
tgstation.dme

- What it says on the tin. Basically a copypaste from `reload_admins()` but calling `load_mentors()` instead. Should be noted that, while it requires admin permissions, I've placed it in the mentor tab for convenience.
- Added a block to `load_mentors()` to ensure admins whose ckey may not be in the mentor list are also considered when reloading. This may not be entirely desireable, as it's a situation that shouldn't happen, but we already do it in mentor_datum_set(), so it's mainly for consistency.
- Removed the seemingly useless parameter from `mentor_datum_set()`. What's that thing for?
This required a new Z-Edit, found in `fulp_verbs.dm` to add the verb into the `AVerbsDefault`, since it's a protected list.
Requested by an admin.
:cl:
fix: load_mentors() now correctly loads admins as …

Adds Reload Mentors as an admin verb

---

fulp_modules/Z_edits/fulp_languages.dm
fulp_modules/features/species/beefmen/russian.dm
tgstation.dme

What it says on the tin. Recently re-reported, apparently it had been brought up before but I forgot to actually make the PR.
Oopsie.
Downside is that it requires a new Z-edit. Gave it its own file in case we ever do more stuff with languages in the future.
Primarily for the sake of compatibility with the bilingual quirk, since no other ways to learn space russian come to mind.
:cl:
fix: humanoids who know Space Russian can now speak it without having a beefman tongue
/:cl:

Allows normal tongues to speak Space Russian

---

fulp_modules/tg_edits.md
tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/game_preferences/antag_tips.tsx

What it says on the tin. We lost the TGUI file in a TGU, so players weren't able to change the setting.
Also moved it to the `game_preferences` folder rather than the `character_preferences` one (not sure why we kept it there) and updated the `tg_edits.md` file accordingly.
Bug fix
:cl:
fix: Antag tips can once again be toggled on and off in the "Gameplay" section of game preferences.
/:cl:

Re-adds the option to toggle antag tips

---

fulp_modules/features/prison/prison_kitchen/food_overwrites.dm
fulp_modules/features/prison/prison_kitchen/prison_bots/head_of_security_bot.dm
fulp_modules/features/prison/prison_kitchen/prison_bots/lizard_bot.dm
fulp_modules/features/prison/prison_kitchen/prison_bots/prisoner_bot.dm
fulp_modules/features/prison/prison_kitchen/prison_bots/rat_bot.dm
fulp_modules/features/prison/prison_kitchen/prison_bots/warden_bot.dm

So anyway I was minding my business in helio perma when this occured
Naturally I was shaken to my core, trying to regain composure I quickly opened the coding program of my choice and fixed the paths for the grilled cheese sandwich as well as the one of the cheese wedge.
It turns out redefining the items to add extra venue prices kind of screws us in the long term when the typepath changes and we inevitably dont get notified
i also modified a few values mostly related to how soup got refactored to add extra steps and how korta is more easily orderable
:cl:
fix: fixed bad perma prison bot orders
/:cl:

prison bot rebalance

---

fulp_modules/features/halloween/_code.dm

Closes  #1068.
Cleans up the procs for halloween beacons and gifts to remove useless checks on one hand and redundant work on the other.
The only other player-facing change is that the debug beacon is actually unlimited now, previously it was false advertisement.
Bugfix and code improvement.
:cl:
fix: Halloween gifts can no longer be empty due to choosing a box prototype
fix: The debug halloween beacon has actually unlimited uses now.
code: Removes useless checks and redundant loops from the code for halloween gifts.
/:cl:

Code cleanup on halloween gifts and beacons

---

_maps/map_files/Heliostation/Heliostation.dmm
_maps/map_files/SeleneStation/SeleneStation.dmm

adds:
request consoles 
notice boards
paper bin on helio
filing cabinet on helio
these things were missing on fulp maps.
the notice boards are a cool addition I think 
:cl:
add: notice boards on fulp maps' detective offices
fix: adds a few missing objects and items in det office
/:cl:

Makes some minor additions to detective offices on helio and selene (NOTICE BOARDS :D) 

---

_maps/map_files/PubbyStation/PubbyStation.dmm

Moves the intercom in Ordnance closer to the bomb thing so it gets announced properly
Also change it to a regular intercom (previously was a chaplain one)
Moves bitrunning to Cargo like the other maps, rather than being shoved in maints
Makes Prison botany a little smaller
Removes valentines card from CMO office
Removes spare boots from HoS office
Removes spare gas mask from Warden's office
Fixes some of starboard solar not being attached to an area
Miners now have 3 closets instead of 6 previously
pubbystation now more consistent w/ other maps n stuf n yea
:cl:
fix: [Pubbystation] Bitrunning is now in Cargo
balance: [Pubbystation] Miners now have 3 closets instead of 6
fix: [Pubbystation] Ordnance now has the proper intercom that announces to the station, and it can actually pick up the …

Fixes to pubbystation.com

---

_maps/map_files/Heliostation/Heliostation.dmm

Recycler on helio was facing the wrong way, now it's not.
Makes the recycler face the right way
:cl:
fix: Helio's recycler now faces the right way
/:cl:

Fixes recycler direction on Helio

---

_maps/map_files/Heliostation/Heliostation.dmm
_maps/map_files/PubbyStation/PubbyStation.dmm
_maps/map_files/SeleneStation/SeleneStation.dmm

Helio, Pubby, and Selene are currently missing the bigger canvases. Well, no more! On Pubby and Helio I just put them on the tables that were already there, but for Selene I had to add a couple of extra ones on the sides. Nothing crazy though. Also replaces some of the small frames with the big ones, so there's a place to mount the new canvases.
Selene
Pubby
Helio
Art is good, bigger art means bigger good.
:cl:
add: NT has finally begun stocking the art rooms of their stations with larger canvases!
/:cl:

Adds bigger art canvases to fulp maps

---

_maps/map_files/Heliostation/Heliostation.dmm
_maps/map_files/PubbyStation/PubbyStation.dmm
_maps/map_files/SeleneStation/SeleneStation.dmm

Adds syndicate docking ports to Pubbystation, Heliostation and Selenestation. These are named Northwest under the docking_port/syndicate
Adds syndicate docking ports to Pubbystation, Heliostation and Selenestation. These are named Northwest under the docking_port/syndicate
It should be possible to do your final.
Adds syndicate docking ports to Selenestation, Pubbystation and Heliostation.
:cl: fix 
/:cl: fix

Fulpstation specific maps syndicate docking ports addition.

---

fulp_modules/features/halloween/_code.dm
tgstation.dme

i messed up and forgot to add this code
I apparently missed the vital code to make it spawnable outside of admin spawns so now the 2023 costume can spawn
it fix mistake :)
so when adding 2023 to the beacons i forgot to add the code to make it spawn in beacons the costume is now no longer admin spawn only
:cl:
code: adds the missing code to make it spawn in halloween beacons (whoopsie)
:cl:

adds 2023 to the halloween beacon

---

fulp_modules/features/antagonists/bloodsuckers/code/bloodsucker/bloodsucker_conversion.dm
fulp_modules/features/antagonists/bloodsuckers/code/structures/bloodsucker_crypt.dm

What it says on the tin.
There's nothing else player facing (other than a balloon alert), but code-wise `can_make_vassal()` will now succeed even if the target is in hardcrit or worse. That check is now specific to the persuassion rack which is (currently) the only other way for someone to become a vassal.
It's a bugfix.
:cl:
fix: Posession now revives those who are dead or in hard crit and turns them into temporary vassals
qol: Added a balloon alert that indicates when someone cannot be tortured in a persuasion rack due to being dead or in hard crit.
/:cl:

 Posession now does revive the dead and turns them into temporary vassals

---

fulp_modules/_defines/fulp_defines.dm
fulp_modules/mapping/areas/areas.dm
fulp_modules/mapping/ruins/space/syndicate_engineer.dmm
fulp_modules/mapping/ruins/space/syndicate_engineer/syndicate_engineer.dm
tgstation.dme

It's exactly as it says on the tin-- Syndicate Engineers are back!
(MDB render is a bit fucky but rest assured I fully tested it)
FulpStation is a beginner server, so having a space ruin dedicated to teaching new players the basics of engineering is... well, natural.
:cl:
add: Syndicate Engineer Ghost Role
add: Prototype Station Space Ruin
/:cl:

Syndicate Engineers & The Prototype Station

---

fulp_modules/features/antagonists/bloodsuckers/code/bloodsucker/bloodsucker_flaws.dm

Admins choosing a clan for bloodsuckers through their traitor panel now gets a tgui list rather than a radial one, so they don't have to be physically near or observing the player they're editing.
admins can fix bloodsuckers without having to wonder why they just get the message saying they are "too far" because they were still in-game.

admins get a tgui list instead of radial for clans

---

fulp_modules/features/antagonists/bloodsuckers/code/bloodsucker/bloodsucker_integration.dm
fulp_modules/features/antagonists/bloodsuckers/code/clans/_clan.dm
fulp_modules/features/antagonists/bloodsuckers/code/powers/_powers.dm

Updates all blood updates for bloodsuckers go through AddBloodVolume()
Consistency is king.
:cl:
refactor: Removes blood updates that directly manipulate bloodsucker_blood_volume and forces them to use AddBloodVolume instead.
/:cl:

Makes all blood updates go through AddBloodVolume

---

fulp_modules/features/species/beefmen/mob/beefman.dm

this fixes beefmen hair not matching the color tone of their body
fixes beefmen hair not matching the color tone of their body
:cl:
fix: beefmen hair will now inherit the beefman's color
/:cl:

fix beefmen hair not matching their meat's color

---

fulp_modules/mapping/ruins/space/syndicate_engineer.dmm
fulp_modules/mapping/ruins/space/syndicate_engineer/syndicate_engineer.dm

This changes a few things about the syndicate engineer space role. In short,
- They have a space heater to combat the fact that space is cold
- Completely modernized the atmos tanks (the vents and injectors are no longer controlled by the air alarm, but instead a computer)
- They get more metal so they don't run out of supplies prematurely
- They also get a circuit imprinter to produce the required circuit boards for APCs and the like
- There now is a box of lights to help brighten up the place
- The space injector has been replaced with a passive vent to mirror how it is on the main station
- Some other things too minor to mention (like changing the position of some gibs)
It also fixes a few things, detailed in the changelog
Syndicate Engineers were lacking some things they needed to …

Prototype Station Tweaks

---

fulp_modules/features/antagonists/infiltrators/albino_gorilla.dm

Only Albino Gorilla has magic gorilla powers NOW. All gorillas used to have these powers.
It was a bug

Only Albino Gorillia has magic gorilla powers

---

fulp_modules/mapping/deathmatch/code/deathmatch_loadouts.dm
fulp_modules/mapping/deathmatch/code/deathmatch_maps.dm
fulp_modules/mapping/deathmatch/maps/heliocentric.dmm

Adds the Heliocentric arena, based on a somewhat popular station map.
Beeftide
Masquerader
No sunflower was harmed in the making
:cl:
add: Heliocentric, DM map.
/:cl:

Adds a second fulp Deathmatch arena

---

_maps/map_files/Heliostation/Heliostation.dmm

This is a good idea on paper but layered cables is pretty non functional right now. You can place cables down there as normal and it would overwrite the SMES and behaves VERY weirdly, so I think it's best to avoid this altogether. I moved things around so SMES cables don't have to go through walls but still, no more layer 1 cables in the SM chamber.
I also removed the floating sm delam counter in CE's office and fixed the floating poster in telecomms

removes helio's layer 1 cables in sm chamber

---

_maps/map_files/SeleneStation/SeleneStation.dmm

Reworks Selene's medbay. Here's what it looks like:
Notable changes:
- Moves psych out of the corner and into an easily accessible part of medbay
- Adds a paramedic prep area
- Makes cryogenics less of a pain to set up
- Adds a storage room for cold storage, moves the corners of stuff into a less in-the-way area
- Adds a box of body bags for medical doctor use
- Embiggens medbay central
- Fixes access error in chapel
Here's botany: 
It's pretty much just aesthetics
Mentors (shout out to @JohnFulpWillard and Max Willis) gave lots of good suggestions on how to improve medbay, and this PR implements them in a way that will (hopefully) improve playability on Selene. Having psych in a more centralized location and putting the extra equpiment in maints improves the psych's ability to interact …

Selene Medbay Rework

---

fulp_modules/_maps/RandomRuins/SpaceRuins/syndicate_engineer.dmm

Some airlocks had variables assigned to them that were no longer being used, causing runtimes; those variables have been summarily executed.
Less runtimes!
:cl:
fix: Removes a few runtimes related to the Prototype Space Station ruin.
/:cl:

Fixes some runtimes in the Prototype Space Station Ruin

---

_maps/map_files/SeleneStation/SeleneStation.dmm

Changed engineering a bit and fixed some issues. Makes engineering less cramped
I will include all changes in the changelog.
Screenshots:
Some features were missing from Selene like external air ports, cyborg charger, proper distro room. I've fixed that
:cl:
add: External air ports, atmos air refilling station, empty cans for atmos, cell charger in engineering, cyborg charger in engineering, proper distro for atmos, 
del: Removed partial atmos can in SM room since that's not how cans are made anymore
qol: added layer manifolds for gas supply to pure
fix: removed engineering access from engi sec outpost.
/:cl:

Selene Engineering tweaks and atmos remaster

---

fulp_modules/mapping/areas/areas.dm

For some reason the Theia PR removed `/area/ruin/space/has_grav/powered/beef/atmos`, resulting in the entire atmos area of the beefman station just not spawning in. 
Fixes #1201
It's probably good that the beefman station gets to be intact.
:cl:
fix: The beefman station will now spawn intact
/:cl:

Fixes Beefman station

---

fulp_modules/features/species/beefmen/mob/beefman.dm

Edits the beefman species trait descriptions for readability. Changes the icon for limb ripping off because the meat icon got moved to a paid version.
Clear language is good. Fixed icons are good.
:cl:
spellcheck: Upated beefman species trait descriptions.
/:cl:

Updates beefman species trait phrasing

---

fulp_modules/features/antagonists/bloodsuckers/code/bloodsucker/bloodsucker_datum.dm
fulp_modules/features/antagonists/bloodsuckers/code/bloodsucker/bloodsucker_flaws.dm
fulp_modules/features/antagonists/bloodsuckers/code/bloodsucker/bloodsucker_frenzy.dm
fulp_modules/features/antagonists/bloodsuckers/code/bloodsucker/bloodsucker_guardian.dm
fulp_modules/features/antagonists/bloodsuckers/code/bloodsucker/bloodsucker_life.dm
fulp_modules/features/antagonists/bloodsuckers/code/bloodsucker/subsystem_sunlight.dm

Fixes some punctuation and capitalization issues with bloodsucker descriptions. Clan is not a proper noun and doesn't need to be capitalized.
Looks more professional this way.
:cl:
spellcheck: punctuation and grammar updates
/:cl:

Cleans up blood sucker descriptions

---

_maps/map_files/PubbyStation/PubbyStation.dmm

Hi! This is the first time I've made a pull request on GitHub, so I apologize in advance if I've messed anything up or made any fatal mistakes.
Anyhow this PR should fix the cabling in Pubby Station's bathroom, which at the moment does not reach the bathroom's APC. This PR also removes a few unnecessary scrubber pipes from the bathroom and adds a rubber duck to it.
Before:
After:
Pubby Station's bathroom is probably meant to be connected to the power grid at round start. Unnecessary scrubber pipes just make things look messier, and a rubber duck is a nice addition to _any_ bathroom.
:cl:
fix: Fixes Pubby Station's bathroom and adds a rubber duck to it
/:cl:

Fixes Pubby Station's Bathroom

---

_maps/map_files/Heliostation/Heliostation.dmm
_maps/map_files/PubbyStation/PubbyStation.dmm
_maps/map_files/SeleneStation/SeleneStation.dmm
_maps/map_files/TheiaStation/TheiaStation.dmm

We have been using var edits on some SMES that didn't work as expected anymore, they were replaced with normal versions instead.
And solar SMES units come charged to give the crew a few extra minutes before they scream at engineers.
This was a VSC coding map edit so if something breaks, I will laugh and cry at the same time.
Power was wonky and after digging a bit I figured out why.
Some SMES units were linked to the main line while not being full, which drained the main line to nothing, if the SM wasn't setup ASAP on Helio. We also had 2 auxiliary power SMES unlinked from the net and I just linked them for extra power on Helio, some rooms drain way too much power because of how many lights it takes to keep such huge station well lit.
Something something hard to learn a job when their …

Fixes SMES and some buffs

---

_maps/map_files/TheiaStation/TheiaStation.dmm

- Adds floor tiles that were missing under some airlocks on Theia Station
- Removes one or two floor tiles which shouldn't have been under maintenance airlocks
- Adds a single, missing cable leading to Theia's cargo delivery office
- Adds a small, relevant Easter egg to Theia's showroom maintenance area:
Most non-maintenance airlocks should have tiles under them for aesthetic reasons. Cargo's delivery office should be connected to the grid at round start— though I can make a separate PR for the cable if necessary.
:cl:
fix: added previously missing tiles under some Theia Station airlocks
fix: added a missing cable leading to Theia's cargo delivery office
/:cl:

Fixes the tiling under some of Theia's airlocks/Adds a singular cable

---

_maps/map_files/Heliostation/Heliostation.dmm

Two of the engineering SMES units on Heliostation were accidentally removed recently. This PR adds them back in.
Fixes this:
:cl:
fix: Readds two SMES units that were accidentally removed from Heliostation engineering
/:cl:

Heliostation Missing SMES Fix

---

fulp_modules/_maps/wonderland.dmm
fulp_modules/mapping/areas/areas.dm

This PR does a fair bit to improve Wonderland's appearance. For lighting purposes the "Wonderland" area has been divided into two separate areas: Wonderland and Wonderland Chess Board. Most other changes are apparent in these two images:
_No more brutalist, riveted indestructible walls (though the walls are very much still indestructible!)_
Wonderland as is looks pretty bad. This PR fixes a few minor mistakes present in the original map, adds better lighting, and overall aims to improve the map's detail. (Oh, also, the water is now *real water*!)
:cl:
add: Added better lighting to Wonderland
add: Gave Wonderland more detail overall
fix: Fixed a few minor mistakes present in the original Wonderland map
code: Divided Wonderland into two separate areas for Wonderland itself and Wonderland's …

Improves Wonderland's Appearance

---

_maps/map_files/TheiaStation/TheiaStation.dmm

This PR replaces the large tanks in Theia's ordnance lab with large oxygen tanks.
Every ordnance lab requires a large tank full of oxygen for basic gas synthesis. Theia's large oxygen tank currently has no oxygen in it, and this PR fixes that.
:cl:
fix: The large oxygen tank in Theia's ordnance lab now actually has oxygen in it.
/:cl:

Theia ordnance O2 tank fix

---

_maps/map_files/Heliostation/Heliostation.dmm

This PR adds an ordnance data disk to Heliostation's ordnance testing lab.
Ordnance data disks contain the NT Frontier program, which is vital to most ordnance-related research. Without ordnance data disks scientists are forced to download NT Frontier instead of just moving it from a disk onto a device of their choosing.
:cl:
qol: Adds an ordnance data disk to Helio's ordnance testing lab
/:cl:

Gives Heliostation's ordnance testing lab an ordnance data disk

---

_maps/map_files/Heliostation/Heliostation.dmm

This PR changes the name of a singular pump on Heliostation from "Distro Stagsing to Filter" to "Mix to Air".
"Stagsing" is a misspelling of "staging". Also "Distro Staging to Filter" does not accurately describe what the pump actually does.
:cl:
spellcheck: Fixed a pump inaccurately labeled "Distro Stagsing to Filter"
/:cl:

Fixes the name of a singular pump

---

_maps/map_files/TheiaStation/TheiaStation.dmm

This pull request makes Theia Station's chapel mass driver functional and expands its room a bit. . . 
<sup><sup>. . .this PR also puts a **whiny plushie** on the mass driver.</sup></sup>
At the moment Theia's chapel mass driver room has no button for its mass driver— which itself is facing the wrong direction. This PR fixes both of those things.
:cl:
fix: fixes Theia Station's chapel mass driver
/:cl:

Theia Station chapel mass driver fix

---

fulp_modules/features/antagonists/monster_hunter/hunting_contract.dm
fulp_modules/features/antagonists/monster_hunter/monsterhunter_weapons.dm
fulp_modules/features/antagonists/monster_hunter/wonderland.dm

This pull request changes a lot of monster hunter descriptions and adds hidden descriptions that are only viewable by monster hunters and (in one instance,) their victims.
These changes may make monster hunter friendlier to new players. In addition it might help anyone who doesn't have an encyclopedic grasp of monster hunter mechanics.
:cl: 
add: Added hidden descriptions to most monster hunter items in order to better explain their function
/:cl:

Monster Hunter description changes

---

_maps/map_files/TheiaStation/TheiaStation.dmm

This PR edits some areas near the center of Theia Station. The full list of changes made is as follows:
- Edits Theia's coffee stands for functionality and appearance/adds shutters to one
- Adds two previously missing wood tiles
- Removes a singular broken wood tile in the bar that would cause the irreversible destruction of a piece of wood siding whenever repaired
- Adds a rack near unanchored equipment just outside the gravity generator so as to prevent said equipment from floating all the way to the medical bay whenever gravity stops working and someone passes by
- Replaces the tiling surrounding Theia's centerpiece cherry tree with dark tiling so as to provide better contrast
- Gives the HOP line dark tiling because it just looks nice
- Gives the vacant commissary a functional shutter …

Minor edits to Theia Station's center

---

fulp_modules/_maps/wonderland.dmm
fulp_modules/features/antagonists/monster_hunter/hunting_contract.dm
fulp_modules/features/antagonists/monster_hunter/monsterhunter_datum.dm
fulp_modules/features/antagonists/monster_hunter/monsterhunter_weapons.dm
fulp_modules/features/antagonists/monster_hunter/wonderland.dm
fulp_modules/features/antagonists/monster_hunter/wonderland_apocalypse.dm

This PR attempts to implement fixes for a handful of Monster Hunter bugs/exploits/balance problems that I've discovered. A full list of these problems and their respective fixes as of this PR is as follows:
1. In PR [#1217](https://github.com/fulpstation/fulpstation/pull/1217) I accidentally added what I can only assume is snow from Icebox to Wonderland. It has been replaced with regular snow (also I anchored a snowman— I might make it not dense later.)
2. A lot of vital monster hunter equipment was flammable/vulnerable to acid and therefore very easy to destroy. Accordingly the majority of monster hunter equipment has been made either fireproof and acidproof or (in one instance) indestructible. (Oh also the weapon upgrade table in Wonderland could be deconstructed with a wrench, so …

Monster Hunter mass bug/balance fixes

---

_maps/map_files/TheiaStation/TheiaStation.dmm

This PR aims to partially fix Theia Station's currently nonfunctional disposals system by replacing one particular segment of faulty piping. This PR also improves the appearance of Theia's disposals room somewhat.
Currently, Theia's disposals system is only really capable of doing this:
https://github.com/user-attachments/assets/14aa43f4-183d-4f66-8bef-9f89a5068d3c
This PR fixes that by making all trash route directly to Theia's disposals room. This, however, means that the disposals mailing system is nonfunctional in turn. It isn't functional at the moment either though, so this is still a net benefit.
An issue report may need to be submitted regarding Theia's disposals mailing system since I can't seem to find an easy fix for it that doesn't involve reworking the entire piping network. …

Partial Theia disposals fix

---

_maps/map_files/TheiaStation/TheiaStation.dmm

Fixes Theia tcomms so channels other than common, sec and command work
Moves AI turret controller up so it isnt at a camera blindspot:
Fixes sci and engi sec outpost camera console
Adds Armoury shutter buttons so warden can now open armoury
Adds a bar seating indicator placer at bar
Moves around or adds camera to the following locations so AI can see the doors
-Sec entrance
-Robo
-mining
-cargo warehouse
-cargo office
Theia Station fixes wooooooo
:cl:
fix: Multiple Theia station map fixes
/:cl:

Theia Tcomms fix + other fixes

---

_maps/map_files/PubbyStation/PubbyStation.dmm

> [!NOTE]
> This PR is almost an exact copy of [#1239](https://github.com/fulpstation/fulpstation/pull/1239), which I chose to close due to a particularly difficult merge conflict. Most of the map changes in this new PR are exactly the same though I have adjusted a few more things here and there.
This PR attempts to improve Pubby Station's exterior a bit (mostly but not exclusively by moving around, adding, and deleting lattices/grilles.) The primary changes of note made in this PR include the following:
1. Adding a space basketball court: 
2. Adding a small asteroid debris cloud near Pubby's bomb testing asteroid: 
3. Giving Pubby's telecomms sat a bit more exterior breathing room: 
<sup>(Also I added a singular tile that was missing under a door near Pubby's mining shuttle dock.)</sup> …

Pubby Station Exterior/Space Detailing (again!)

---

_maps/map_files/TheiaStation/TheiaStation.dmm

This PR makes a wide number of improvements to Theia Station. Due to the fact that I didn't keep track of what I was doing as I did it the following list of changes is likely incomplete, but here it is nonetheless:
- Adds more dirty, burnt, and broken tiling to all maintenance areas for aesthetic purposes.
- Adds more random spawners to all maintenance areas.
- Adds more lightbulbs to all maintenance areas.
- Adds steam vents to all maintenance areas.
- Generally makes maintenance on Theia roomier (at least in appearance.)
- Gives the gravity generator's SMES a bit more room in order to keep its wiring sane.
- Replaces the gravity generator's reinforced glass windows with reinforced plasma-glass windows.
- Replaces the security lobby's reinforced glass flooring with reinforced …

Incredibly broad Theia Station improvements

---

_maps/map_files/PubbyStation/PubbyStation.dmm

This pull request adds a total of three new escape pods to Pubby Station. One is located at security, another at the monastery, and the last one is near disposals in science/cargo maintenance.
<details><summary>Images of the new escape pods</summary>
</details>
Currently Pubby Station only has one escape pod, and the fact that it even is an escape pod is fairly unintuitive (since it's the public mining shuttle.) This PR fixes that by adding three new ones. (This also means that the budget/luxury escape pod station perks can now work on Pubby Station.)
:cl:
add: Added more escape pods to Pubby Station
/:cl:

Adds more escape pods to Pubby Station

---

_maps/map_files/Heliostation/Heliostation.dmm

This PR edits Heliostation's vault a bit by adding a previously missing gold crate to it and making it look like this:
<details><summary>Expand for image of new vault appearance shown in StrongDMM</summary>
</details>
(Also this PR attempts to fix two other minor mapping errors, including a tile with two racks and an improperly layered plush in the bar.)
Heliostation's vault currently lacks a gold crate, which is a rather essential feature of any station vault (especially on low-pop rounds where gold is necessary to build positronic brains and AI shells.)
:cl:
fix: added a previously missing gold crate to Heliostation's vault and changed up its appearance a bit
/:cl:

Heliostation vault edits

---

config/config.txt
fulp_modules/fulp_world/fulp_config.dm
fulp_modules/fulp_world/public_restart_vote.dm
tgstation.dme

After 2 hours* have elapsed, players will be able to host a Shuttle Vote. If it passes, the shuttle will be called with no possibility of recalling. If it fails, it can be rerun every 20 minutes.
Sample:
https://github.com/user-attachments/assets/a96a7dbf-e9c3-466d-b88e-edd854afe123
It behaves like a standard vote, in that all players (dead or alive) can vote in and start it.
(*The actual value is based on config. A sample of how config.txt will need to be changed is provided in the PR.)
Avoids situations where the round drags on due power problems, consoles being broken, everyone being dead, etc.
Two hours is a reasonably long time for a round, and so this should rarely cut a good round short. Meanwhile, it will cut through plenty of tedious waits for an admin to call it, or for someone …

Players can now start a shuttle vote 2 hours into the round

---

fulp_modules/features/admin_chicanery/smites/catification.dm
tgstation.dme

This PR adds a new admin smite which spawns a cateor near a target and launches it at them (with additional target immobilization options.) This probably isn't coded very efficiently, but it is by all means functional. A video demonstration of the new smite can be found through the Youtube link [here](https://www.youtube.com/watch?v=Am4zrSS626g).
It's a fun thing for admins to interject into a round regardless of context.
:cl:
add: added a new admin smite which involves cateors

Adds a basic cateor smite

---

_maps/map_files/SeleneStation/SeleneStation.dmm

This PR spruces up Selene Station's service department (bar, kitchen, service hallway, surrounding maintenance, etc.) a bit. See the results of the MapDiffBot check on this PR for images.
Currently this portion of Selene Station is a bit lacking in detail and general stylistic consistency, so this PR makes improvements to address that.
:cl:
map: made an assortment of improvements to Selene Station's main service department area
/:cl:

Selene service department improvements

---

fulp_modules/_maps/RandomRuins/IceRuins/beef_cytology.dmm
fulp_modules/_maps/RandomRuins/SpaceRuins/beef_station.dmm
fulp_modules/_maps/RandomRuins/SpaceRuins/syndicate_engineer.dmm

By "non-standard mapping", I'm referring to things not allowed by linters. This includes the use of dir in a non-directional spawner instead of using the directional prefabs, improper capitalization of door names, grilles and windows accidentally placed twice over the same tile, etc.
Fixes the issues that #1290 will bring to light, as it will allow map tests to be run on these maps too.
Nothing player-facing

Fixes non-standard mapping in Govyadina Station, the Beefman Research Outpost and the Syndicate Engineering Outpost

---

_maps/map_files/Heliostation/Heliostation.dmm
_maps/map_files/PubbyStation/PubbyStation.dmm
_maps/map_files/SeleneStation/SeleneStation.dmm
_maps/map_files/TheiaStation/TheiaStation.dmm

This PR adds singular roboticist spray cans to Pubbystation, Selenestation, Heliostation, and Theiastation.
This is an incredibly minor thing that might've been overlooked in the last TGU :P 
:cl:
fix: Added previously missing roboticist spray cans to every robotics lab on a Fulpstation map.
/:cl:

Adds missing roboticist spray cans to every Fulpstation map

---

_maps/map_files/TheiaStation/TheiaStation.dmm
fulp_modules/mapping/station_objects/trees.dm

This PR adds a Christmas tree spawner to Theiastation, and (for the sake of allowing that tree to render properly) gives Christmas trees a new layer value.
Theiastation should have a Christmas tree like all other station maps; this PR adds one.
:cl:
fix: Theiastation should have a Christmas tree now
/:cl:

Adds a Christmas tree spawner to Theiastation

---

fulp_modules/features/antagonists/bloodsuckers/code/powers/feed.dm

This PR implements a quick fix for a bug that renders the Bloodsucker Bite ability unusable. The bug seems to be caused by the improper clearing of the 'target_ref' variable upon the ability's failure to initiate.
This fixes [this](https://github.com/fulpstation/fulpstation/issues/1313) issue.
:cl:
fix: Fixed a bug involving the Bloodsucker Bite ability.
/:cl:

Bloodsucker Bite Ability Bug Fix

---

fulp_modules/features/antagonists/bloodsuckers/code/structures/bloodsucker_crypt.dm

This PR adds a quieter version of the burning sound loop used by bonfires to bloodsucker braziers. 
This small aesthetic detail might add to the general ambience of bloodsucker lairs.
:cl:
add: Added the bonfire burning sound loop to braziers.
/:cl:

Adds the Bonfire Burning Sound Loop to Braziers

---

_maps/map_files/PubbyStation/PubbyStation.dmm

This PR makes a number of light alterations to Pubby Station's medical bay. One of the primary changes of note is the removal of the (currently nonfunctional and generally confusing) corpse disposal system. Defibrillator wall mounts have also been added where needed, and the 3x3 "abandoned medbay" area has been integrated into medical maintenance due to its insufficient "abandoned mebday"-ness. Images may be found in the results of the MapDiffBot check on this PR as per always.
Pubby Station's medical bay currently has a few functional/aesthetic faults, and this PR addresses them while also improving the appearance of the area overall. (Also most of the disposal units in the medical bay were labeled as "corpse disposal" units even though 75% of them don't actually lead to the morgue.) …

Pubby Station Medical Edits

---

_maps/map_files/TheiaStation/TheiaStation.dmm

This PR makes a number of edits to Theia Station's AI satellite. The most notable changes include the following: 
- The removal of one _really_ annoying firelock in telecomms.
- The slight expansion of the main AI chamber. 
- The rewiring of the entire satellite along with the addition of two power monitoring consoles.
Images for these changes may be found in the results section of the MapDiffBot check on this PR as per always.
These changes develop a currently underdeveloped portion of Theia Station.
:cl:
map: Made some adjustments to Theia Station's AI satellite.
/:cl:

Theia Station AI Satellite Edits

---

_maps/map_files/TheiaStation/TheiaStation.dmm

It seems that the fixes made to Theia Station's pods in PR #1262 were accidentally reverted/overridden in or around #1269. This PR undoes this undoing and does the thing (which was originally done) again in much the same way. (I did take the opportunity to make a few slight adjustments/fixes to areas around the pods though.)
(See the "Why It's Good For the Game" section for PR #1262 if desired.)
:cl:
fix: Reimplements an accidentally reverted fix to Theia Station's escape pods from PR #1262 
/:cl:

Escape pod early launch functionality map fix (again!)

---

_maps/map_files/TheiaStation/TheiaStation.dmm
config/maps.txt

Unfortunately, our last proposal worked exactly as advertised, if you read the fine print. A single destination, Dormitories, did not work properly. Now it does.
Bugfix
:cl:
map: Packages addressed to "Dormitories" now arrive correctly on Theiastation
/:cl:

Corrects one missing mail splitter in TheiaStation

---

_maps/map_files/PubbyStation/PubbyStation.dmm

This pull request replaces a pole in Pubby Station's abandoned gambling den (and also details the area around it just a bit). After making this PR I noticed that the CI Suite check for Pubbystation was failing due to a singular improperly area'd window near cargo, so that has been fixed as well.
<details><summary>Screenshot of the old (prior to the thing with the singular window ruining it) MapDiffBot check:</summary>
</details>
The pole is an explicit reference which probably doesn't fit with Fulpstation's intentions as a server.
:cl:
map: Removed a pole from Pubby Station's abandoned gambling den.
/:cl:

Replaces a Pole on Pubby Station

---

_maps/map_files/TheiaStation/TheiaStation.dmm

So I've figured out that the "Check Plumbing" mapping verb exists, and with this PR I have used it to correct a few minor mistakes with the piping on Theia Station (the piping in/around atmospherics hasn't been touched though). As per always, see the results of the MapDiffBot check for images.
This PR minimizes the number of disconnected/improperly placed pipes on Theia Station.
:cl:
map: Made a handful of general corrections to the piping on Theia Station.
/:cl:

Theia Station Piping Fixes

---

_maps/map_files/TheiaStation/TheiaStation.dmm

In PR #1249 I put a handful of welding fuel decals under a high capacity fuel tank in Theia Station's engineering maintenance area. This turned out to be a very bad idea. I understood that the decals could trigger an explosion if ignited, but I underestimated the overall probability of them igniting on any given round. 
I later reduced the number of welding fuel pools in PR #1252, but that didn't really help much. Given the benefit of hindsight, I now realize that the entire concept is inherently flawed. This PR removes all of the aforementioned welding fuel pools and moves a couple of fuel tanks away from each other to make chain reaction explosions less likely.
Having welding tanks explode every four rounds or so due to a very poor mapping decision is a bad thing. This PR rectifies that …

Theia Station Engineering Fuel Tank Fix

---

fulp_modules/features/events/cateors/cateor.dm

This PR does the following:
1. Fixes a bug/runtime error which caused cateors to not properly give cat organs to lizardpeople and (probably) a few other species. 
2. Makes cateors no longer explode people who have already been given cat ears and a cat tail.
3. Makes cateors give the "drugginess" status effect to felinids in addition to stunning them (because catnip).
These changes fix a couple of cateor bugs and generally just improve them a bit in terms of functionality/polish.
:cl:
fix: Fixed a bug which caused cateors to not properly "felinidify" certain species.
fix: Cateors no longer explode people who already have cat ears and a cat tail.
balance: Cateors now also give felinids the "drugginess" status effect in addition to stunning them.
/:cl:

Cateor Bug Fixes 

---

fulp_modules/features/spells/_spells.dm

In PR #1291 I attempted to fix some bugs involving the Summon Dancefloor spell. For the most part those fixes worked, but it seems I missed a few things. This PR makes the following additional fixes:
1. Summon Dancefloor can no longer be pointlessly upgraded by wizards.
2. Summon Dancefloor will function a bit more reliably if its user isn't directly on a tile.
3. The "sparkles" visual effect copied to Summon Dancefloor from dance machines now properly deletes itself in tandem with its dancefloor.
These changes make a Fulpstation spell a bit less buggy.
:cl:
fix: Fixed a few minor bugs involving the spell Summon Dancefloor.
/:cl:

Summon Dancefloor Bug Fixes 2

---

_maps/map_files/PubbyStation/PubbyStation.dmm
_maps/shuttles/cargo_pubby.dmm

This PR fixes a few things that were missed in #1325 (mainly the incorrect ID-ing of one conveyor belt, a few improperly styled tiles, and the lack of airtight flaps on Pubby's cargo shuttle).
These changes correct a few things that were missed in a recent PR.
:cl:
map: Fixes a few things that were overlooked in a recent edit of Pubby Station's cargo bay.
/:cl:

Minor Pubby Cargo Fixes Following Recent Improvements

---

_maps/fulp_maps/RandomRuins/SpaceRuins/allamericandiner_openforbusiness.dmm

"The kitchen setup is close to the way most stations are set"
She lied
adds these two machines to the ruin, also adds an not pictured microwave
you should actually be able to cook on the cooking ghost spawner
:cl:
fix: essential kitchen equipment added to the ghost diner
/:cl:

ghost kitchen fixes

---

_maps/map_files/TheiaStation/TheiaStation.dmm

This PR slightly adjusts the values on a singular AI satellite SMES in order to ensure that telecomms is powered properly at round start. 
As part of PR #1318 I slightly edited Theia Station's AI satellite power network in order to make it slightly more station-independent. In doing so I accidentally overlooked the fact that the satellite has three SMES units, and the main station-to-ai-sat SMES needs to power two others.
:cl:
map: Made Theia Station's telecomms room properly receive power at round start.
/:cl:

Theia Station Telecomms Power Fix

---

fulp_modules/features/antagonists/bloodsuckers/code/powers/targeted/brawn.dm

This PR removes the 'BP_CANT_USE_WHILE_INCAPACITATED' flag from the bloodsucker Brawn ability.
Part of this abilities function is allowing you to escape from restraints, and you can't use it to do that if you can't use it while incapacitated.
:cl:
fix: Made the bloodsucker Brawn and Brash abilities useable while handcuffed.
/:cl:

Makes Brawn and its Subtype (Brash) Useable While Handcuffed

---

fulp_modules/features/antagonists/bloodsuckers/code/bloodsucker/bloodsucker_flaws.dm
fulp_modules/features/antagonists/bloodsuckers/code/powers/feed.dm

This PR does two things:
1. Fixes a couple of issues which make the bloodsucker Feed ability unusable. These issues were partially addressed in PR #1315, but they ultimately seem to be caused by an early return implemented in PR #1300. That early return has been removed in favor of just not logging feed attempts where 'feed_target = null'.
2. Adds a TGUI warning to the Brujah clan on selection so as to make players aware that joining the clan will increase their Frenzy threshold.
1. I don't _think_ we need to log bite attempts where 'feed_target = null', and as it currently stands that only seems to cause a lot of attack log spam.
2. Players should really know ahead of time that joining the Brujah clan will raise their Frenzy threshold by 375.
:cl:
qol: Made players attempting to join the …

A Small Bloodsucker Bite Fix and a Bit of QOL

---

_maps/map_files/SeleneStation/SeleneStation.dmm

This pull request removes the round start N2O leak near Selene Station's medical maintenance area. This PR also spruces up the area around where that leak was and replaces the main portion of the removed area with an equivalent gimmick room.
N2O can permanently render player characters unconscious without external assistance. It is very dangerous on low population rounds and can lead to very negative player experiences when leaked at round start.
:cl:
map: Replaced the round start N2O leak near medical maintenance on Selene Station with something a bit more standard.
/:cl:

Selene Station N2O Leak Replacement

---

_maps/fulp_maps/RandomRuins/SpaceRuins/allamericandiner_openforbusiness.dmm
code/__DEFINES/fulp_defines/fulp_defines.dm
fulp_modules/mapping/areas/areas.dm
fulp_modules/mapping/ruins/space/ghost_diner/ghost_diner.dm

This PR makes a fair number of fixes and edits to the chef ghost role ruin introduced in PR #1356 by @sylvia-from-fulp-station. These changes affect both the ghost role itself and its map. What follows is a (mostly) comprehensive list of everything done in this PR sorted into the categories of fixes, edits, and additions:
1. Resets the icon offsets for a lot of machines on tables in the diner ruin. (Machines automatically offset themselves on tables, and doing it manually through varediting will cause them overcorrect their offset).
2. Adds tiling that was missing under a number of airlocks.
3. Adds the "template passthrough" area to blank portions of the map (unoccupied space areas).
4. Adds the nearstation area to occupied space areas on the map.
5. Gives the chef ghost roles proper IDs …

Chef Ghost Role Fixes, Edits, and Minor Additions

---

_maps/map_files/TheiaStation/TheiaStation.dmm

This PR makes a number of edits to Theia Station's permabrig for both functional and aesthetic purposes. A singular tile with doubled piping halfway across the map has also been corrected with this PR.
<details><summary>Image of the old (prior to the thing with the pipe) MapDiffBot check:</summary>
</details>
Theia Station's permabrig is currently a bit underdeveloped. It lacks a _few_ things possessed by other permabrigs, and its areas  need a bit more partitioning.
:cl:
map: Edited and generally detailed Theia Station's permabrig.
/:cl:

Theia Station Permabrig Edits

---

_maps/fulp_maps/RandomRuins/SpaceRuins/beef_station.dmm
code/__DEFINES/fulp_defines/fulp_defines.dm
fulp_modules/mapping/ruins/space/beefman_station/beefman_station.dm

This PR improves the atmospherics/piping on the Govyadina (Beef) Station ruin/ghost spawner by expanding the atmospherics area a bit, replacing most piping with smart piping where possible, adding nitrogen to the atmospherics area, providing the atmospherics area with a functional gas mix chamber, and plumbing the entire ruin.
<sup>I also took this opportunity to add a few light switches, a crystallizer circuit board, and a custom atmospherics locker.</sup>
You can't do much with the atmospherics setup on this ruin currently, and this PR addresses that.
:cl:
map: Improved the atmospherics setup on the Govyadina (Beef) Station ruin/ghost spawner.
/:cl:

Govyadina Station Atmospherics/Piping Edits

---

fulp_modules/features/antagonists/bloodsuckers/code/clans/clan_nosferatu.dm

This PR gives members of the Nosferatu bloodsucker clan a 33% chance to flip nearby light switches every tick.
It's a _SpongeBob SquarePants_ reference. (See [https://www.youtube.com/watch?v=hDwc8hvB3vg](https://www.youtube.com/watch?v=hDwc8hvB3vg)).
:cl:
add: Made Nosferatu bloodsuckers have a 33% chance to flip nearby light switches every tick.
/:cl:

Noferatu Bloodsucker Light Flickering

---

_maps/map_files/TheiaStation/TheiaStation.dmm

This PR (similarly to PRs #1360 and #1364) corrects a lot of mapping errors on Theia Station via the usage of mapping verbs. Images may be found in the MapDiffBot check on this PR as per always.
_See the "Why It's Good For The Game" section on PR #1360._
:cl:
map: Fixed a lot of things on Theia Station (missing intercoms, missing light switches, et cetera.)
/:cl:

Theia Station Mapping Verb Sweep

---

_maps/map_files/PubbyStation/PubbyStation.dmm

This PR corrects a lot of Pubby Station mapping errors that were discovered via the usage of mapping verbs. I also took this opportunity to add more entertainment monitors to Pubby since they've become a fair bit more useful recently. A few other miscellaneous adjustments were performed here and there as well. Images may be found in the results of the MapDiffBot check on this PR as per always.
Light switches, intercoms, unobstructed atmospheric objects, properly connected piping, request consoles, and properly tagged cameras are all essential aspects of a good map; this PR adds them.
:cl:
map: Fixed a lot of things on Pubby Station (missing intercoms, missing light switches, et cetera.)
/:cl:

Pubby Station Mapping Verb Sweep

---

fulp_modules/Z_edits/event_overrides/grav_gen_blackout.dm
tgstation.dme

This PR makes the gravity generator blackout event much less common on low population rounds. It is outright removed on rounds with less than fifteen players, and it is still possible (albeit less likely) on rounds with less than thirty. This PR does NOT prevent the gravitational anomaly event from causing the generator to malfunction when its anomaly delaminates.
The gravity generator blackout event has a max occurrence limit of twenty, and its weight is set to thirty whereas most events fall within the range of ten to twenty. It also doesn't have any population requirements by default, so it can become _very_ annoying on low population rounds (especially when there's nobody around with the access required to reset the generator).
:cl:
balance: Made the gravity generator blackout event …

Adjusts the Gravity Generator Blackout Event on Low Population Rounds

---

_maps/map_files/Heliostation/Heliostation.dmm

This PR fixes/adjusts a lot of things on Heliostation that were discovered via the usage of mapping verbs. Images may be found in the MapDiffBot check on this PR as per always.
_See the "Why It's Good For The Game" section on PR #1360 (which is identical to this PR except in the particular map that it focuses on)._
:cl:
map: Fixed a lot of things on Heliostation (missing intercoms, missing light switches, et cetera.)
/:cl:

Heliostation Mapping Verb Sweep

---

_maps/fulp_maps/RandomRuins/IceRuins/beef_cytology.dmm
code/__DEFINES/fulp_defines/fulp_defines.dm
fulp_modules/mapping/ruins/icemoon/beefman_cytology/beefcyto_spawner.dm

This PR makes a couple adjustments to the beefman cytology ghost role. The main addition to the role is a z-level restriction component (much like the one implemented in PR #1359) that turns those spawned on the ruin into meat slabs if they leave their z-level. The map has been adjusted to account for this, with a small bridge being added to allow beef cytologists to cross their liquid plasma moat and explore the lower levels of the Icemoon if they desire.
This change permits a bit more freedom to the beefman cytology ghost role while at the same keeping it focused on cytology (and away from the station).
:cl:
add: Restricted those spawned in on the beefman cytology ruin to their ruin's z-level. The ruin's map has been made less restrictive accordingly.
/:cl:

Beefman Cytology Adjustments 

---

fulp_modules/features/antagonists/bloodsuckers/code/powers/_powers.dm

This PR gives bloodsucker abilities their own action subpanel/tab as part of the typical SS13/BYOND status panel (the one that's always on the side of the screen and has a lot of clickable text commands). This functions in much the same way as it does with spells (the tab is only given to people who receive the particular abilities associated with it, et cetera).
These changes allow bloodsuckers to use their abilities even if their ability HUD buttons cease to function for whatever reason. 
:cl:
qol: Bloodsucker actions are now part of a subpanel/tab within the standard BYOND game status panel.
/:cl:

Makes Bloodsucker Abilities Part of a Tab on the Status Panel

---

_maps/map_files/Heliostation/Heliostation.dmm
_maps/map_files/PubbyStation/PubbyStation.dmm
_maps/map_files/SeleneStation/SeleneStation.dmm
_maps/map_files/TheiaStation/TheiaStation.dmm

This PR makes use of the "red alert access" helper recently added through the last TGU. It has applied to EVA and medical storage doors on every Fulpstation map. This is consistent with the helper's [implementation on our upstream](https://github.com/tgstation/tgstation/pull/89424). 
This is a minor thing that might've been overlooked in the last TGU. Accounting for it maintains map consistency.
:cl:
fix: EVA and medical storage airlocks on Fulpstation maps now have their access requirements lifted on red alert.
/:cl:

Adds Red Alert Access to Appropriate Doors on Fulp Maps

---

_maps/map_files/Heliostation/Heliostation.dmm
_maps/map_files/PubbyStation/PubbyStation.dmm
_maps/map_files/SeleneStation/SeleneStation.dmm
_maps/map_files/TheiaStation/TheiaStation.dmm

This pull request adds airtight coldroom flaps to telecomms on every Fulpstation map. Images may be found in the results of the MapDiffBot check on this PR as per always.
This is a relatively minor thing that might've been missed in the last TGU. Implementing it maintains map consistency between our maps and TG's.
:cl:
fix: Added airtight coldroom flaps to telecomms on every Fulpstation map.
/:cl:

Adds Telecomms Flaps to Every Fulpstation Map

---

fulp_modules/features/antagonists/bloodsuckers/code/powers/targeted/mesmerize.dm

This PR replaces a couple of `<=` operators with `<` operators.
This makes the ability functionally consistent with its description (and fixes #1399). 
:cl:
fix: Made the bloodsucker Mesmerize ability work as indicated in its description.
/:cl:

Fixes the Bloodsucker "Mesmerize" Ability 

---

fulp_modules/features/antagonists/bloodsuckers/code/powers/feed.dm
fulp_modules/features/antagonists/bloodsuckers/code/powers/targeted/mesmerize.dm
fulp_modules/features/antagonists/bloodsuckers/code/powers/tremere/dominate.dm
fulp_modules/features/antagonists/bloodsuckers/code/powers/vassal/vassal_fold.dm

This pull request fixes #1401 by setting the `hidden` parameter on several `do_after()` calls to `TRUE`. 
As described in the previously mentioned issue: these abilities are supposed to be stealthy and having cogwheels appear over their user hinders that.
:cl:
fix: Cogwheels will no longer appear over the users of certain bloodsucker abilities.
/:cl:

Fixes Certain Stealthy Bloodsucker Abilities Producing a Cogwheel

---

_maps/shuttles/cargo_pubby.dmm

This fixes some misaligned doors in the Pubbystation cargo shuttle
Currently the loading doors for the cargo shuttle in Pubbystation do not line up with the conveyors to and from the Cargo Department. This slows down cargo quite a lot as you have to load/unload from the airlocks.
This pull request fixes that issue, making cargo faster overall at the cost of adding a single extra tile to both conveyors.
:cl:
fix: Moved the shuttle loading doors to line up with the department loading doors
/:cl:

Fixes Pubby cargo shuttle doors

---

fulp_modules/features/antagonists/bloodsuckers/code/bloodsucker/bloodsucker_procs.dm
fulp_modules/features/antagonists/bloodsuckers/code/powers/_powers.dm
fulp_modules/features/antagonists/bloodsuckers/code/powers/gohome.dm
fulp_modules/features/antagonists/bloodsuckers/code/powers/masquerade.dm
fulp_modules/features/antagonists/bloodsuckers/code/powers/tremere/_powers_tremere.dm
fulp_modules/features/antagonists/bloodsuckers/code/powers/vassal/distress.dm
fulp_modules/features/antagonists/bloodsuckers/code/powers/vassal/recuperate.dm
fulp_modules/features/antagonists/bloodsuckers/code/powers/vassal/vassal_fold.dm
fulp_modules/features/antagonists/bloodsuckers/code/powers/veil.dm

This PR aims to better communicate the fact that Bloodsucker powers have 'levels' separate from their owner's rank. This has been accomplished by adding the ability's level to its HUD icon's description.
<details><summary>Expand for example image of the new HUD icon description.</summary>
</details>
While coding this I also _slightly_ refactored how powers are leveled and how their buttons are updated.
This aspect of bloodsucker powers isn't very intuitive[^1], but I do think that retaining it makes them interesting. Having to consider which powers you want to level up quicker via early selection does lend a fair bit of strategy towards the act of choosing them. 
(Also this may help with issue #1399.)
[^1]:  I myself recently forgot about it and replaced most instances of the word "level" …

Better Communicates Bloodsucker Power Leveling 

---

_maps/map_files/SeleneStation/SeleneStation.dmm

Makes the Engi entrance a bit friendlier to crew trying to talk with engineers by swapping the outward airlock for a public one and adding windows to the foyer.
Also fixes some not so hidden pipes, and missing firelocks to most of engineering, and missing firealarms, and kills the chair get up and go work lazy ass, and adds windows to the secure storage, and nearstation near secure storage, and the TCOMs air alarm won't trigger roundstart, and likely other small stuff I forgot.
Easier to check if any engineer is vibing at the foyer, and makes the hallways a bit prettier with hidden pipes.
fix: Some not so hidden pipes at Selene's Engineering hallway
map: Change the entrance of Selene's Engineering by allowing crew to get access closer to the foyer and adding windows …

Changes and fixes to Selene's Engineering

---

fulp_modules/features/antagonists/bloodsuckers/code/bloodsucker/bloodsucker_frenzy.dm
fulp_modules/features/antagonists/bloodsuckers/code/structures/bloodsucker_mirror.dm

This PR brings a couple lines of (mainly bloodsucker-related) code up to date with a recent TG refactor of client colours (TGstation PR [#89843](https://github.com/tgstation/tgstation/pull/89843)).
The red overlay provided by bloodsucker frenzying and blood mirror usage is permanent without this.
:cl:
fix: Fixed the overlay provided by bloodsucker frenzying and blood mirror usage being permanent.
/:cl:

Fixes a Couple of Client Colours Being Permanent
